// مكتبة المحاصيل اليمنية - بيانات علمية واقعية
// المصادر: FAO، وزارة الزراعة اليمنية، IITA، تقارير المزارعين

export interface CropInfo {
  id: string;
  nameAr: string;
  nameEn: string;
  scientificName: string;
  category: 'cereals' | 'cash' | 'fruits' | 'vegetables' | 'forage' | 'industrial';
  icon: string;

  // المتطلبات البيئية
  growingSeasonMonths: number; // مدة الموسم بالأشهر
  plantingSeason: string; // موسم الزراعة
  temperatureMin: number; // °C
  temperatureMax: number;
  rainfallMin: number; // مم/سنة
  rainfallMax: number;
  altitudeMin: number; // متر
  altitudeMax: number;
  soilType: string; // التربة المناسبة
  soilPH: string; // الحموضة
  saltTolerance: 'low' | 'medium' | 'high';

  // الإنتاجية والكثافة
  yieldPerHectare: number; // طن/هكتار
  plantDensityPerHa: number; // نبات/هكتار
  maturityDays: number; // أيام للنضج

  // الاحتياجات المائية
  waterNeedMm: number; // مم/موسم
  irrigationType: 'drip' | 'sprinkler' | 'flood' | 'rainfed';

  // اقتصاديات
  seedCostPerHa: number; // ريال يمني
  fertilizerCostPerHa: number;
  laborCostPerHa: number;
  totalCostPerHa: number;
  pricePerTon: number; // سعر بيع الطن
  revenuePerHa: number; // إيراد/هكتار
  profitPerHa: number; // ربح/هكتار

  // ملاحظات
  notes: string;
  suitableRegions: string[]; // مناطق يمنية مناسبة
}

export const CROPS_LIBRARY: CropInfo[] = [
  // === الحبوب ===
  {
    id: 'wheat',
    nameAr: 'قمح',
    nameEn: 'Wheat',
    scientificName: 'Triticum aestivum',
    category: 'cereals',
    icon: '🌾',
    growingSeasonMonths: 4,
    plantingSeason: 'نوفمبر - ديسمبر',
    temperatureMin: 10, temperatureMax: 25,
    rainfallMin: 250, rainfallMax: 600,
    altitudeMin: 500, altitudeMax: 2500,
    soilType: 'طينية رملية خصبة',
    soilPH: '6.0 - 7.5',
    saltTolerance: 'medium',
    yieldPerHectare: 3.0,
    plantDensityPerHa: 250,
    maturityDays: 120,
    waterNeedMm: 450,
    irrigationType: 'sprinkler',
    seedCostPerHa: 9000000,
    fertilizerCostPerHa: 260000000,
    laborCostPerHa: 15000000,
    totalCostPerHa: 50000000,
    pricePerTon: 200000,
    revenuePerHa: 600000,
    profitPerHa: 550000,
    notes: 'محصول استراتيجي للأمن الغذائي. اليمن يستورد 90% من احتياجه. صنف سردا-1 وبحوث 1 مناسبان محلياً.',
    suitableRegions: ['ذمار', 'صنعاء', 'إب', 'تعز', 'حجة'],
  },
  {
    id: 'corn',
    nameAr: 'ذرة شامية',
    nameEn: 'Maize',
    scientificName: 'Zea mays',
    category: 'cereals',
    icon: '🌽',
    growingSeasonMonths: 3,
    plantingSeason: 'مارس - أبريل',
    temperatureMin: 18, temperatureMax: 35,
    rainfallMin: 400, rainfallMax: 800,
    altitudeMin: 0, altitudeMax: 2000,
    soilType: 'خصبة جيدة الصرف',
    soilPH: '5.5 - 7.5',
    saltTolerance: 'low',
    yieldPerHectare: 4.5,
    plantDensityPerHa: 53333,
    maturityDays: 90,
    waterNeedMm: 550,
    irrigationType: 'flood',
    seedCostPerHa: 4500000,
    fertilizerCostPerHa: 180000000,
    laborCostPerHa: 12000000,
    totalCostPerHa: 40000000,
    pricePerTon: 180000,
    revenuePerHa: 810000,
    profitPerHa: 770000,
    notes: 'محصول صيفي، يتحمل الحرارة. يستخدم علفاً وغذاءً. سريع النمو.',
    suitableRegions: ['الحديدة', 'تهامة', 'حضرموت', 'المكلا'],
  },
  {
    id: 'barley',
    nameAr: 'شعير',
    nameEn: 'Barley',
    scientificName: 'Hordeum vulgare',
    category: 'cereals',
    icon: '🌾',
    growingSeasonMonths: 4,
    plantingSeason: 'نوفمبر',
    temperatureMin: 5, temperatureMax: 22,
    rainfallMin: 200, rainfallMax: 500,
    altitudeMin: 800, altitudeMax: 3000,
    soilType: 'يتحمل الفقيرة والملحية',
    soilPH: '6.0 - 8.5',
    saltTolerance: 'high',
    yieldPerHectare: 2.5,
    plantDensityPerHa: 200,
    maturityDays: 110,
    waterNeedMm: 350,
    irrigationType: 'rainfed',
    seedCostPerHa: 6000000,
    fertilizerCostPerHa: 120000000,
    laborCostPerHa: 10000000,
    totalCostPerHa: 30000000,
    pricePerTon: 220000,
    revenuePerHa: 550000,
    profitPerHa: 520000,
    notes: 'يتحمل الجفاف والملوحة. علف أساسي للحيوانات. يزرع بعل في المرتفعات.',
    suitableRegions: ['صعدة', 'عمران', 'ذمار', 'بيضاء'],
  },
  {
    id: 'sorghum',
    nameAr: 'ذرة رفيعة (دخن)',
    nameEn: 'Sorghum',
    scientificName: 'Sorghum bicolor',
    category: 'cereals',
    icon: '🌾',
    growingSeasonMonths: 4,
    plantingSeason: 'يوليو - أغسطس',
    temperatureMin: 20, temperatureMax: 40,
    rainfallMin: 250, rainfallMax: 600,
    altitudeMin: 0, altitudeMax: 1500,
    soilType: 'يتحمل الجفاف والفقيرة',
    soilPH: '5.5 - 8.5',
    saltTolerance: 'high',
    yieldPerHectare: 3.0,
    plantDensityPerHa: 125000,
    maturityDays: 120,
    waterNeedMm: 300,
    irrigationType: 'rainfed',
    seedCostPerHa: 3000000,
    fertilizerCostPerHa: 80000000,
    laborCostPerHa: 8000000,
    totalCostPerHa: 25000000,
    pricePerTon: 150000,
    revenuePerHa: 450000,
    profitPerHa: 425000,
    notes: 'الأكثر تحملاً للجفاف. غذاء أساسي في المناطق الجافة. يستخدم علفاً وحبوباً.',
    suitableRegions: ['حضرموت', 'المهرة', 'شبوة', 'البيضاء'],
  },

  // === المحاصيل النقدية اليمنية ===
  {
    id: 'coffee-arabi',
    nameAr: 'بُن عربي يمني',
    nameEn: 'Yemeni Arabica Coffee',
    scientificName: 'Coffea arabica',
    category: 'cash',
    icon: '☕',
    growingSeasonMonths: 9,
    plantingSeason: 'موسم الأمطار (مارس-أبريل)',
    temperatureMin: 15, temperatureMax: 25,
    rainfallMin: 1200, rainfallMax: 2000,
    altitudeMin: 1000, altitudeMax: 2500,
    soilType: 'بركانية خصبة، جيدة الصرف',
    soilPH: '5.5 - 6.5',
    saltTolerance: 'low',
    yieldPerHectare: 0.8,
    plantDensityPerHa: 1333,
    maturityDays: 270,
    waterNeedMm: 1500,
    irrigationType: 'rainfed',
    seedCostPerHa: 15000000,
    fertilizerCostPerHa: 50000000,
    laborCostPerHa: 30000000,
    totalCostPerHa: 95000000,
    pricePerTon: 9000000, // $9/kg × 1000 - بُن فاخر
    revenuePerHa: 7200000,
    profitPerHa: 7100000,
    notes: 'البُن اليمني عالمي السمعة (موكا، حراز، بني مطر). سعر الكيلو $8-11 للمختص. صنف حرازي ودوعري. يبدأ الإنتاج السنة 3 ويستمر 30 سنة. صادرات اليمن 5500-8800 طن سنوياً.',
    suitableRegions: ['حراز', 'بني مطر', 'عنس', 'الحدا', 'يريم', 'جبل عفار'],
  },
  {
    id: 'qat',
    nameAr: 'قات',
    nameEn: 'Qat',
    scientificName: 'Catha edulis',
    category: 'cash',
    icon: '🌿',
    growingSeasonMonths: 12,
    plantingSeason: 'موسم الأمطار',
    temperatureMin: 15, temperatureMax: 30,
    rainfallMin: 500, rainfallMax: 1500,
    altitudeMin: 1000, altitudeMax: 2500,
    soilType: 'عميقة، جيدة الصرف',
    soilPH: '6.0 - 8.0',
    saltTolerance: 'medium',
    yieldPerHectare: 2.0,
    plantDensityPerHa: 625,
    maturityDays: 1095, // 3 سنوات للنضج
    waterNeedMm: 1000,
    irrigationType: 'drip',
    seedCostPerHa: 25000000,
    fertilizerCostPerHa: 80000000,
    laborCostPerHa: 60000000,
    totalCostPerHa: 200000000,
    pricePerTon: 12000000, // 12,000 ريال للكيلو
    revenuePerHa: 24000000,
    profitPerHa: 23800000,
    notes: 'محصول نقدي رئيسي في اليمن. استهلاك يومي محلي. يستهلك 30% من المياه الجوفية. جدل اقتصادي/صحي. أعلى ربحية للمزارع الصغيرة.',
    suitableRegions: ['صنعاء', 'ذمار', 'إب', 'تعز', 'حجة'],
  },
  {
    id: 'honey',
    nameAr: 'عسل سدر يمني',
    nameEn: 'Yemeni Sidr Honey',
    scientificName: 'Ziziphus spina-christi (شجر السدر)',
    category: 'cash',
    icon: '🍯',
    growingSeasonMonths: 6,
    plantingSeason: 'موسم السدر (أكتوبر-مارس)',
    temperatureMin: 20, temperatureMax: 40,
    rainfallMin: 100, rainfallMax: 400,
    altitudeMin: 0, altitudeMax: 1500,
    soilType: 'جافة، جيدة الصرف',
    soilPH: '7.0 - 8.5',
    saltTolerance: 'high',
    yieldPerHectare: 0.15, // 150 كغ عسل/هكتار مرعى
    plantDensityPerHa: 200, // أشجار سدر/هكتار
    maturityDays: 180,
    waterNeedMm: 150,
    irrigationType: 'rainfed',
    seedCostPerHa: 5000000,
    fertilizerCostPerHa: 10000000,
    laborCostPerHa: 20000000,
    totalCostPerHa: 50000000,
    pricePerTon: 50000000, // $200/kg للعسل الفاخر
    revenuePerHa: 7500000,
    profitPerHa: 7450000,
    notes: 'عسل سدر حضرموت ووادي دوعن عالمي الشهرة. سعر الكيلو $100-200 للأجود. يحتاج مناحل + أشجار سدر. مشروع متكامل (نحل + زراعة).',
    suitableRegions: ['حضرموت - وادي دوعن', 'حجور', 'تهامة', 'صعدة'],
  },

  // === الفواكه ===
  {
    id: 'mango',
    nameAr: 'مانجو',
    nameEn: 'Mango',
    scientificName: 'Mangifera indica',
    category: 'fruits',
    icon: '🥭',
    growingSeasonMonths: 12,
    plantingSeason: 'فبراير - مارس',
    temperatureMin: 20, temperatureMax: 38,
    rainfallMin: 500, rainfallMax: 1500,
    altitudeMin: 0, altitudeMax: 800,
    soilType: 'عميقة، جيدة الصرف',
    soilPH: '5.5 - 7.5',
    saltTolerance: 'medium',
    yieldPerHectare: 15,
    plantDensityPerHa: 200,
    maturityDays: 1095, // 3 سنوات
    waterNeedMm: 1200,
    irrigationType: 'drip',
    seedCostPerHa: 10000000,
    fertilizerCostPerHa: 60000000,
    laborCostPerHa: 30000000,
    totalCostPerHa: 120000000,
    pricePerTon: 400000,
    revenuePerHa: 6000000,
    profitPerHa: 5880000,
    notes: 'مانجو الحديدة شهيرة. أصناف: الجلفور، البامبا، السكري. يبدأ الإنتاج سنة 3-4 ويستمر 30+ سنة. صادرات للخليج.',
    suitableRegions: ['الحديدة', 'تهامة', 'حضرموت', 'المكلا'],
  },
  {
    id: 'banana',
    nameAr: 'موز',
    nameEn: 'Banana',
    scientificName: 'Musa spp.',
    category: 'fruits',
    icon: '🍌',
    growingSeasonMonths: 12,
    plantingSeason: 'طوال السنة',
    temperatureMin: 22, temperatureMax: 35,
    rainfallMin: 1500, rainfallMax: 2500,
    altitudeMin: 0, altitudeMax: 500,
    soilType: 'خصبة، احتباس مائي',
    soilPH: '5.5 - 7.0',
    saltTolerance: 'low',
    yieldPerHectare: 30,
    plantDensityPerHa: 1600,
    maturityDays: 365,
    waterNeedMm: 2000,
    irrigationType: 'flood',
    seedCostPerHa: 8000000,
    fertilizerCostPerHa: 100000000,
    laborCostPerHa: 40000000,
    totalCostPerHa: 150000000,
    pricePerTon: 250000,
    revenuePerHa: 7500000,
    profitPerHa: 7350000,
    notes: 'موز تهامة مشهور. يحتاج مياه وفيرة. سريع الإنتاج (سنة واحدة). أصناف: بارادي ناري، غروس ميشيل.',
    suitableRegions: ['تهامة', 'الحديدة', 'حضرموت'],
  },
  {
    id: 'palm',
    nameAr: 'نخيل تمور',
    nameEn: 'Date Palm',
    scientificName: 'Phoenix dactylifera',
    category: 'fruits',
    icon: '🌴',
    growingSeasonMonths: 12,
    plantingSeason: 'فبراير - مارس',
    temperatureMin: 25, temperatureMax: 45,
    rainfallMin: 50, rainfallMax: 300,
    altitudeMin: 0, altitudeMax: 1000,
    soilType: 'رملية، جيدة الصرف',
    soilPH: '7.0 - 9.0',
    saltTolerance: 'high',
    yieldPerHectare: 8,
    plantDensityPerHa: 100,
    maturityDays: 1825, // 5 سنوات
    waterNeedMm: 800,
    irrigationType: 'drip',
    seedCostPerHa: 20000000,
    fertilizerCostPerHa: 40000000,
    laborCostPerHa: 25000000,
    totalCostPerHa: 100000000,
    pricePerTon: 1500000, // أصناف فاخرة
    revenuePerHa: 12000000,
    profitPerHa: 11900000,
    notes: 'نخيل حضرموت والمهرة عالي الجودة. أصناف: مجدول، برحي، خضراوي. يتحمل الملوحة والجفاف. يبدأ الإنتاج سنة 5 ويستمر 50+ سنة.',
    suitableRegions: ['حضرموت', 'المهرة', 'وادي حضرموت', 'شبوة'],
  },
  {
    id: 'pomegranate',
    nameAr: 'رمان',
    nameEn: 'Pomegranate',
    scientificName: 'Punica granatum',
    category: 'fruits',
    icon: '🍎',
    growingSeasonMonths: 8,
    plantingSeason: 'فبراير - مارس',
    temperatureMin: 15, temperatureMax: 35,
    rainfallMin: 300, rainfallMax: 800,
    altitudeMin: 200, altitudeMax: 1500,
    soilType: 'طينية كلسية',
    soilPH: '6.0 - 7.5',
    saltTolerance: 'medium',
    yieldPerHectare: 12,
    plantDensityPerHa: 400,
    maturityDays: 1095,
    waterNeedMm: 900,
    irrigationType: 'drip',
    seedCostPerHa: 12000000,
    fertilizerCostPerHa: 50000000,
    laborCostPerHa: 30000000,
    totalCostPerHa: 100000000,
    pricePerTon: 800000,
    revenuePerHa: 9600000,
    profitPerHa: 9500000,
    notes: 'متوسط الاحتياج المائي. يتحمل الجفاف. ثمار عالية القيمة الغذائية. صادرات للخليج.',
    suitableRegions: ['صنعاء', 'ذمار', 'إب', 'تعز'],
  },
  {
    id: 'grape',
    nameAr: 'عنب',
    nameEn: 'Grape',
    scientificName: 'Vitis vinifera',
    category: 'fruits',
    icon: '🍇',
    growingSeasonMonths: 8,
    plantingSeason: 'فبراير',
    temperatureMin: 15, temperatureMax: 35,
    rainfallMin: 400, rainfallMax: 900,
    altitudeMin: 500, altitudeMax: 1800,
    soilType: 'رملية طينية، جيدة الصرف',
    soilPH: '6.0 - 7.5',
    saltTolerance: 'medium',
    yieldPerHectare: 18,
    plantDensityPerHa: 666,
    maturityDays: 730,
    waterNeedMm: 700,
    irrigationType: 'drip',
    seedCostPerHa: 8000000,
    fertilizerCostPerHa: 45000000,
    laborCostPerHa: 25000000,
    totalCostPerHa: 85000000,
    pricePerTon: 500000,
    revenuePerHa: 9000000,
    profitPerHa: 8915000,
    notes: 'عنب صنعاء وذمار مشهور. يتحمل الجفاف النسبي. أصناف: بيزاني، رازقي. للأكل والزبيب.',
    suitableRegions: ['صنعاء', 'ذمار', 'عمران', 'صعدة'],
  },

  // === الخضروات ===
  {
    id: 'tomato',
    nameAr: 'طماطم',
    nameEn: 'Tomato',
    scientificName: 'Solanum lycopersicum',
    category: 'vegetables',
    icon: '🍅',
    growingSeasonMonths: 4,
    plantingSeason: 'سبتمبر - فبراير',
    temperatureMin: 18, temperatureMax: 30,
    rainfallMin: 600, rainfallMax: 1000,
    altitudeMin: 0, altitudeMax: 2000,
    soilType: 'خصبة، جيدة الصرف',
    soilPH: '6.0 - 6.8',
    saltTolerance: 'medium',
    yieldPerHectare: 35,
    plantDensityPerHa: 20000,
    maturityDays: 90,
    waterNeedMm: 600,
    irrigationType: 'drip',
    seedCostPerHa: 5000000,
    fertilizerCostPerHa: 80000000,
    laborCostPerHa: 30000000,
    totalCostPerHa: 120000000,
    pricePerTon: 300000,
    revenuePerHa: 10500000,
    profitPerHa: 10300000,
    notes: 'محصول سريع العائد. طلب محلي عالٍ. يزرع في الصوب والحقول. دورة 3 أشهر فقط.',
    suitableRegions: ['صنعاء', 'ذمار', 'إب', 'الحديدة'],
  },
  {
    id: 'watermelon',
    nameAr: 'بطيخ',
    nameEn: 'Watermelon',
    scientificName: 'Citrullus lanatus',
    category: 'vegetables',
    icon: '🍉',
    growingSeasonMonths: 3,
    plantingSeason: 'مارس - أبريل',
    temperatureMin: 22, temperatureMax: 35,
    rainfallMin: 400, rainfallMax: 800,
    altitudeMin: 0, altitudeMax: 1000,
    soilType: 'رملية، جيدة الصرف',
    soilPH: '6.0 - 7.5',
    saltTolerance: 'medium',
    yieldPerHectare: 25,
    plantDensityPerHa: 5000,
    maturityDays: 85,
    waterNeedMm: 500,
    irrigationType: 'drip',
    seedCostPerHa: 3000000,
    fertilizerCostPerHa: 50000000,
    laborCostPerHa: 15000000,
    totalCostPerHa: 70000000,
    pricePerTon: 200000,
    revenuePerHa: 5000000,
    profitPerHa: 4930000,
    notes: 'صيفي، يحب الحرارة. صنف (كويتي 100، أبو فروة). سريع الإنتاج (3 أشهر).',
    suitableRegions: ['تهامة', 'الحديدة', 'حضرموت', 'حجة'],
  },
  {
    id: 'onion',
    nameAr: 'بصل',
    nameEn: 'Onion',
    scientificName: 'Allium cepa',
    category: 'vegetables',
    icon: '🧅',
    growingSeasonMonths: 5,
    plantingSeason: 'أكتوبر - نوفمبر',
    temperatureMin: 13, temperatureMax: 25,
    rainfallMin: 350, rainfallMax: 700,
    altitudeMin: 0, altitudeMax: 2000,
    soilType: 'خصبة، جيدة الصرف',
    soilPH: '6.0 - 7.0',
    saltTolerance: 'medium',
    yieldPerHectare: 20,
    plantDensityPerHa: 250000,
    maturityDays: 150,
    waterNeedMm: 450,
    irrigationType: 'flood',
    seedCostPerHa: 6000000,
    fertilizerCostPerHa: 70000000,
    laborCostPerHa: 25000000,
    totalCostPerHa: 110000000,
    pricePerTon: 350000,
    revenuePerHa: 7000000,
    profitPerHa: 6890000,
    notes: 'محصول استراتيجي. بصل صنعاء وذمار مشهور. يتخزن لفترات طويلة. صادرات للخليج.',
    suitableRegions: ['صنعاء', 'ذمار', 'عمران', 'صعدة'],
  },

  // === الأعلاف والصناعية ===
  {
    id: 'alfalfa',
    nameAr: 'برسيم حجازي',
    nameEn: 'Alfalfa',
    scientificName: 'Medicago sativa',
    category: 'forage',
    icon: '🌱',
    growingSeasonMonths: 12,
    plantingSeason: 'أكتوبر - نوفمبر',
    temperatureMin: 15, temperatureMax: 35,
    rainfallMin: 300, rainfallMax: 800,
    altitudeMin: 0, altitudeMax: 2000,
    soilType: 'خصبة، جيدة الصرف',
    soilPH: '6.5 - 7.5',
    saltTolerance: 'medium',
    yieldPerHectare: 60, // طن علة اخضر
    plantDensityPerHa: 20000000, // بذور
    maturityDays: 60, // أول حشة
    waterNeedMm: 1200,
    irrigationType: 'flood',
    seedCostPerHa: 4000000,
    fertilizerCostPerHa: 30000000,
    laborCostPerHa: 20000000,
    totalCostPerHa: 60000000,
    pricePerTon: 100000,
    revenuePerHa: 6000000,
    profitPerHa: 5940000,
    notes: 'محصول علفي دائم (5-7 سنوات). 6-8 حشات سنوياً. علف أساسي للأبقار والأغنام. عالي القيمة الغذائية.',
    suitableRegions: ['صنعاء', 'ذمار', 'إب', 'الحديدة'],
  },
  {
    id: 'sesame',
    nameAr: 'سمسم',
    nameEn: 'Sesame',
    scientificName: 'Sesamum indicum',
    category: 'industrial',
    icon: '🌰',
    growingSeasonMonths: 4,
    plantingSeason: 'يوليو - أغسطس',
    temperatureMin: 22, temperatureMax: 35,
    rainfallMin: 300, rainfallMax: 700,
    altitudeMin: 0, altitudeMax: 1200,
    soilType: 'خصبة، جيدة الصرف',
    soilPH: '5.5 - 8.0',
    saltTolerance: 'medium',
    yieldPerHectare: 1.2,
    plantDensityPerHa: 250000,
    maturityDays: 120,
    waterNeedMm: 400,
    irrigationType: 'rainfed',
    seedCostPerHa: 3000000,
    fertilizerCostPerHa: 40000000,
    laborCostPerHa: 15000000,
    totalCostPerHa: 60000000,
    pricePerTon: 800000,
    revenuePerHa: 960000,
    profitPerHa: 900000,
    notes: 'يتحمل الجفاف. زيت عالي الجودة. صنف أحمر وأبيض. صادرات للخليج. محصول صيفي.',
    suitableRegions: ['تهامة', 'الحديدة', 'حضرموت', 'شبوة'],
  },

  // === محاصيل إضافية ===
  {
    id: 'cotton',
    nameAr: 'قطن',
    nameEn: 'Cotton',
    scientificName: 'Gossypium hirsutum',
    category: 'industrial',
    icon: '☁️',
    growingSeasonMonths: 6,
    plantingSeason: 'مارس - أبريل',
    temperatureMin: 20, temperatureMax: 38,
    rainfallMin: 500, rainfallMax: 1000,
    altitudeMin: 0, altitudeMax: 1000,
    soilType: 'طينية رملية، جيدة الصرف',
    soilPH: '5.5 - 8.5',
    saltTolerance: 'medium',
    yieldPerHectare: 2.5,
    plantDensityPerHa: 100000,
    maturityDays: 180,
    waterNeedMm: 700,
    irrigationType: 'flood',
    seedCostPerHa: 4000000,
    fertilizerCostPerHa: 90000000,
    laborCostPerHa: 35000000,
    totalCostPerHa: 140000000,
    pricePerTon: 1200000,
    revenuePerHa: 3000000,
    profitPerHa: 2860000,
    notes: 'محصول استراتيجي للنسيج. يتطلب عمالة كثيفة. صادرات للهند والصين. يمكن تطوير صناعة غزل ونسيج محلية.',
    suitableRegions: ['تهامة', 'الحديدة', 'حضرموت', 'وادي حضرموت'],
  },
  {
    id: 'cactus-fruit',
    nameAr: 'صبار التين الهندي',
    nameEn: 'Prickly Pear',
    scientificName: 'Opuntia ficus-indica',
    category: 'fruits',
    icon: '🌵',
    growingSeasonMonths: 12,
    plantingSeason: 'مارس - أبريل',
    temperatureMin: 18, temperatureMax: 40,
    rainfallMin: 100, rainfallMax: 400,
    altitudeMin: 0, altitudeMax: 1800,
    soilType: 'جافة، رملية، جيدة الصرف',
    soilPH: '6.0 - 8.5',
    saltTolerance: 'high',
    yieldPerHectare: 12,
    plantDensityPerHa: 800,
    maturityDays: 730,
    waterNeedMm: 200,
    irrigationType: 'rainfed',
    seedCostPerHa: 6000000,
    fertilizerCostPerHa: 15000000,
    laborCostPerHa: 20000000,
    totalCostPerHa: 50000000,
    pricePerTon: 600000,
    revenuePerHa: 7200000,
    profitPerHa: 7150000,
    notes: 'يتحمل أشد الجفاف والملوحة. ينتج فاكهة + علف من الشرائح. يحتاج القليل من المياه. مثالي للأراضي الصحراوية. يُستخرج منه زيت البذور الثمين.',
    suitableRegions: ['حضرموت', 'المهرة', 'شبوة', 'وادي حضرموت'],
  },
  {
    id: 'thyme',
    nameAr: 'زعتر',
    nameEn: 'Thyme',
    scientificName: 'Thymus vulgaris',
    category: 'cash',
    icon: '🌿',
    growingSeasonMonths: 12,
    plantingSeason: 'أكتوبر - نوفمبر',
    temperatureMin: 10, temperatureMax: 30,
    rainfallMin: 300, rainfallMax: 700,
    altitudeMin: 800, altitudeMax: 2500,
    soilType: 'كلسية، جيدة الصرف',
    soilPH: '6.0 - 8.0',
    saltTolerance: 'medium',
    yieldPerHectare: 3.0,
    plantDensityPerHa: 33333,
    maturityDays: 365,
    waterNeedMm: 350,
    irrigationType: 'drip',
    seedCostPerHa: 5000000,
    fertilizerCostPerHa: 20000000,
    laborCostPerHa: 15000000,
    totalCostPerHa: 45000000,
    pricePerTon: 2500000,
    revenuePerHa: 7500000,
    profitPerHa: 7455000,
    notes: 'نبات طبي وعطري. الزعتر اليمني مشهور. يُستخدم طازجاً ومجففاً وزيتاً عطرياً. تصدير للخليج وأوروبا. محصول دائم (5-7 سنوات).',
    suitableRegions: ['صنعاء', 'ذمار', 'إب', 'تعز', 'عمران'],
  },
  {
    id: 'tobacco',
    nameAr: 'تبغ',
    nameEn: 'Tobacco',
    scientificName: 'Nicotiana tabacum',
    category: 'industrial',
    icon: '🚬',
    growingSeasonMonths: 4,
    plantingSeason: 'فبراير - مارس',
    temperatureMin: 20, temperatureMax: 32,
    rainfallMin: 400, rainfallMax: 800,
    altitudeMin: 0, altitudeMax: 1500,
    soilType: 'رملية، جيدة الصرف',
    soilPH: '5.5 - 6.5',
    saltTolerance: 'low',
    yieldPerHectare: 2.0,
    plantDensityPerHa: 16000,
    maturityDays: 120,
    waterNeedMm: 500,
    irrigationType: 'drip',
    seedCostPerHa: 4000000,
    fertilizerCostPerHa: 70000000,
    laborCostPerHa: 40000000,
    totalCostPerHa: 120000000,
    pricePerTon: 2500000,
    revenuePerHa: 5000000,
    profitPerHa: 4880000,
    notes: 'محصول نقدية عالية. عمالة مكثفة. معالجة وتجفيف مطلوبان. صادرات + استخدام محلي. جدل صحي لكن الطلب مرتفع.',
    suitableRegions: ['تهامة', 'الحديدة', 'حجة', 'صعدة'],
  },
  {
    id: 'peanut',
    nameAr: 'فول سوداني',
    nameEn: 'Peanut',
    scientificName: 'Arachis hypogaea',
    category: 'cash',
    icon: '🥜',
    growingSeasonMonths: 4,
    plantingSeason: 'أبريل - مايو',
    temperatureMin: 22, temperatureMax: 35,
    rainfallMin: 400, rainfallMax: 800,
    altitudeMin: 0, altitudeMax: 1200,
    soilType: 'رملية، جيدة الصرف',
    soilPH: '5.5 - 7.0',
    saltTolerance: 'low',
    yieldPerHectare: 2.5,
    plantDensityPerHa: 100000,
    maturityDays: 120,
    waterNeedMm: 450,
    irrigationType: 'drip',
    seedCostPerHa: 6000000,
    fertilizerCostPerHa: 50000000,
    laborCostPerHa: 25000000,
    totalCostPerHa: 85000000,
    pricePerTon: 1500000,
    revenuePerHa: 3750000,
    profitPerHa: 3665000,
    notes: 'محصول صيفي عالي القيمة. يثبت النيتروجين في التربة. يُباع نيئاً ومحمصاً وزيتاً. صادرات للسعودية. مصدر جيد للبروتين النباتي.',
    suitableRegions: ['تهامة', 'الحديدة', 'حضرموت', 'شبوة'],
  },
  {
    id: 'date-palm',
    nameAr: 'دلاع (بطيخ أحمر صيفي)',
    nameEn: 'Watermelon (Summer)',
    scientificName: 'Citrullus lanatus',
    category: 'vegetables',
    icon: '🍉',
    growingSeasonMonths: 3,
    plantingSeason: 'مايو - يونيو',
    temperatureMin: 25, temperatureMax: 40,
    rainfallMin: 200, rainfallMax: 500,
    altitudeMin: 0, altitudeMax: 800,
    soilType: 'رملية، جيدة الصرف',
    soilPH: '6.0 - 7.5',
    saltTolerance: 'medium',
    yieldPerHectare: 30,
    plantDensityPerHa: 4000,
    maturityDays: 80,
    waterNeedMm: 400,
    irrigationType: 'drip',
    seedCostPerHa: 3500000,
    fertilizerCostPerHa: 55000000,
    laborCostPerHa: 18000000,
    totalCostPerHa: 80000000,
    pricePerTon: 250000,
    revenuePerHa: 7500000,
    profitPerHa: 7420000,
    notes: 'صيفي، يحب الحرارة الشديدة. أعلى إنتاجية من البطيخ العادي. سريع العائد. الذروة في أغسطس-سبتمبر عندما الطلب عالٍ.',
    suitableRegions: ['تهامة', 'الحديدة', 'حضرموت', 'وادي حضرموت'],
  },

  // === محاصيل إضافية ===
  {
    id: 'olive',
    nameAr: 'زيتون',
    nameEn: 'Olive',
    scientificName: 'Olea europaea',
    category: 'fruits',
    icon: '🫒',
    growingSeasonMonths: 12,
    plantingSeason: 'أكتوبر - نوفمبر',
    temperatureMin: 5, temperatureMax: 35,
    rainfallMin: 300, rainfallMax: 800,
    altitudeMin: 300, altitudeMax: 1800,
    soilType: 'كلسية، جيدة الصرف',
    soilPH: '6.0 - 8.5',
    saltTolerance: 'high',
    yieldPerHectare: 4.0,
    plantDensityPerHa: 300,
    maturityDays: 1460,
    waterNeedMm: 500,
    irrigationType: 'drip',
    seedCostPerHa: 12000000,
    fertilizerCostPerHa: 30000000,
    laborCostPerHa: 25000000,
    totalCostPerHa: 80000000,
    pricePerTon: 2500000,
    revenuePerHa: 10000000,
    profitPerHa: 9920000,
    notes: 'شجر دائم (50+ سنة). يتحمل الجفاف والملوحة. زيت زيتون بكر ممتاز. إنتاج من سنة 4. يناسب مرتفعات اليمن.',
    suitableRegions: ['ذمار', 'صنعاء', 'إب', 'تعز', 'عمران'],
  },
  {
    id: 'potato',
    nameAr: 'بطاطس',
    nameEn: 'Potato',
    scientificName: 'Solanum tuberosum',
    category: 'vegetables',
    icon: '🥔',
    growingSeasonMonths: 3,
    plantingSeason: 'سبتمبر - أكتوبر',
    temperatureMin: 10, temperatureMax: 25,
    rainfallMin: 400, rainfallMax: 700,
    altitudeMin: 500, altitudeMax: 2500,
    soilType: 'خصبة، جيدة الصرف',
    soilPH: '5.0 - 6.5',
    saltTolerance: 'low',
    yieldPerHectare: 25,
    plantDensityPerHa: 40000,
    maturityDays: 100,
    waterNeedMm: 500,
    irrigationType: 'drip',
    seedCostPerHa: 8000000,
    fertilizerCostPerHa: 70000000,
    laborCostPerHa: 25000000,
    totalCostPerHa: 110000000,
    pricePerTon: 400000,
    revenuePerHa: 10000000,
    profitPerHa: 9890000,
    notes: 'محصول استراتيجي غذائي. سريع النمو (100 يوم). إنتاجية عالية. ينمو في المرتفعات. تخزين طويل.',
    suitableRegions: ['ذمار', 'صنعاء', 'صعدة', 'عمران', 'بيضاء'],
  },
  {
    id: 'garlic',
    nameAr: 'ثوم',
    nameEn: 'Garlic',
    scientificName: 'Allium sativum',
    category: 'vegetables',
    icon: '🧄',
    growingSeasonMonths: 5,
    plantingSeason: 'أكتوبر - نوفمبر',
    temperatureMin: 12, temperatureMax: 25,
    rainfallMin: 300, rainfallMax: 600,
    altitudeMin: 500, altitudeMax: 2000,
    soilType: 'خصبة، جيدة الصرف',
    soilPH: '6.0 - 7.0',
    saltTolerance: 'medium',
    yieldPerHectare: 8,
    plantDensityPerHa: 250000,
    maturityDays: 150,
    waterNeedMm: 400,
    irrigationType: 'drip',
    seedCostPerHa: 10000000,
    fertilizerCostPerHa: 50000000,
    laborCostPerHa: 30000000,
    totalCostPerHa: 95000000,
    pricePerTon: 1200000,
    revenuePerHa: 9600000,
    profitPerHa: 9505000,
    notes: 'محصول عالي القيمة. طلب محلي وعالمي مستمر. مضاد حيوي طبيعي. تخزين طويل. يناسب المرتفعات.',
    suitableRegions: ['صنعاء', 'ذمار', 'صعدة', 'عمران'],
  },
  {
    id: 'strawberry',
    nameAr: 'فراولة',
    nameEn: 'Strawberry',
    scientificName: 'Fragaria × ananassa',
    category: 'fruits',
    icon: '🍓',
    growingSeasonMonths: 6,
    plantingSeason: 'أكتوبر - نوفمبر',
    temperatureMin: 10, temperatureMax: 25,
    rainfallMin: 500, rainfallMax: 1000,
    altitudeMin: 500, altitudeMax: 2000,
    soilType: 'خصبة، جيدة الصرف',
    soilPH: '5.5 - 6.5',
    saltTolerance: 'low',
    yieldPerHectare: 20,
    plantDensityPerHa: 60000,
    maturityDays: 90,
    waterNeedMm: 600,
    irrigationType: 'drip',
    seedCostPerHa: 15000000,
    fertilizerCostPerHa: 60000000,
    laborCostPerHa: 40000000,
    totalCostPerHa: 120000000,
    pricePerTon: 1500000,
    revenuePerHa: 30000000,
    profitPerHa: 29880000,
    notes: 'الأعلى ربحية للمساحات الصغيرة! محصول فاخر للتصدير. يزرع في الصوب. إنتاج سريع 90 يوم. يناسب المرتفعات المعتدلة.',
    suitableRegions: ['إب', 'تعز', 'ذمار', 'صنعاء'],
  },
  {
    id: 'lavender',
    nameAr: 'خزامى (لافندر)',
    nameEn: 'Lavender',
    scientificName: 'Lavandula angustifolia',
    category: 'cash',
    icon: '💜',
    growingSeasonMonths: 12,
    plantingSeason: 'أكتوبر - نوفمبر',
    temperatureMin: 5, temperatureMax: 30,
    rainfallMin: 200, rainfallMax: 600,
    altitudeMin: 800, altitudeMax: 2500,
    soilType: 'كلسية، جيدة الصرف',
    soilPH: '6.5 - 8.0',
    saltTolerance: 'medium',
    yieldPerHectare: 1.5,
    plantDensityPerHa: 10000,
    maturityDays: 365,
    waterNeedMm: 300,
    irrigationType: 'drip',
    seedCostPerHa: 8000000,
    fertilizerCostPerHa: 15000000,
    laborCostPerHa: 15000000,
    totalCostPerHa: 45000000,
    pricePerTon: 8000000,
    revenuePerHa: 12000000,
    profitPerHa: 11950000,
    notes: 'نبات عطري طبي. زيت اللافندر ثمين ($200/لتر). محصول دائم 8-10 سنوات. تصدير لأوروبا. يناسب المرتفعات.',
    suitableRegions: ['صنعاء', 'ذمار', 'إب', 'عمران', 'صعدة'],
  },
  {
    id: 'sunflower',
    nameAr: 'عباد الشمس',
    nameEn: 'Sunflower',
    scientificName: 'Helianthus annuus',
    category: 'industrial',
    icon: '🌻',
    growingSeasonMonths: 4,
    plantingSeason: 'مارس - أبريل',
    temperatureMin: 18, temperatureMax: 35,
    rainfallMin: 300, rainfallMax: 700,
    altitudeMin: 0, altitudeMax: 1500,
    soilType: 'خصبة، جيدة الصرف',
    soilPH: '6.0 - 7.5',
    saltTolerance: 'medium',
    yieldPerHectare: 2.0,
    plantDensityPerHa: 55000,
    maturityDays: 110,
    waterNeedMm: 450,
    irrigationType: 'rainfed',
    seedCostPerHa: 4000000,
    fertilizerCostPerHa: 45000000,
    laborCostPerHa: 15000000,
    totalCostPerHa: 70000000,
    pricePerTon: 900000,
    revenuePerHa: 1800000,
    profitPerHa: 1730000,
    notes: 'زيت عالي الجودة + بذور للأكل + علف. سريع النمو (110 يوم). يتحمل الجفاف. تجميلي + صناعي.',
    suitableRegions: ['تهامة', 'الحديدة', 'حضرموت', 'ذمار'],
  },

  // === محاصيل إضافية (دورة 4) ===
  {
    id: 'cucumber',
    nameAr: 'خيار',
    nameEn: 'Cucumber',
    scientificName: 'Cucumis sativus',
    category: 'vegetables',
    icon: '🥒',
    growingSeasonMonths: 3,
    plantingSeason: 'مارس - أغسطس',
    temperatureMin: 18, temperatureMax: 32,
    rainfallMin: 500, rainfallMax: 900,
    altitudeMin: 0, altitudeMax: 1500,
    soilType: 'خصبة، جيدة الصرف',
    soilPH: '6.0 - 7.0',
    saltTolerance: 'medium',
    yieldPerHectare: 30,
    plantDensityPerHa: 25000,
    maturityDays: 60,
    waterNeedMm: 550,
    irrigationType: 'drip',
    seedCostPerHa: 3000000,
    fertilizerCostPerHa: 50000000,
    laborCostPerHa: 20000000,
    totalCostPerHa: 80000000,
    pricePerTon: 300000,
    revenuePerHa: 9000000,
    profitPerHa: 8920000,
    notes: 'سريع النمو (60 يوم). إنتاجية عالية. يزرع في الصوب والحقول. طلب محلي مستمر طوال السنة.',
    suitableRegions: ['الحديدة', 'تهامة', 'إب', 'ذمار'],
  },
  {
    id: 'eggplant',
    nameAr: 'باذنجان',
    nameEn: 'Eggplant',
    scientificName: 'Solanum melongena',
    category: 'vegetables',
    icon: '🍆',
    growingSeasonMonths: 4,
    plantingSeason: 'فبراير - مارس',
    temperatureMin: 20, temperatureMax: 35,
    rainfallMin: 500, rainfallMax: 900,
    altitudeMin: 0, altitudeMax: 1500,
    soilType: 'خصبة، جيدة الصرف',
    soilPH: '6.0 - 7.0',
    saltTolerance: 'medium',
    yieldPerHectare: 25,
    plantDensityPerHa: 15000,
    maturityDays: 90,
    waterNeedMm: 600,
    irrigationType: 'drip',
    seedCostPerHa: 3500000,
    fertilizerCostPerHa: 55000000,
    laborCostPerHa: 22000000,
    totalCostPerHa: 85000000,
    pricePerTon: 350000,
    revenuePerHa: 8750000,
    profitPerHa: 8665000,
    notes: 'محصول صيفي. يتحمل الحرارة. طلب محلي. مدة إنتاج طويلة (4 أشهر حصاد مستمر).',
    suitableRegions: ['الحديدة', 'تهامة', 'حضرموت', 'إب'],
  },
  {
    id: 'mint',
    nameAr: 'نعناع',
    nameEn: 'Mint',
    scientificName: 'Mentha spp.',
    category: 'cash',
    icon: '🌿',
    growingSeasonMonths: 12,
    plantingSeason: 'طوال السنة',
    temperatureMin: 12, temperatureMax: 30,
    rainfallMin: 400, rainfallMax: 800,
    altitudeMin: 500, altitudeMax: 2200,
    soilType: 'خصبة، احتباس مائي',
    soilPH: '6.0 - 7.5',
    saltTolerance: 'low',
    yieldPerHectare: 15,
    plantDensityPerHa: 100000,
    maturityDays: 60,
    waterNeedMm: 700,
    irrigationType: 'drip',
    seedCostPerHa: 5000000,
    fertilizerCostPerHa: 30000000,
    laborCostPerHa: 15000000,
    totalCostPerHa: 55000000,
    pricePerTon: 1500000,
    revenuePerHa: 22500000,
    profitPerHa: 22450000,
    notes: 'محصول دائم (3-5 سنوات). 4-6 حشات سنوياً. طلب محلي ضخم. يُباع طازج ومجفف. زيت عطري ثمين.',
    suitableRegions: ['صنعاء', 'ذمار', 'إب', 'تعز', 'عمران'],
  },
  {
    id: 'chili',
    nameAr: 'فلفل حار',
    nameEn: 'Chili Pepper',
    scientificName: 'Capsicum annuum',
    category: 'vegetables',
    icon: '🌶️',
    growingSeasonMonths: 5,
    plantingSeason: 'فبراير - مارس',
    temperatureMin: 18, temperatureMax: 35,
    rainfallMin: 400, rainfallMax: 800,
    altitudeMin: 0, altitudeMax: 1800,
    soilType: 'خصبة، جيدة الصرف',
    soilPH: '6.0 - 7.0',
    saltTolerance: 'medium',
    yieldPerHectare: 10,
    plantDensityPerHa: 30000,
    maturityDays: 120,
    waterNeedMm: 500,
    irrigationType: 'drip',
    seedCostPerHa: 4000000,
    fertilizerCostPerHa: 50000000,
    laborCostPerHa: 25000000,
    totalCostPerHa: 85000000,
    pricePerTon: 1200000,
    revenuePerHa: 12000000,
    profitPerHa: 11915000,
    notes: 'محصول عالي القيمة. طلب محلي + تصدير. يستخدم طازج ومجفف ومطحون. الفلفل اليمني (صنعاء) مشهور.',
    suitableRegions: ['صنعاء', 'ذمار', 'إب', 'تعز', 'الحديدة'],
  },
];

export const CROP_CATEGORIES = {
  cereals: { ar: 'حبوب', en: 'Cereals', color: 'bg-amber-500/10 text-amber-700' },
  cash: { ar: 'نقدية', en: 'Cash Crops', color: 'bg-purple-500/10 text-purple-700' },
  fruits: { ar: 'فواكه', en: 'Fruits', color: 'bg-red-500/10 text-red-700' },
  vegetables: { ar: 'خضروات', en: 'Vegetables', color: 'bg-green-500/10 text-green-700' },
  forage: { ar: 'أعلاف', en: 'Forage', color: 'bg-blue-500/10 text-blue-700' },
  industrial: { ar: 'صناعية', en: 'Industrial', color: 'bg-cyan-500/10 text-cyan-700' },
};

export function getCropById(id: string): CropInfo | undefined {
  return CROPS_LIBRARY.find((c) => c.id === id);
}

// فلترة المحاصيل حسب المنطقة/المناخ
export function recommendCrops(params: {
  altitude?: number;
  temperature?: number;
  rainfall?: number;
  soilType?: string;
  irrigationAvailable?: boolean;
}): CropInfo[] {
  return CROPS_LIBRARY.filter((c) => {
    if (params.altitude && (params.altitude < c.altitudeMin || params.altitude > c.altitudeMax)) return false;
    if (params.temperature && (params.temperature < c.temperatureMin || params.temperature > c.temperatureMax)) return false;
    if (params.rainfall && params.rainfall > 0 && c.irrigationType === 'rainfed' && params.rainfall < c.rainfallMin) return false;
    return true;
  });
}
