// مكتبة مصانع الصناعات التحويلية - بيانات واقعية
// المصادر: Mashroo3k، Pre-Feasibility Studies، FAO

export interface FactoryInfo {
  id: string;
  nameAr: string;
  nameEn: string;
  category: 'food' | 'beverage' | 'textile' | 'plastic' | 'chemical' | 'metal' | 'construction' | 'paper';
  icon: string;

  // الإنتاج
  productionCapacity: string; // وصف الطاقة
  productionVolumeAnnual: number; // طن أو وحدة/سنة
  productionUnit: string;

  // الاستثمار والتكلفة (بالريال اليمني)
  initialInvestment: number;
  fixedAssets: number;
  workingCapital: number;
  equipmentCost: number;

  // التشغيل
  workers: number;
  landArea: number; // م²
  buildingArea: number; // م²
  energyNeed: number; // kWh/سنة
  waterNeed: number; // م³/سنة

  // الاقتصاديات
  unitCost: number; // تكلفة الوحدة
  unitPrice: number; // سعر بيع الوحدة
  annualRevenue: number;
  annualCost: number;
  annualProfit: number;
  profitMargin: number; // %

  // السوق
  marketDemand: string;
  targetMarkets: string[];
  exportPotential: 'low' | 'medium' | 'high';

  // التقنية
  productionProcess: string;
  rawMaterials: string;
  equipment: string[];
  qualityStandards: string[];

  // المخاطر والمميزات
  riskLevel: 'low' | 'medium' | 'high';
  paybackPeriod: number; // سنوات
  advantages: string[];
  challenges: string[];

  notes: string;
}

export const FACTORIES_LIBRARY: FactoryInfo[] = [
  // === الصناعات الغذائية ===
  {
    id: 'dairy-factory',
    nameAr: 'مصنع ألبان وتعبيب',
    nameEn: 'Dairy Processing Plant',
    category: 'food',
    icon: '🥛',
    productionCapacity: '5000 لتر/يوم',
    productionVolumeAnnual: 1825000,
    productionUnit: 'لتر',
    initialInvestment: 450000000,
    fixedAssets: 300000000,
    workingCapital: 120000000,
    equipmentCost: 200000000,
    workers: 25,
    landArea: 2000,
    buildingArea: 800,
    energyNeed: 250000,
    waterNeed: 15000,
    unitCost: 180,
    unitPrice: 280,
    annualRevenue: 511000000,
    annualCost: 328000000,
    annualProfit: 183000000,
    profitMargin: 35.8,
    marketDemand: 'طلب محلي متزايد + بديل للمستورد',
    targetMarkets: ['السوق المحلي', 'الخليج'],
    exportPotential: 'medium',
    productionProcess: 'استلام حليب → فحص جودة → بسترة (72°م/15ث) → تبريد → تعبئة → تخزين مبرد. يمكن إنتاج زبادي، جبن، لبن.',
    rawMaterials: 'حليب طازج، عبوات بلاستيكية، ثقافات بكتيرية، ملح، منكهات',
    equipment: ['خزانات استلام 5000 لتر', 'مبستر HTST', 'وحدة تعبئة أوتوماتيكية', 'مبرد 2000 لتر', 'مختبر جودة', 'شاحنة مبردة'],
    qualityStandards: ['HACCP', 'ISO 22000', 'مواصفات دول مجلس التعاون'],
    riskLevel: 'medium',
    paybackPeriod: 3.5,
    advantages: ['طلب يومي على الحليب', 'سلسلة تبريد محلية', 'دعم حكومي للأمن الغذائي'],
    challenges: ['توفير الحليب الخام', 'سلسلة التبريد', 'قصر مدة الصلاحية'],
    notes: 'مصنع ألبان متوسط الحجم. كل 5000 لتر يومياً تنتج 1.8 مليون لتر سنوياً. هامش ربح 35%. يناسب مناطق إنتاج الحليب (ذمار، إب، عمران).',
  },
  {
    id: 'juice-factory',
    nameAr: 'مصنع عصائر وتعبئة',
    nameEn: 'Juice & Beverage Factory',
    category: 'beverage',
    icon: '🧃',
    productionCapacity: '10000 لتر/يوم',
    productionVolumeAnnual: 3000000,
    productionUnit: 'لتر',
    initialInvestment: 350000000,
    fixedAssets: 230000000,
    workingCapital: 100000000,
    equipmentCost: 150000000,
    workers: 18,
    landArea: 1500,
    buildingArea: 600,
    energyNeed: 180000,
    waterNeed: 10000,
    unitCost: 120,
    unitPrice: 220,
    annualRevenue: 660000000,
    annualCost: 360000000,
    annualProfit: 300000000,
    profitMargin: 45.5,
    marketDemand: 'طلب عالٍ صيفاً + بديل للمستورد',
    targetMarkets: ['محلي', 'السعودية', 'الإمارات'],
    exportPotential: 'high',
    productionProcess: 'استلام فواكه → غسيل → عصر → فلترة → بسترة → تعبئة → تخزين. أصناف: مانجو، برتقال، فراولة، عنب، مشكل.',
    rawMaterials: 'فواكه طازجة (مانجو، برتقال)، سكر، ماء، عبوات Tetra Pak أو PET',
    equipment: ['خط عصر 5 طن/ساعة', 'مبستر أنبوبي', 'آلة تعبئة Tetra Pak', 'مختبر جودة', 'مبرد', 'خط تغليف'],
    qualityStandards: ['HACCP', 'ISO 22000', 'FDA (للتصدير)'],
    riskLevel: 'medium',
    paybackPeriod: 2.8,
    advantages: ['مواد خام محلية (مانجو، برتقال)', 'سوق خليجي كبير', 'هامش ربح عالٍ 45%'],
    challenges: ['موسمية الفواكه', 'منافسة المستورد', 'تعبئة Tetra Pak مكلفة'],
    notes: 'مصنع عصائر عالي الربحية. اليمن غني بالفواكه (مانجو الحديدة، عنب صنعاء). هامش 45% = 300 مليون ربح سنوي.',
  },
  {
    id: 'flour-mill',
    nameAr: 'مطحن دقيق',
    nameEn: 'Flour Mill',
    category: 'food',
    icon: '🌾',
    productionCapacity: '50 طن/يوم',
    productionVolumeAnnual: 15000,
    productionUnit: 'طن',
    initialInvestment: 550000000,
    fixedAssets: 400000000,
    workingCapital: 130000000,
    equipmentCost: 280000000,
    workers: 22,
    landArea: 3000,
    buildingArea: 1200,
    energyNeed: 320000,
    waterNeed: 5000,
    unitCost: 180000,
    unitPrice: 250000,
    annualRevenue: 3750000000,
    annualCost: 2700000000,
    annualProfit: 1050000000,
    profitMargin: 28,
    marketDemand: 'طلب محلي ضخم - اليمن يستورد 90%',
    targetMarkets: ['محلي', 'المخبزات', 'الصوامع'],
    exportPotential: 'low',
    productionProcess: 'استلام قمح → تنظيف → ترطيب → طحن → غربلة → تعبئة. ينتج: دقيق أبيض، فاخر، نخالة.',
    rawMaterials: 'قمح (محلي + مستورد)، عبوات 50 كغ',
    equipment: ['سيور نقل', 'آلة تنظيف', 'مطاحن Roller Mill', 'مناخل', 'مبان تخزين', 'خط تعبئة'],
    qualityStandards: ['ISO 22000', 'مواصفات القمح'],
    riskLevel: 'low',
    paybackPeriod: 2.5,
    advantages: ['طلب ضخم مستقر', 'تكنولوجيا ناضجة', 'عائد سريع'],
    challenges: ['استيراد القمح', 'منافسة المطاحن الكبيرة'],
    notes: 'مشروع استراتيجي للأمن الغذائي. 50 طن/يوم = 15000 طن سنوياً. عائد استثنائي 1.05 مليار ربح/سنة. استرداد 2.5 سنة.',
  },
  {
    id: 'poultry-slaughter',
    nameAr: 'مجزرة دواجن آلية',
    nameEn: 'Poultry Slaughterhouse',
    category: 'food',
    icon: '🐔',
    productionCapacity: '3000 طير/ساعة',
    productionVolumeAnnual: 7200000,
    productionUnit: 'طير',
    initialInvestment: 380000000,
    fixedAssets: 270000000,
    workingCapital: 90000000,
    equipmentCost: 200000000,
    workers: 30,
    landArea: 2500,
    buildingArea: 1000,
    energyNeed: 280000,
    waterNeed: 25000,
    unitCost: 1100,
    unitPrice: 1600,
    annualRevenue: 11520000000,
    annualCost: 7920000000,
    annualProfit: 3600000000,
    profitMargin: 31.25,
    marketDemand: 'طلب محلي ضخم + بديل المستورد المجمّد',
    targetMarkets: ['محلي', 'مطاعم', 'سوبر ماركت'],
    exportPotential: 'medium',
    productionProcess: 'استلام طيور → صعق → ذبح → سلق → نزع ريش → تنظيف → تبريد → تعبئة → تجميد',
    rawMaterials: 'دواجن حية، ثلج، عبوات، ماء',
    equipment: ['خط ذبح أوتوماتيكي', 'آلة نزع ريش', 'مبرد سباقي', 'غرفة تجميد -18°', 'خط تعبئة', 'مختبر'],
    qualityStandards: ['HACCP', 'حلال', 'مواصفات صحية'],
    riskLevel: 'medium',
    paybackPeriod: 3,
    advantages: ['طلب يومي مستقر', 'هامش ربح جيد 31%', 'بديل للمستورد'],
    challenges: ['توفير الدواجن الحية', 'سلسلة تبريد', 'اشتراطات صحية صارمة'],
    notes: 'مجزرة آلية متوسطة. 7.2 مليون طير سنوياً. ربح 3.6 مليار ريال. يحتاج مزارع دواجن محلية متعاقدة.',
  },

  // === المشروبات ===
  {
    id: 'water-bottling',
    nameAr: 'مصنع تعبئة مياه',
    nameEn: 'Water Bottling Plant',
    category: 'beverage',
    icon: '💧',
    productionCapacity: '20000 قارورة/ساعة',
    productionVolumeAnnual: 80000000,
    productionUnit: 'قارورة 1.5ل',
    initialInvestment: 280000000,
    fixedAssets: 200000000,
    workingCapital: 60000000,
    equipmentCost: 150000000,
    workers: 15,
    landArea: 1500,
    buildingArea: 500,
    energyNeed: 150000,
    waterNeed: 50000,
    unitCost: 30,
    unitPrice: 100,
    annualRevenue: 8000000000,
    annualCost: 2400000000,
    annualProfit: 5600000000,
    profitMargin: 70,
    marketDemand: 'طلب ضخم ومستمر - مياه شرب',
    targetMarkets: ['محلي', 'خليجي'],
    exportPotential: 'medium',
    productionProcess: 'استخراج ماء بئر → فلترة → UV/أوزون → تعبئة قوارير PET → كبسلة → تغليف',
    rawMaterials: 'ماء (بئر)، قوارير PET، أغطية، لاصقات',
    equipment: ['مضخة بئر', 'فلاتر متعددة', 'وحدة UV', 'آلة تعبئة 20000/ساعة', 'آلة PET', 'كبسلة'],
    qualityStandards: ['WHO Drinking Water', 'مواصفات خليجية'],
    riskLevel: 'low',
    paybackPeriod: 1.8,
    advantages: ['هامش ربح استثنائي 70%', 'عائد سريع جداً', 'طلب مستمر'],
    challenges: ['توفير بئر مياه نقية', 'منافسة شديدة', 'البلاستيك البيئي'],
    notes: 'الأعلى ربحية! 8 مليار ريال ربح سنوي. استرداد 1.8 سنة فقط. يحتاج بئر مياه نقية + موافقة مياه.',
  },

  // === النسيج ===
  {
    id: 'textile-factory',
    nameAr: 'مصنع غزل ونسيج',
    nameEn: 'Textile Spinning & Weaving',
    category: 'textile',
    icon: '🧵',
    productionCapacity: '5 طن قماش/يوم',
    productionVolumeAnnual: 1500,
    productionUnit: 'طن قماش',
    initialInvestment: 680000000,
    fixedAssets: 500000000,
    workingCapital: 150000000,
    equipmentCost: 380000000,
    workers: 50,
    landArea: 5000,
    buildingArea: 2500,
    energyNeed: 500000,
    waterNeed: 20000,
    unitCost: 1800000,
    unitPrice: 2600000,
    annualRevenue: 3900000000,
    annualCost: 2700000000,
    annualProfit: 1200000000,
    profitMargin: 30.8,
    marketDemand: 'بديل للمستورد + سوق محلي كبير',
    targetMarkets: ['محلي', 'مخازن ملابس', 'إفريقيا'],
    exportPotential: 'medium',
    productionProcess: 'استلام قطن → غزل → نسيج → صباغة → تطريز. ينتج قماش قطني ومخلوط.',
    rawMaterials: 'قطن (محلي/مستورد)، أصباغ، مواد كيميائية',
    equipment: ['مغازل', 'أنوال نسيج أوتوماتيكية', 'وحدة صباغة', 'آلة طباعة', 'غلايات'],
    qualityStandards: ['OEKO-TEX', 'مواصفات نسيج'],
    riskLevel: 'medium',
    paybackPeriod: 4.5,
    advantages: ['يمن تنتج قطن', 'سوق محلي كبير', 'فرص عمل كثيفة'],
    challenges: ['استثمار كبير', 'منافسة آسيوية', 'تكنولوجيا متقدمة'],
    notes: 'مشروع استراتيجي لإحياء صناعة النسيج اليمنية. 50 فرصة عمل. يستخدم قطن تهامة المحلي.',
  },

  // === البلاستيك ===
  {
    id: 'plastic-factory',
    nameAr: 'مصنع بلاستيك (أكياس وعبوات)',
    nameEn: 'Plastic Products Factory',
    category: 'plastic',
    icon: '♻️',
    productionCapacity: '2 طن/يوم',
    productionVolumeAnnual: 600,
    productionUnit: 'طن منتجات',
    initialInvestment: 220000000,
    fixedAssets: 160000000,
    workingCapital: 50000000,
    equipmentCost: 120000000,
    workers: 20,
    landArea: 2000,
    buildingArea: 800,
    energyNeed: 200000,
    waterNeed: 3000,
    unitCost: 1800000,
    unitPrice: 2800000,
    annualRevenue: 1680000000,
    annualCost: 1080000000,
    annualProfit: 600000000,
    profitMargin: 35.7,
    marketDemand: 'طلب محلي كبير على الأكياس والعبوات',
    targetMarkets: ['محلي', 'مصانع أغذية', 'مزارع'],
    exportPotential: 'low',
    productionProcess: 'استلام حبيبات بلاستيك → صهر → حقن/نفخ → تشكيل → طباعة → تعبئة',
    rawMaterials: 'حبيبات HDPE، LDPE، PET، PP، أصباغ',
    equipment: ['آلة حقن', 'آلة نفخ', 'آلة فيلم', 'طابعة أوفست', 'كاسر حبيبات'],
    qualityStandards: ['FDA (للعبوات الغذائية)', 'مواصفات بيئية'],
    riskLevel: 'medium',
    paybackPeriod: 2.2,
    advantages: ['سوق محلي كبير', 'تكنولوجيا معروفة', 'ربحية جيدة 36%'],
    challenges: ['استيراد الحبيبات', 'منافسة المستورد', 'قضايا بيئية'],
    notes: 'مصنع بلاستيك متعدد المنتجات (أكياس، عبوات، فيلم). 600 طن سنوياً. ربح 600 مليون ريال.',
  },

  // === الكيماويات ===
  {
    id: 'detergent-factory',
    nameAr: 'مصنع منظفات',
    nameEn: 'Detergent Factory',
    category: 'chemical',
    icon: '🧼',
    productionCapacity: '8 طن/يوم',
    productionVolumeAnnual: 2400,
    productionUnit: 'طن',
    initialInvestment: 180000000,
    fixedAssets: 130000000,
    workingCapital: 40000000,
    equipmentCost: 90000000,
    workers: 15,
    landArea: 1500,
    buildingArea: 600,
    energyNeed: 100000,
    waterNeed: 4000,
    unitCost: 800000,
    unitPrice: 1400000,
    annualRevenue: 3360000000,
    annualCost: 1920000000,
    annualProfit: 1440000000,
    profitMargin: 42.9,
    marketDemand: 'طلب محلي مستمر - منتجات تنظيف',
    targetMarkets: ['محلي', 'مؤسسات', 'فنادق'],
    exportPotential: 'medium',
    productionProcess: 'خلط كيماويات → معالجة → تعبئة → تغليف. منتجات: سائل، مسحوق، صابون.',
    rawMaterials: 'حمض السلفونيك، صودا كاوية، سيليكات، عطور، عبوات',
    equipment: ['خلاطات', 'مفاعل كيميائي', 'خط تعبئة سائل', 'آلة تغليف', 'مختبر'],
    qualityStandards: ['ISO 9001', 'مواصفات سلامة'],
    riskLevel: 'medium',
    paybackPeriod: 2,
    advantages: ['هامش ربح 43%', 'عائد سريع', 'سوق كبير'],
    challenges: ['استيراد المواد الكيميائية', 'سلامة العمال', 'لوائح بيئية'],
    notes: 'مصنع منظفات بـ 2.4 ألف طن سنوياً. ربح 1.44 مليار ريال. استرداد سريع 2 سنة.',
  },

  // === المعادن ===
  {
    id: 'aluminum-factory',
    nameAr: 'مصنع ألمنيوم (نوافذ وأبواب)',
    nameEn: 'Aluminum Products Factory',
    category: 'metal',
    icon: '🪟',
    productionCapacity: '5000 م²/شهر',
    productionVolumeAnnual: 60000,
    productionUnit: 'م²',
    initialInvestment: 320000000,
    fixedAssets: 230000000,
    workingCapital: 70000000,
    equipmentCost: 180000000,
    workers: 35,
    landArea: 2500,
    buildingArea: 1200,
    energyNeed: 220000,
    waterNeed: 1000,
    unitCost: 8000,
    unitPrice: 14000,
    annualRevenue: 840000000,
    annualCost: 480000000,
    annualProfit: 360000000,
    profitMargin: 42.9,
    marketDemand: 'طلب محلي على النوافذ والأبواب',
    targetMarkets: ['محلي', 'مقاولين', 'بناء'],
    exportPotential: 'low',
    productionProcess: 'قطع ألمنيوم → تجميع → تركيب زجاج → تشطيب → تركيب',
    rawMaterials: 'ألمنيوم إكس تروژن، زجاج، إكسسوارات، سيليكون',
    equipment: ['منشار قطع رقمي', 'آلة تجميع', 'ورشة زجاج', 'رافعة', 'خط طلاب أنودة'],
    qualityStandards: ['مواصفات البناء', 'ISO 9001'],
    riskLevel: 'low',
    paybackPeriod: 2.5,
    advantages: ['انتعاش قطاع البناء', 'هامش 43%', 'تكنولوجيا متاحة'],
    challenges: ['استيراد الألمنيوم الخام', 'منافسة'],
    notes: 'مصنع ألمنيوم يخدم قطاع البناء المزدهر. 60 ألف م² سنوياً. ربح 360 مليون ريال.',
  },

  // === البناء ===
  {
    id: 'block-factory',
    nameAr: 'مصنع طوب وبلوك',
    nameEn: 'Block & Brick Factory',
    category: 'construction',
    icon: '🧱',
    productionCapacity: '10000 بلوك/يوم',
    productionVolumeAnnual: 3000000,
    productionUnit: 'بلوك',
    initialInvestment: 150000000,
    fixedAssets: 110000000,
    workingCapital: 30000000,
    equipmentCost: 70000000,
    workers: 12,
    landArea: 5000,
    buildingArea: 1000,
    energyNeed: 80000,
    waterNeed: 8000,
    unitCost: 80,
    unitPrice: 150,
    annualRevenue: 450000000,
    annualCost: 240000000,
    annualProfit: 210000000,
    profitMargin: 46.7,
    marketDemand: 'طلب ضخم بسبب الانتعاش الإنشائي',
    targetMarkets: ['محلي', 'مقاولين'],
    exportPotential: 'low',
    productionProcess: 'خلط إسمنت + رمل + ماء → صب → كبس → تجفيف → تخزين. أنواع: 15، 20، 10 سم.',
    rawMaterials: 'إسمنت، رمل، ماء، حصى',
    equipment: ['ماكينة بلوك أوتوماتيكية', 'خلاطة', 'سيور نقل', 'رافعة شوكية'],
    qualityStandards: ['مواصفات البناء اليمنية'],
    riskLevel: 'low',
    paybackPeriod: 1.5,
    advantages: ['هامش 47%', 'عائد سريع جداً 1.5 سنة', 'طلب محلي ضخم'],
    challenges: ['توفير الرمل عالي الجودة', 'غبار وتلوث'],
    notes: 'الأسرع عائداً! 3 مليون بلوك سنوياً. ربح 210 مليون ريال. استرداد 1.5 سنة فقط.',
  },
  {
    id: 'tiles-factory',
    nameAr: 'مصنع بلاط سيراميك',
    nameEn: 'Ceramic Tiles Factory',
    category: 'construction',
    icon: '⬜',
    productionCapacity: '2000 م²/يوم',
    productionVolumeAnnual: 600000,
    productionUnit: 'م²',
    initialInvestment: 480000000,
    fixedAssets: 350000000,
    workingCapital: 100000000,
    equipmentCost: 280000000,
    workers: 40,
    landArea: 6000,
    buildingArea: 3000,
    energyNeed: 450000,
    waterNeed: 12000,
    unitCost: 1800,
    unitPrice: 3200,
    annualRevenue: 1920000000,
    annualCost: 1080000000,
    annualProfit: 840000000,
    profitMargin: 43.75,
    marketDemand: 'بديل للمستورد + طلب محلي',
    targetMarkets: ['محلي', 'خليجي'],
    exportPotential: 'medium',
    productionProcess: 'خلط طين → كبس → تجفيف → طباعة → فرن 1200° → تلميع → تعبئة',
    rawMaterials: 'طين كاولين، فeldspar، أصباغ، مواد صقيلة',
    equipment: ['مطحنة كروية', 'آلة كبس', 'فرن نفق 1200°', 'آلة طباعة', 'آلة تلميع'],
    qualityStandards: ['ISO 13006', 'مواصفات سيراميك'],
    riskLevel: 'medium',
    paybackPeriod: 3,
    advantages: ['بديل للمستورد', 'هامش 44%', 'طين محلي متوفر'],
    challenges: ['استثمار كبير', 'استهلاك طاقة عالٍ', 'تكنولوجيا معقدة'],
    notes: 'مصنع سيراميك 600 ألف م² سنوياً. ربح 840 مليون ريال. يتوفر طين كاولين محلي.',
  },

  // === الورق ===
  {
    id: 'cardboard-factory',
    nameAr: 'مصنع كرتون وعبوات',
    nameEn: 'Cardboard & Packaging Factory',
    category: 'paper',
    icon: '📦',
    productionCapacity: '15 طن/يوم',
    productionVolumeAnnual: 4500,
    productionUnit: 'طن',
    initialInvestment: 260000000,
    fixedAssets: 190000000,
    workingCapital: 60000000,
    equipmentCost: 130000000,
    workers: 25,
    landArea: 3000,
    buildingArea: 1500,
    energyNeed: 200000,
    waterNeed: 6000,
    unitCost: 800000,
    unitPrice: 1300000,
    annualRevenue: 5850000000,
    annualCost: 3600000000,
    annualProfit: 2250000000,
    profitMargin: 38.5,
    marketDemand: 'طلب كبير من المصانع التجارية',
    targetMarkets: ['محلي', 'مصانع غذائية', 'تصدير'],
    exportPotential: 'medium',
    productionProcess: 'استلام ورق مقوى → طباعة → قطع → طي → لصق → تعبئة. أنواع: علبي، متموج، طباعي.',
    rawMaterials: 'ورق مقوى (مستورد/متراكب)، أحبار، غراء',
    equipment: ['آلة طباعة فلكسو', 'آلة قطع', 'آلة طي ولصق', 'آلة تقطيع', 'كاسر ورق'],
    qualityStandards: ['ISO 14001', 'قابل للتدوير'],
    riskLevel: 'low',
    paybackPeriod: 2.2,
    advantages: ['كل المصانع تحتاج عبوات', 'ربحية 38%', 'استرداد سريع'],
    challenges: ['استيراد الورق الخام', 'منافسة المستورد'],
    notes: 'مصنع عبوات كرتونية يخدم جميع المصانع المحلية. 4500 طن سنوياً. ربح 2.25 مليار ريال.',
  },

  // === مصانع إضافية ===
  {
    id: 'animal-feed-factory',
    nameAr: 'مصنع أعلاف حيوانية',
    nameEn: 'Animal Feed Factory',
    category: 'food',
    icon: '🐂',
    productionCapacity: '50 طن/يوم',
    productionVolumeAnnual: 15000,
    productionUnit: 'طن',
    initialInvestment: 320000000,
    fixedAssets: 230000000,
    workingCapital: 70000000,
    equipmentCost: 180000000,
    workers: 20,
    landArea: 3000,
    buildingArea: 1200,
    energyNeed: 280000,
    waterNeed: 4000,
    unitCost: 220000,
    unitPrice: 320000,
    annualRevenue: 4800000000,
    annualCost: 3300000000,
    annualProfit: 1500000000,
    profitMargin: 31.25,
    marketDemand: 'طلب ضخم محلي - مزارع دواجن وأبقار',
    targetMarkets: ['محلي', 'مزارع دواجن', 'مزارع أبقار'],
    exportPotential: 'medium',
    productionProcess: 'استلام حبوب → طحن → خلط (ذرة، صويا، فيتامينات) → كبس → تعبئة 50كغ',
    rawMaterials: 'ذرة (50%)، كسب صويا (25%)، نخالة، فيتامينات، أملاح، إضافات',
    equipment: ['مطحنة مطرقية', 'خلاطة 2طن', 'آلة كبس Pellet', 'آلة تعبئة', 'سيور نقل', 'مختبر'],
    qualityStandards: ['ISO 22000', 'مواصفات أعلاف'],
    riskLevel: 'low',
    paybackPeriod: 2.8,
    advantages: ['طلب محلي ضخم', 'مواد خام محلية (ذرة)', 'عائد سريع 2.8 سنة'],
    challenges: ['تذبذب أسعار الذرة', 'منافسة المستورد'],
    notes: 'يخدم قطاع الثروة الحيوانية المتنامي. 15000 طن سنوياً = 300 ألف كيس. يستخدم ذرة محلية. ربح 1.5 مليار ريال.',
  },
  {
    id: 'sheep-slaughter',
    nameAr: 'مجزر أغنام آلي',
    nameEn: 'Sheep Slaughterhouse',
    category: 'food',
    icon: '🐑',
    productionCapacity: '500 رأس/يوم',
    productionVolumeAnnual: 150000,
    productionUnit: 'رأس',
    initialInvestment: 280000000,
    fixedAssets: 200000000,
    workingCapital: 60000000,
    equipmentCost: 140000000,
    workers: 35,
    landArea: 3000,
    buildingArea: 1500,
    energyNeed: 200000,
    waterNeed: 30000,
    unitCost: 35000,
    unitPrice: 55000,
    annualRevenue: 8250000000,
    annualCost: 5250000000,
    annualProfit: 3000000000,
    profitMargin: 36.4,
    marketDemand: 'طلب محلي + تصدير للحج (خليجي)',
    targetMarkets: ['محلي', 'السعودية - الحج', 'الإمارات'],
    exportPotential: 'high',
    productionProcess: 'استلام أغنام → فحص بيطري → صعق → ذبح حلال → سلخ → تقطيع → تبريد → تعبئة',
    rawMaterials: 'أغنام حية، ماء، ثلج، عبوات، مواد تنظيف',
    equipment: ['خط ذبح نصف أوتوماتيكي', 'غرفة تبريد -2°م', 'غرفة تجميد -18°م', 'خط تقطيع', 'مختبر بيطري'],
    qualityStandards: ['HACCP', 'حلال', 'مواصفات دول الخليج'],
    riskLevel: 'medium',
    paybackPeriod: 2.5,
    advantages: ['تصدير مربح جداً للحج', 'أغنام يمنية ممتازة', 'هامش 36%'],
    challenges: ['موسمية التصدير', 'اشتراطات بيطرية صارمة', 'توفير الأغنام'],
    notes: 'مجزر متخصص بالأغنام. ذروة الطلب في موسم الحج (تصدير للسعودية). أغنام يمنية (النعيمي، الحدي) مطلوبة عالمياً.',
  },
  {
    id: 'marble-factory',
    nameAr: 'مصنع رخام وبلاط طبيعي',
    nameEn: 'Marble & Stone Factory',
    category: 'construction',
    icon: '🪨',
    productionCapacity: '3000 م²/شهر',
    productionVolumeAnnual: 36000,
    productionUnit: 'م²',
    initialInvestment: 380000000,
    fixedAssets: 280000000,
    workingCapital: 80000000,
    equipmentCost: 220000000,
    workers: 28,
    landArea: 5000,
    buildingArea: 2500,
    energyNeed: 320000,
    waterNeed: 15000,
    unitCost: 3500,
    unitPrice: 7500,
    annualRevenue: 270000000,
    annualCost: 126000000,
    annualProfit: 144000000,
    profitMargin: 53.3,
    marketDemand: 'انتعاش قطاع البناء + فنادق',
    targetMarkets: ['محلي', 'فنادق', 'قصور'],
    exportPotential: 'low',
    productionProcess: 'استلام كتل رخام → قص بمنشار سلكي → تلميع → تقطيع → معالجة → تعبئة',
    rawMaterials: 'كتل رخام (محلي/مستورد)، مواد تلميع، فِبَر، راتنج',
    equipment: ['منشار سلكي', 'آلة تلميع متعددة المراحل', 'آلة قص CNC', 'فرن راتنج', 'رافعة 10 طن'],
    qualityStandards: ['مواصفات البناء', 'ISO 9001'],
    riskLevel: 'medium',
    paybackPeriod: 2.8,
    advantages: ['هامش ربح 53% (الأعلى)', 'رخام محلي متوفر', 'طلب فنادق وفيلات'],
    challenges: ['استثمار كبير', 'استيراد المعدات', 'كثافة عمالة'],
    notes: 'الأعلى هامش ربح (53%)! رخام يمني (بيضاء، حضرموت). يستهدف الفنادق والقصور. 36 ألف م² سنوياً.',
  },
  {
    id: 'furniture-factory',
    nameAr: 'مصنع أثاث منزلي',
    nameEn: 'Furniture Factory',
    category: 'metal',
    icon: '🛋️',
    productionCapacity: '200 قطعة/شهر',
    productionVolumeAnnual: 2400,
    productionUnit: 'قطعة',
    initialInvestment: 220000000,
    fixedAssets: 160000000,
    workingCapital: 50000000,
    equipmentCost: 110000000,
    workers: 40,
    landArea: 3000,
    buildingArea: 2000,
    energyNeed: 180000,
    waterNeed: 2000,
    unitCost: 60000,
    unitPrice: 120000,
    annualRevenue: 288000000,
    annualCost: 144000000,
    annualProfit: 144000000,
    profitMargin: 50,
    marketDemand: 'طلب محلي + طلب قطاع الفنادق',
    targetMarkets: ['محلي', 'فنادق', 'مكاتب'],
    exportPotential: 'medium',
    productionProcess: 'تصميم → قطع خشب → تجميع → تنجيد → تشطيب → تغليف. أنواع: كنب، طاولات، أسرة، خزائن.',
    rawMaterials: 'خشب MDF، إسفنج، قماش، جلد، مسامير، طلاء',
    equipment: ['منشار CNC', 'آلة تجميع', 'ماكينة خياطة', 'آلة رش', 'آلة ضغط', 'ورشة تنجيد'],
    qualityStandards: ['ISO 9001', 'مواصفات أثاث'],
    riskLevel: 'low',
    paybackPeriod: 2,
    advantages: ['هامش 50%', 'عائد سريع 2 سنة', 'عمالة محلية'],
    challenges: ['استيراد الخشب', 'منافسة المستورد'],
    notes: 'مصنع أثاث يخدم قطاع البناء والفنادق المزدهر. 2400 قطعة سنوياً. ربح 144 مليون ريال.',
  },
  {
    id: 'soap-factory',
    nameAr: 'مصنع صابون وكريمات',
    nameEn: 'Soap & Cosmetics Factory',
    category: 'chemical',
    icon: '🧴',
    productionCapacity: '5 طن/يوم',
    productionVolumeAnnual: 1500,
    productionUnit: 'طن',
    initialInvestment: 150000000,
    fixedAssets: 110000000,
    workingCapital: 30000000,
    equipmentCost: 75000000,
    workers: 12,
    landArea: 1200,
    buildingArea: 500,
    energyNeed: 90000,
    waterNeed: 5000,
    unitCost: 1200000,
    unitPrice: 2200000,
    annualRevenue: 3300000000,
    annualCost: 1800000000,
    annualProfit: 1500000000,
    profitMargin: 45.5,
    marketDemand: 'طلب محلي مستمر + فرص تصدير',
    targetMarkets: ['محلي', 'صيدليات', 'سوبر ماركت'],
    exportPotential: 'medium',
    productionProcess: 'صهر زيتيات → إضافة صودا → تصبين → إضافة عطور/ألوان → قولبة → تغليف',
    rawMaterials: 'زيت زيتون/نخيل، صودا كاوية، عطور، أصباغ، عبوات',
    equipment: ['مفاعل تصبين', 'آلة قولبة', 'خط تغليف', 'مختبر جودة', 'خلاطات'],
    qualityStandards: ['GMP', 'ISO 22716 (مستحضرات تجميل)'],
    riskLevel: 'low',
    paybackPeriod: 1.8,
    advantages: ['هامش 45%', 'عائد سريع 1.8 سنة', 'زيت زيتون محلي متوفر'],
    challenges: ['استيراد العطور', 'منافسة'],
    notes: 'مصنع صابون طبيعي بزيت الزيتون اليمني. شهرة تاريخية (صابون صنعاء). استرداد 1.8 سنة فقط.',
  },
  {
    id: 'tuna-canning',
    nameAr: 'مصنع تعليب تونة',
    nameEn: 'Tuna Canning Factory',
    category: 'food',
    icon: '🐟',
    productionCapacity: '20 طن/يوم',
    productionVolumeAnnual: 5000,
    productionUnit: 'طن',
    initialInvestment: 520000000,
    fixedAssets: 380000000,
    workingCapital: 110000000,
    equipmentCost: 280000000,
    workers: 45,
    landArea: 4000,
    buildingArea: 2000,
    energyNeed: 380000,
    waterNeed: 25000,
    unitCost: 3500000,
    unitPrice: 5500000,
    annualRevenue: 27500000000,
    annualCost: 17500000000,
    annualProfit: 10000000000,
    profitMargin: 36.4,
    marketDemand: 'طلب ضخم محلي + تصدير عالمي',
    targetMarkets: ['محلي', 'السعودية', 'أوروبا', 'أمريكا'],
    exportPotential: 'high',
    productionProcess: 'استلام تونة → تنظيف → طبخ → تعليب → إضافة صلصة → تعقيم → تعبئة',
    rawMaterials: 'تونة طازجة (محلية)، علب صفيح، زيت/صلصة، ملح',
    equipment: ['خط تعليب أوتوماتيكي', 'مفاعل تعقيم', 'آلة طبخ', 'آلة ملء', 'مختبر جودة', 'مبرد'],
    qualityStandards: ['HACCP', 'BRC', 'FDA', 'حلال'],
    riskLevel: 'medium',
    paybackPeriod: 2.5,
    advantages: ['سواحل يمنية غنية بالتونة', 'ربح 10 مليار/سنة!', 'تصدير عالمي'],
    challenges: ['استثمار كبير', 'صيد مستدام', 'صيانة معقدة'],
    notes: 'الأعلى ربحاً مطلقاً (10 مليار ريال/سنة). اليمن لديها سواحل غنية بالتونة (المكلا، الحديدة). تصدير عالمي مربح.',
  },
  {
    id: 'honey-packaging',
    nameAr: 'مصنع تعبئة وتعبئة عسل',
    nameEn: 'Honey Packaging Plant',
    category: 'food',
    icon: '🍯',
    productionCapacity: '3 طن/شهر',
    productionVolumeAnnual: 36,
    productionUnit: 'طن',
    initialInvestment: 90000000,
    fixedAssets: 65000000,
    workingCapital: 20000000,
    equipmentCost: 45000000,
    workers: 10,
    landArea: 800,
    buildingArea: 400,
    energyNeed: 60000,
    waterNeed: 1500,
    unitCost: 35000000,
    unitPrice: 50000000,
    annualRevenue: 1800000000,
    annualCost: 1260000000,
    annualProfit: 540000000,
    profitMargin: 30,
    marketDemand: 'عسل يمني عالمي السمعة - طلب تصديري ضخم',
    targetMarkets: ['محلي', 'السعودية', 'الإمارات', 'آسيا'],
    exportPotential: 'high',
    productionProcess: 'استلام عسل خام → فلترة → فحص جودة → تعبئة برطيلات زجاجية → لحام → تغليف',
    rawMaterials: 'عسل خام (سدر، سمر، زهرة)، برطيلات زجاج، ملصقات، علب كرتون',
    equipment: ['وحدة فلترة', 'آلة تعبئة أوتوماتيكية', 'آلة لحام', 'مختبر جودة', 'خط تغليف'],
    qualityStandards: ['مواصفات عسل خليجية', 'Codex Alimentarius'],
    riskLevel: 'low',
    paybackPeriod: 1.5,
    advantages: ['عسل يمني عالمي السمعة', 'هامش 30% + عائد سريع 1.5 سنة', 'تصدير مربح'],
    challenges: ['توفير العسل الخام الفاخر', 'مكافحة الغش'],
    notes: 'عسل سدر حضرموت (وادي دوعن) عالمي السمعة ($100-200/كغ). استرداد 1.5 سنة فقط. أقل استثمار (90 مليون) وأعلى عائد نسبي.',
  },
  {
    id: 'cement-blocks',
    nameAr: 'مصنع بلوك إسمنتي + خرسانة جاهزة',
    nameEn: 'Cement Blocks & Ready Mix Concrete',
    category: 'construction',
    icon: '🏗️',
    productionCapacity: '20000 بلوك/يوم + 100 م³ خرسانة',
    productionVolumeAnnual: 6000000,
    productionUnit: 'بلوك + م³',
    initialInvestment: 280000000,
    fixedAssets: 200000000,
    workingCapital: 60000000,
    equipmentCost: 160000000,
    workers: 30,
    landArea: 8000,
    buildingArea: 2500,
    energyNeed: 250000,
    waterNeed: 20000,
    unitCost: 90,
    unitPrice: 170,
    annualRevenue: 1020000000,
    annualCost: 540000000,
    annualProfit: 480000000,
    profitMargin: 47.1,
    marketDemand: 'انتعاش قطاع البناء - طلب ضخم',
    targetMarkets: ['محلي', 'مقاولين', 'بناء'],
    exportPotential: 'low',
    productionProcess: 'بلوك: خلط إسمنت+رمل+ماء → صب → كبس → تجفيف. خرسانة: خلط → نقل بشاحنات مزيج',
    rawMaterials: 'إسمنت، رمل، حصى، ماء، إضافات',
    equipment: ['ماكينة بلوك أوتوماتيكية', 'محطة خرسانة جاهزة 60م³/ساعة', 'شاحنات مزيج 3 وحدات', 'خلاطات'],
    qualityStandards: ['مواصفات البناء اليمنية', 'ASTM'],
    riskLevel: 'low',
    paybackPeriod: 2,
    advantages: ['طلب ضخم محلي', 'هامش 47%', 'استرداد 2 سنة', 'تكنولوجيا بسيطة'],
    challenges: ['توفير الرمل', 'غبار وصحة عمال'],
    notes: 'مصنع متكامل للبناء: بلوك + خرسانة جاهزة. يخدم قطاع البناء المزدهر. 6 مليون بلوك + 30 ألف م³ خرسانة سنوياً.',
  },

  // === مصانع إضافية ===
  {
    id: 'ice-factory',
    nameAr: 'مصنع ثلج صناعي',
    nameEn: 'Ice Factory',
    category: 'food',
    icon: '🧊',
    productionCapacity: '20 طن ثلج/يوم',
    productionVolumeAnnual: 6000,
    productionUnit: 'طن',
    initialInvestment: 120000000,
    fixedAssets: 85000000,
    workingCapital: 25000000,
    equipmentCost: 65000000,
    workers: 8,
    landArea: 800,
    buildingArea: 300,
    energyNeed: 350000,
    waterNeed: 8000,
    unitCost: 15000,
    unitPrice: 35000,
    annualRevenue: 210000000,
    annualCost: 90000000,
    annualProfit: 120000000,
    profitMargin: 57.1,
    marketDemand: 'طلب ضخم لصيد الأسماك + محلات + فعاليات',
    targetMarkets: ['محلي', 'صيادين', 'مطاعم', 'مستشفيات'],
    exportPotential: 'low',
    productionProcess: 'تنقية مياه → تجميد في قوالب → تخزين براد → توزيع',
    rawMaterials: 'ماء (بئر/شبكة)، كهرباء، عبوات',
    equipment: ['مكينة ثلج 20طن/يوم', 'خزان ماء', 'فلتر UV', 'براد تخزين', 'شاحنة توزيع'],
    qualityStandards: ['مواصفات مياه شرب', 'صحي'],
    riskLevel: 'low',
    paybackPeriod: 1.5,
    advantages: ['هامش 57% (الأعلى!)', 'استرداد 1.5 سنة فقط', 'طلب مستمر', 'استثمار قليل'],
    challenges: ['استهلاك كهرباء عالٍ', 'منافسة محلية'],
    notes: 'الأسرع عائداً والأعلى هامش! استثمار قليل (120 مليون) + عائد سريع. يخدم قطاع الصيد والمطاعم. 6000 طن سنوياً.',
  },
  {
    id: 'feed-pellet',
    nameAr: 'مصنع أعلاف مضغوطة (Pellet)',
    nameEn: 'Pellet Feed Factory',
    category: 'food',
    icon: '🐄',
    productionCapacity: '30 طن/يوم',
    productionVolumeAnnual: 9000,
    productionUnit: 'طن',
    initialInvestment: 250000000,
    fixedAssets: 180000000,
    workingCapital: 50000000,
    equipmentCost: 140000000,
    workers: 15,
    landArea: 2500,
    buildingArea: 1000,
    energyNeed: 250000,
    waterNeed: 3000,
    unitCost: 250000,
    unitPrice: 380000,
    annualRevenue: 3420000000,
    annualCost: 2250000000,
    annualProfit: 1170000000,
    profitMargin: 34.2,
    marketDemand: 'طلب ضخم من مزارع الدواجن والأبقار',
    targetMarkets: ['محلي', 'مزارع دواجن', 'مزارع أبقار'],
    exportPotential: 'medium',
    productionProcess: 'طحن حبوب → خلق (ذرة، صويا، فيتامينات) → كبس Pellet → تبريد → تعبئة 50كغ',
    rawMaterials: 'ذرة، كسب صويا، نخالة، فيتامينات، أملاح',
    equipment: ['مطحنة مطرقية', 'خلاطة 2طن', 'آلة كبس Pellet 5طن/ساعة', 'مبردة', 'آلة تعبئة', 'سيور'],
    qualityStandards: ['ISO 22000', 'مواصفات أعلاف'],
    riskLevel: 'low',
    paybackPeriod: 2.5,
    advantages: ['طلب محلي ضخم', 'ذرة محلية', 'ربح 1.17 مليار/سنة', 'استرداد 2.5 سنة'],
    challenges: ['تذبذب أسعار الذرة', 'منافسة المستورد'],
    notes: 'مصنع أعلاف pellet متخصص. 9000 طن سنوياً. يخدم قطاع الثروة الحيوانية المتنامي. ربح 1.17 مليار ريال.',
  },
  {
    id: 'glass-factory',
    nameAr: 'مصنع زجاج وعبوات زجاجية',
    nameEn: 'Glass Container Factory',
    category: 'metal',
    icon: '🥃',
    productionCapacity: '50 طن/يوم',
    productionVolumeAnnual: 15000,
    productionUnit: 'طن',
    initialInvestment: 680000000,
    fixedAssets: 500000000,
    workingCapital: 150000000,
    equipmentCost: 380000000,
    workers: 50,
    landArea: 6000,
    buildingArea: 3000,
    energyNeed: 800000,
    waterNeed: 15000,
    unitCost: 800000,
    unitPrice: 1300000,
    annualRevenue: 19500000000,
    annualCost: 12000000000,
    annualProfit: 7500000000,
    profitMargin: 38.5,
    marketDemand: 'طلب محلي ضخم من مصانع الأغذية والمشروبات',
    targetMarkets: ['محلي', 'مصانع أغذية', 'مصانع أدوية'],
    exportPotential: 'medium',
    productionProcess: 'صهر رمل سيليكا + صودا → تشكيل → تبريد → فحص → تعبئة',
    rawMaterials: 'رمل سيليكا (محلي!)، صودا كاوية، حجر جيري، زجاج معاد تدويره',
    equipment: ['فرن صهر 50طن/يوم', 'آلة تشكيل IS', 'فرن تلدين', 'خط فحص', 'خط تعبئة'],
    qualityStandards: ['ISO 9001', 'FDA'],
    riskLevel: 'medium',
    paybackPeriod: 3.5,
    advantages: ['رمل سيليكا محلي متوفر', 'بديل للمستورد', 'ربح 7.5 مليار/سنة', '50 فرصة عمل'],
    challenges: ['استثمار كبير', 'استهلاك طاقة عالٍ', 'تكنولوجيا معقدة'],
    notes: 'صناعة استراتيجية! اليمن غنية بالرمل السيليكي. 15000 طن عبوات زجاجية سنوياً. ربح 7.5 مليار ريال. يخدم كل المصانع.',
  },
  {
    id: 'leather-factory',
    nameAr: 'مصنع جلود وأحذية',
    nameEn: 'Leather & Shoes Factory',
    category: 'textile',
    icon: '👞',
    productionCapacity: '2000 زوج/يوم',
    productionVolumeAnnual: 600000,
    productionUnit: 'زوج',
    initialInvestment: 200000000,
    fixedAssets: 140000000,
    workingCapital: 45000000,
    equipmentCost: 100000000,
    workers: 45,
    landArea: 2500,
    buildingArea: 1500,
    energyNeed: 150000,
    waterNeed: 8000,
    unitCost: 15000,
    unitPrice: 28000,
    annualRevenue: 16800000000,
    annualCost: 9000000000,
    annualProfit: 7800000000,
    profitMargin: 46.4,
    marketDemand: 'طلب محلي ضخم + تصدير',
    targetMarkets: ['محلي', 'السعودية', 'إفريقيا'],
    exportPotential: 'high',
    productionProcess: 'دباغة جلود → قص → خياطة → تجميع → تشطيب → تعبئة',
    rawMaterials: 'جلود خام (محلية!)، مواد دباغة، نعال، خيوط، صمغ',
    equipment: ['آلة دباغة', 'قص CNC', 'ماكينة خياطة 20 وحدة', 'آلة تجميع', 'آلة تشطيب'],
    qualityStandards: ['ISO 9001', 'مواصفات أحذية'],
    riskLevel: 'medium',
    paybackPeriod: 2,
    advantages: ['جلود محلية متوفرة', 'هامش 46%', 'عائد سريع 2 سنة', 'تصدير'],
    challenges: ['تكنولوجيا الدباغة', 'منافسة الآسيوي'],
    notes: 'يستخدم جلود محلية (أبقار، أغنام، جمال). 600 ألف زوج سنوياً. ربح 7.8 مليار ريال. 45 فرصة عمل.',
  },
  {
    id: 'biscuit-factory',
    nameAr: 'مصنع بسكويت وحلويات',
    nameEn: 'Biscuit & Confectionery Factory',
    category: 'food',
    icon: '🍪',
    productionCapacity: '8 طن/يوم',
    productionVolumeAnnual: 2400,
    productionUnit: 'طن',
    initialInvestment: 180000000,
    fixedAssets: 130000000,
    workingCapital: 40000000,
    equipmentCost: 90000000,
    workers: 20,
    landArea: 2000,
    buildingArea: 1000,
    energyNeed: 120000,
    waterNeed: 3000,
    unitCost: 1500000,
    unitPrice: 2800000,
    annualRevenue: 6720000000,
    annualCost: 3600000000,
    annualProfit: 3120000000,
    profitMargin: 46.4,
    marketDemand: 'طلب محلي ضخم + أطفال',
    targetMarkets: ['محلي', 'بقالات', 'سوبر ماركت', 'مدارس'],
    exportPotential: 'medium',
    productionProcess: 'خلط دقيق+سكر+زبدة → تشكيل → خبز → تعبئة → تغليف',
    rawMaterials: 'دقيق، سكر، زبدة، شوكولاتة، عبوات',
    equipment: ['خلاطة', 'آلة تشكيل Biscuit', 'فرن نفق 15م', 'آلة تعبئة', 'آلة تغليف'],
    qualityStandards: ['HACCP', 'ISO 22000'],
    riskLevel: 'low',
    paybackPeriod: 1.8,
    advantages: ['هامش 46%', 'استرداد 1.8 سنة', 'طلب مستمر', 'دقيق محلي'],
    challenges: ['منافسة المستورد', 'صحة وجودة'],
    notes: 'مصنع بسكويت وحلويات. 2400 طن سنوياً. ربح 3.12 مليار ريال. استرداد 1.8 سنة فقط. يناسب السوق المحلي.',
  },
  {
    id: 'paint-factory',
    nameAr: 'مصنع دهانات وطلاء',
    nameEn: 'Paint & Coatings Factory',
    category: 'chemical',
    icon: '🎨',
    productionCapacity: '15 طن/يوم',
    productionVolumeAnnual: 4500,
    productionUnit: 'طن',
    initialInvestment: 220000000,
    fixedAssets: 160000000,
    workingCapital: 50000000,
    equipmentCost: 110000000,
    workers: 18,
    landArea: 2500,
    buildingArea: 1200,
    energyNeed: 130000,
    waterNeed: 5000,
    unitCost: 1800000,
    unitPrice: 3200000,
    annualRevenue: 14400000000,
    annualCost: 8100000000,
    annualProfit: 6300000000,
    profitMargin: 43.75,
    marketDemand: 'انتعاش قطاع البناء - طلب ضخم',
    targetMarkets: ['محلي', 'مقاولين', 'ديكور'],
    exportPotential: 'low',
    productionProcess: 'خلط راتنج + أصباغ + مذيبات → طحن → فلترة → تعبئة',
    rawMaterials: 'راتنج أكريلك، TiO2، مذيبات، أصباغ، عبوات',
    equipment: ['خلاطات عالية السرعة', 'مطحنة رملية', 'فلتر', 'آلة تعبئة', 'مختبر'],
    qualityStandards: ['ISO 9001', 'مواصفات دهانات'],
    riskLevel: 'low',
    paybackPeriod: 2,
    advantages: ['انتعاش البناء', 'هامش 44%', 'استرداد 2 سنة', 'تكنولوجيا معروفة'],
    challenges: ['استيراد الراتنج', 'مواد خطرة'],
    notes: 'مصنع دهانات (مائي + زيتي). 4500 طن سنوياً. ربح 6.3 مليار ريال. يخدم قطاع البناء المزدهر.',
  },

  // === مصانع إضافية (دورة 4) ===
  {
    id: 'noodle-factory',
    nameAr: 'مصنع مكرونة ومعكرونة',
    nameEn: 'Pasta & Noodle Factory',
    category: 'food',
    icon: '🍝',
    productionCapacity: '10 طن/يوم',
    productionVolumeAnnual: 3000,
    productionUnit: 'طن',
    initialInvestment: 170000000,
    fixedAssets: 120000000,
    workingCapital: 40000000,
    equipmentCost: 85000000,
    workers: 15,
    landArea: 1800,
    buildingArea: 900,
    energyNeed: 100000,
    waterNeed: 3000,
    unitCost: 1200000,
    unitPrice: 2200000,
    annualRevenue: 6600000000,
    annualCost: 3600000000,
    annualProfit: 3000000000,
    profitMargin: 45.5,
    marketDemand: 'طلب محلي ضخم - بديل للمستورد',
    targetMarkets: ['محلي', 'سوبر ماركت', 'بقالات'],
    exportPotential: 'medium',
    productionProcess: 'عجن دقيق → تشكيل → تجفيف → تعبئة. أنواع: سباغيتي، بيني، فوسيلي.',
    rawMaterials: 'دقيق سميد (قمح)، ماء، عبوات بلاستيك',
    equipment: ['عجانة أوتوماتيكية', 'آلة تشكيل Pasta', 'مجفف نفق 30م', 'آلة تعبئة', 'مختبر'],
    qualityStandards: ['HACCP', 'ISO 22000'],
    riskLevel: 'low',
    paybackPeriod: 1.8,
    advantages: ['هامش 45%', 'استرداد 1.8 سنة', 'دقيق محلي', 'طلب مستمر'],
    challenges: ['منافسة المستورد', 'جودة الدقيق'],
    notes: 'مصنع مكرونة 3000 طن سنوياً. ربح 3 مليار ريال. استرداد سريع 1.8 سنة. بديل للمستورد.',
  },
  {
    id: 'shampoo-factory',
    nameAr: 'مصنع شامبو ومنظفات شخصية',
    nameEn: 'Shampoo & Personal Care Factory',
    category: 'chemical',
    icon: '🧴',
    productionCapacity: '8 طن/يوم',
    productionVolumeAnnual: 2400,
    productionUnit: 'طن',
    initialInvestment: 150000000,
    fixedAssets: 110000000,
    workingCapital: 30000000,
    equipmentCost: 75000000,
    workers: 12,
    landArea: 1200,
    buildingArea: 600,
    energyNeed: 80000,
    waterNeed: 6000,
    unitCost: 1500000,
    unitPrice: 3000000,
    annualRevenue: 7200000000,
    annualCost: 3600000000,
    annualProfit: 3600000000,
    profitMargin: 50,
    marketDemand: 'طلب مستمر - منتجات العناية الشخصية',
    targetMarkets: ['محلي', 'صيدليات', 'سوبر ماركت', 'تصدير'],
    exportPotential: 'high',
    productionProcess: 'خلط ماء + سلفونات + إضافات → تعبئة → تغليف. منتجات: شامبو، بلسم، جل استحمام.',
    rawMaterials: 'سلفونات، ماء، عطور، مواد حافظة، عبوات PET',
    equipment: ['مفاعل خلط', 'آلة تعبئة أوتوماتيكية', 'آلة تغليف', 'مختبر جودة', 'خزانات'],
    qualityStandards: ['GMP', 'ISO 22716'],
    riskLevel: 'low',
    paybackPeriod: 1.5,
    advantages: ['هامش 50%!', 'استرداد 1.5 سنة', 'تصدير عالٍ', 'طلب مستمر'],
    challenges: ['استيراد المواد', 'منافسة الماركات'],
    notes: 'مصنع شامبو + جل استحمام. 2400 طن سنوياً. ربح 3.6 مليار ريال. استرداد 1.5 سنة فقط!',
  },
  {
    id: 'frozen-food',
    nameAr: 'مصنع أطعمة مجمدة',
    nameEn: 'Frozen Food Factory',
    category: 'food',
    icon: '🧊',
    productionCapacity: '12 طن/يوم',
    productionVolumeAnnual: 3600,
    productionUnit: 'طن',
    initialInvestment: 280000000,
    fixedAssets: 200000000,
    workingCapital: 60000000,
    equipmentCost: 150000000,
    workers: 25,
    landArea: 2500,
    buildingArea: 1200,
    energyNeed: 200000,
    waterNeed: 8000,
    unitCost: 2000000,
    unitPrice: 3500000,
    annualRevenue: 12600000000,
    annualCost: 7200000000,
    annualProfit: 5400000000,
    profitMargin: 42.9,
    marketDemand: 'طلب متزايد على الأطعمة المجمدة',
    targetMarkets: ['محلي', 'سوبر ماركت', 'مطاعم', 'تصدير'],
    exportPotential: 'medium',
    productionProcess: 'تحضير → طبخ → تجميد سريع IQF → تعبئة → تخزين -18°م. منتجات: خضار، بطاطس، وجبات جاهزة.',
    rawMaterials: 'خضار، لحوم، دجاج، بهارات، عبوات',
    equipment: ['خط طبخ', 'نفق تجميد IQF', 'غرفة تخزين -18°م', 'خط تعبئة', 'مختبر'],
    qualityStandards: ['HACCP', 'ISO 22000', 'حلال'],
    riskLevel: 'medium',
    paybackPeriod: 2.2,
    advantages: ['طلب متزايد', 'هامش 43%', 'تصدير', 'قيمة مضافة عالية'],
    challenges: ['سلسلة تبريد', 'طاقة عالية', 'صلاحية'],
    notes: 'مصنع أطعمة مجمدة. 3600 طن سنوياً. ربح 5.4 مليار ريال. يخدم المطاعم والسوبر ماركت.',
  },
  {
    id: 'nursery-factory',
    nameAr: 'مشتل نباتات وزراعية',
    nameEn: 'Plant Nursery',
    category: 'food',
    icon: '🌱',
    productionCapacity: '100000 شتلة/شهر',
    productionVolumeAnnual: 1200000,
    productionUnit: 'شتلة',
    initialInvestment: 80000000,
    fixedAssets: 55000000,
    workingCapital: 20000000,
    equipmentCost: 35000000,
    workers: 10,
    landArea: 3000,
    buildingArea: 1500,
    energyNeed: 60000,
    waterNeed: 5000,
    unitCost: 300,
    unitPrice: 800,
    annualRevenue: 960000000,
    annualCost: 360000000,
    annualProfit: 600000000,
    profitMargin: 62.5,
    marketDemand: 'طلب متزايد على الشتلات الزراعية',
    targetMarkets: ['محلي', 'مزارعين', 'حدائق', 'متنزهات'],
    exportPotential: 'low',
    productionProcess: 'تحضير بيئة زراعية → زراعة بذور → رعاية → تقسية → بيع. أنواع: خضار، فواكه، زينة، حواجز.',
    rawMaterials: 'بذور، تربة، سماد، أكياس، ماء',
    equipment: ['صوب زراعية', 'نظام ري تنقيط', 'مبرد/دافئ', 'طاولة بذور', 'مظلات'],
    qualityStandards: ['شهادة بذور معتمدة'],
    riskLevel: 'low',
    paybackPeriod: 1.5,
    advantages: ['هامش 62.5% (الأعلى!)', 'استرداد 1.5 سنة', 'طلب متزايد', 'استثمار قليل'],
    challenges: ['أمراض النباتات', 'مناخ'],
    notes: 'مشتل نباتات متخصص. 1.2 مليون شتلة سنوياً. ربح 600 مليون ريال. استثمار قليل + عائد سريع.',
  },
];

export const FACTORY_CATEGORIES = {
  food: { ar: 'غذائية', en: 'Food', color: 'bg-amber-500/10 text-amber-700' },
  beverage: { ar: 'مشروبات', en: 'Beverage', color: 'bg-blue-500/10 text-blue-700' },
  textile: { ar: 'نسيج', en: 'Textile', color: 'bg-purple-500/10 text-purple-700' },
  plastic: { ar: 'بلاستيك', en: 'Plastic', color: 'bg-cyan-500/10 text-cyan-700' },
  chemical: { ar: 'كيماويات', en: 'Chemical', color: 'bg-orange-500/10 text-orange-700' },
  metal: { ar: 'معادن', en: 'Metal', color: 'bg-slate-500/10 text-slate-700' },
  construction: { ar: 'بناء', en: 'Construction', color: 'bg-red-500/10 text-red-700' },
  paper: { ar: 'ورق', en: 'Paper', color: 'bg-emerald-500/10 text-emerald-700' },
};

export function getFactoryById(id: string): FactoryInfo | undefined {
  return FACTORIES_LIBRARY.find((f) => f.id === id);
}
