// قاموس المصطلحات المالية والاقتصادية

export interface GlossaryTerm {
  id: string;
  term: string;
  termEn: string;
  category: 'financial' | 'economic' | 'investment' | 'risk' | 'accounting';
  definitionAr: string;
  definitionEn: string;
  formula?: string;
  example?: string;
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    id: 'npv',
    term: 'صافي القيمة الحالية',
    termEn: 'Net Present Value (NPV)',
    category: 'investment',
    definitionAr: 'مجموع القيم الحالية لكل التدفقات النقدية المستقبلية مخصومة بمعدل خصم محدد، ناقصاً الاستثمار الأولي. إذا كان NPV موجباً فالمشروع مجدي.',
    definitionEn: 'Sum of present values of all future cash flows discounted at a specified rate, minus initial investment. Positive NPV means viable project.',
    formula: 'NPV = Σ [CFt / (1+r)^t] - C0',
    example: 'إذا كانت التدفقات المتوقعة 100,000 سنوياً لـ 5 سنوات، ومعدل الخصم 10%، والاستثمار 300,000، فـ NPV ≈ 79,087',
  },
  {
    id: 'irr',
    term: 'معدل العائد الداخلي',
    termEn: 'Internal Rate of Return (IRR)',
    category: 'investment',
    definitionAr: 'معدل الخصم الذي يجعل NPV يساوي صفراً. كلما زاد IRR عن معدل الخصم المطلوب، كان المشروع أكثر جدوى.',
    definitionEn: 'The discount rate that makes NPV equal to zero. Higher IRR than required rate means more viable project.',
    formula: 'IRR: NPV = 0 → Σ [CFt / (1+IRR)^t] = C0',
    example: 'IRR = 15% يعني أن المشروع يحقق عائداً 15% سنوياً على رأس المال المستثمر',
  },
  {
    id: 'mirr',
    term: 'معدل العائد الداخلي المعدّل',
    termEn: 'Modified Internal Rate of Return (MIRR)',
    category: 'investment',
    definitionAr: 'نسخة محسّنة من IRR تأخذ في الحسبان أن التدفقات الموجبة يعاد استثمارها بمعدل معقول (معدل الخصم) والتدفقات السالبة تموّل بمعدل التمويل.',
    definitionEn: 'Improved IRR that assumes positive cash flows are reinvested at discount rate and negative flows financed at finance rate.',
    formula: 'MIRR = (FV positives / PV negatives)^(1/n) - 1',
  },
  {
    id: 'roi',
    term: 'العائد على الاستثمار',
    termEn: 'Return on Investment (ROI)',
    category: 'financial',
    definitionAr: 'نسبة صافي الربح إلى الاستثمار الأولي، تُعبّر عن كفاءة استخدام رأس المال.',
    definitionEn: 'Ratio of net profit to initial investment, expressing capital efficiency.',
    formula: 'ROI = (Net Profit / Investment) × 100%',
    example: 'استثمار 100,000 وربح 25,000 = ROI 25%',
  },
  {
    id: 'payback',
    term: 'فترة الاسترداد',
    termEn: 'Payback Period',
    category: 'investment',
    definitionAr: 'المدة الزمنية اللازمة لاسترداد الاستثمار الأولي من التدفقات النقدية المتولدة. كلما قصرت كانت أفضل.',
    definitionEn: 'Time required to recover initial investment from generated cash flows. Shorter is better.',
    formula: 'Payback = Years before recovery + (Unrecovered / Cash flow of recovery year)',
    example: 'استثمار 100,000 وتدفق 25,000 سنوياً = 4 سنوات استرداد',
  },
  {
    id: 'discounted-payback',
    term: 'فترة الاسترداد المخصومة',
    termEn: 'Discounted Payback Period',
    category: 'investment',
    definitionAr: 'مثل فترة الاسترداد لكن باستخدام التدفقات النقدية المخصومة (بعد تطبيق معدل الخصم)، تعطي صورة أكثر واقعية.',
    definitionEn: 'Like payback but using discounted cash flows, more realistic.',
  },
  {
    id: 'pi',
    term: 'مؤشر الربحية',
    termEn: 'Profitability Index (PI)',
    category: 'investment',
    definitionAr: 'نسبة القيمة الحالية للتدفقات المستقبلية إلى الاستثمار الأولي. PI > 1 يعني مشروع مجدي.',
    definitionEn: 'Ratio of PV of future cash flows to initial investment. PI > 1 means viable.',
    formula: 'PI = PV of future cash flows / Initial investment',
  },
  {
    id: 'wacc',
    term: 'متوسط تكلفة رأس المال المرجّح',
    termEn: 'Weighted Average Cost of Capital (WACC)',
    category: 'financial',
    definitionAr: 'متوسط تكلفة تمويل الشركة موزوناً حسب نسبة كل من حقوق الملكية والدين في هيكل رأس المال.',
    definitionEn: 'Average financing cost weighted by equity and debt proportions in capital structure.',
    formula: 'WACC = (E/V × Re) + (D/V × Rd × (1-T))',
    example: 'إذا كان 70% ملكية (تكلفة 12%) و30% دين (تكلفة 8%، ضريبة 20%) = WACC 9.72%',
  },
  {
    id: 'break-even',
    term: 'نقطة التعادل',
    termEn: 'Break-even Point',
    category: 'accounting',
    definitionAr: 'حجم المبيعات الذي تتساوى عنده الإيرادات مع التكاليف الكلية (لا ربح ولا خسارة).',
    definitionEn: 'Sales volume where total revenues equal total costs (no profit, no loss).',
    formula: 'BEP = Fixed Costs / (Price - Variable Cost per unit)',
  },
  {
    id: 'margin-of-safety',
    term: 'هامش الأمان',
    termEn: 'Margin of Safety',
    category: 'risk',
    definitionAr: 'الفرق بين المبيعات المتوقعة ومبيعات نقطة التعادل، يُعبّر عن مدى تحمل المشروع لانخفاض المبيعات قبل الخسارة.',
    definitionEn: 'Difference between expected sales and break-even sales, shows tolerance for sales decline.',
    formula: 'MOS = (Actual Sales - Break-even Sales) / Actual Sales × 100%',
  },
  {
    id: 'var',
    term: 'القيمة المعرضة للخطر',
    termEn: 'Value at Risk (VaR)',
    category: 'risk',
    definitionAr: 'أقصى خسارة متوقعة خلال فترة زمنية محددة بمستوى ثقة معين (عادة 95% أو 99%).',
    definitionEn: 'Maximum expected loss over a specific period at a given confidence level (usually 95% or 99%).',
    example: 'VaR 95% = -10M يعني أن هناك احتمال 5% أن تتجاوز الخسارة 10 مليون',
  },
  {
    id: 'cvar',
    term: 'الخسارة المشروطة',
    termEn: 'Conditional Value at Risk (CVaR)',
    category: 'risk',
    definitionAr: 'متوسط الخسائر التي تتجاوز قيمة VaR، تعطي صورة عن أسوأ السيناريوهات.',
    definitionEn: 'Average of losses exceeding VaR, shows worst-case scenarios.',
  },
  {
    id: 'monte-carlo',
    term: 'محاكاة مونت كارلو',
    termEn: 'Monte Carlo Simulation',
    category: 'risk',
    definitionAr: 'تقنية إحصائية تولّد آلاف السيناريوهات العشوائية بناءً على توزيعات احتمالية للمتغيرات، لتقدير مدى المخاطرة.',
    definitionEn: 'Statistical technique generating thousands of random scenarios based on probability distributions to estimate risk.',
  },
  {
    id: 'sensitivity',
    term: 'تحليل الحساسية',
    termEn: 'Sensitivity Analysis',
    category: 'risk',
    definitionAr: 'دراسة كيفية تأثير تغيير متغير واحد (مع بقاء الباقي ثابتاً) على النتيجة. يُحدد المتغيرات الأكثر تأثيراً.',
    definitionEn: 'Studying how changing one variable (holding others constant) affects the outcome. Identifies most impactful variables.',
  },
  {
    id: 'scenario',
    term: 'تحليل السيناريوهات',
    termEn: 'Scenario Analysis',
    category: 'risk',
    definitionAr: 'تقييم المشروع تحت عدة سيناريوهات (متفائل، متعادل، متشائم) مع احتمالات موزونة لحساب القيمة المتوقعة.',
    definitionEn: 'Evaluating project under multiple scenarios (optimistic, realistic, pessimistic) with weighted probabilities.',
  },
  {
    id: 'tornado',
    term: 'مخطط Tornado',
    termEn: 'Tornado Chart',
    category: 'risk',
    definitionAr: 'رسم بياني يرتب المتغيرات حسب تأثيرها على النتيجة (NPV عادة)، من الأعلى تأثيراً للأقل، بشكل يشبه الإعصار.',
    definitionEn: 'Chart ranking variables by their impact on outcome (usually NPV), from highest to lowest, resembling a tornado.',
  },
  {
    id: 'vat',
    term: 'ضريبة القيمة المضافة',
    termEn: 'Value Added Tax (VAT)',
    category: 'accounting',
    definitionAr: 'ضريبة استهلاك تُفرض على القيمة المضافة في كل مرحلة من مراحل الإنتاج والتوزيع. تُحصّل من المستهلك النهائي.',
    definitionEn: 'Consumption tax levied on value added at each production/distribution stage. Collected from final consumer.',
    formula: 'VAT = Output VAT (on sales) - Input VAT (on purchases)',
  },
  {
    id: 'depreciation',
    term: 'الإهلاك',
    termEn: 'Depreciation',
    category: 'accounting',
    definitionAr: 'توزيع تكلفة الأصل الثابت على عمره الإنتاجي بشكل منهجي، يعكس الاستهلاك التدريجي للأصل.',
    definitionEn: 'Systematic allocation of fixed asset cost over its useful life, reflecting gradual consumption.',
    formula: 'Straight-line: (Cost - Salvage value) / Useful life',
  },
  {
    id: 'amortization',
    term: 'الإهلاك (للقرض)',
    termEn: 'Loan Amortization',
    category: 'financial',
    definitionAr: 'جدول سداد القرض بدفعات منتظمة تشمل الفائدة وأصل القرض، بحيث يُسدد بالكامل في نهاية المدة.',
    definitionEn: 'Loan repayment schedule with regular payments covering interest and principal, fully repaid at end.',
    formula: 'PMT = L × [r(1+r)^n] / [(1+r)^n - 1]',
  },
  {
    id: 'working-capital',
    term: 'رأس المال العامل',
    termEn: 'Working Capital',
    category: 'financial',
    definitionAr: 'الفرق بين الأصول المتداولة والخصوم المتداولة، يمثل السيولة المتاحة للتشغيل اليومي.',
    definitionEn: 'Difference between current assets and current liabilities, represents liquidity for daily operations.',
    formula: 'Working Capital = Current Assets - Current Liabilities',
  },
  {
    id: 'cash-flow',
    term: 'التدفق النقدي',
    termEn: 'Cash Flow',
    category: 'financial',
    definitionAr: 'النقد الداخل والخارج من المشروع خلال فترة محددة. التدفق الموجب يعني زيادة في السيولة.',
    definitionEn: 'Cash in and out of project during a period. Positive flow means increased liquidity.',
  },
  {
    id: 'opportunity-cost',
    term: 'التكلفة الاقتصادية البديلة',
    termEn: 'Opportunity Cost',
    category: 'economic',
    definitionAr: 'العائد المتخلى عنه عند اختيار بديل استثماري على آخر. تُستخدم لتقييم أفضل الاستخدامات للموارد.',
    definitionEn: 'Return foregone when choosing one investment alternative over another. Used to evaluate best resource use.',
  },
  {
    id: 'inflation',
    term: 'التضخم',
    termEn: 'Inflation',
    category: 'economic',
    definitionAr: 'الارتفاع المستمر في المستوى العام للأسعار، يقلل من القوة الشرائية للنقد عبر الزمن.',
    definitionEn: 'Continuous rise in general price level, reduces purchasing power over time.',
  },
  {
    id: 'real-vs-nominal',
    term: 'القيم الحقيقية مقابل الاسمية',
    termEn: 'Real vs Nominal Values',
    category: 'economic',
    definitionAr: 'القيم الاسمية تشمل التضخم، بينما الحقيقية معدّلة منه. التحليل الاقتصادي يستخدم القيم الحقيقية.',
    definitionEn: 'Nominal values include inflation, real values are adjusted. Economic analysis uses real values.',
    formula: 'Real = Nominal / (1 + Inflation rate)',
  },
  {
    id: 'swot',
    term: 'تحليل SWOT',
    termEn: 'SWOT Analysis',
    category: 'economic',
    definitionAr: 'أداة استراتيجية تحلل: نقاط القوة (Strengths)، الضعف (Weaknesses)، الفرص (Opportunities)، التهديدات (Threats).',
    definitionEn: 'Strategic tool analyzing: Strengths, Weaknesses, Opportunities, Threats.',
  },
  {
    id: 'porter',
    term: 'قوى بورتر الخمس',
    termEn: "Porter's Five Forces",
    category: 'economic',
    definitionAr: 'إطار تحليلي لقياس جاذبية الصناعة عبر 5 قوى: شدة التنافس، الداخلون الجدد، البدائل، قوة الموردين، قوة المشترين.',
    definitionEn: 'Framework to assess industry attractiveness via 5 forces: rivalry, new entrants, substitutes, supplier power, buyer power.',
  },
  {
    id: 'kpi',
    term: 'مؤشرات الأداء الرئيسية',
    termEn: 'Key Performance Indicators (KPIs)',
    category: 'financial',
    definitionAr: 'مقاييس كمية لتقييم أداء المشروع مقابل أهداف محددة، تساعد في متابعة التقدم واتخاذ القرارات.',
    definitionEn: 'Quantitative metrics evaluating project performance against targets, aid progress tracking and decisions.',
  },
  {
    id: 'sunk-cost',
    term: 'التكاليف الغارقة',
    termEn: 'Sunk Costs',
    category: 'economic',
    definitionAr: 'تكاليف تم إنفاقها ولا يمكن استردادها، يجب تجاهلها في القرارات المستقبلية.',
    definitionEn: 'Costs already spent and unrecoverable, should be ignored in future decisions.',
  },
];

export const GLOSSARY_CATEGORIES = {
  financial: { ar: 'مالي', en: 'Financial', color: 'bg-blue-500/10 text-blue-700' },
  economic: { ar: 'اقتصادي', en: 'Economic', color: 'bg-purple-500/10 text-purple-700' },
  investment: { ar: 'استثماري', en: 'Investment', color: 'bg-emerald-500/10 text-emerald-700' },
  risk: { ar: 'مخاطر', en: 'Risk', color: 'bg-red-500/10 text-red-700' },
  accounting: { ar: 'محاسبي', en: 'Accounting', color: 'bg-amber-500/10 text-amber-700' },
};
