// مشاريع نموذجية كاملة للتعلم
import type { ProjectFull } from '@/hooks/use-projects';

export interface SampleProject {
  id: string;
  nameAr: string;
  nameEn: string;
  icon: string;
  descriptionAr: string;
  descriptionEn: string;
  data: Partial<ProjectFull>;
}

const YEAR = (year: number, revenues: number, costs: number) => ({ year, revenues, costs });

export const SAMPLE_PROJECTS: SampleProject[] = [
  {
    id: 'sample-ice-factory',
    nameAr: 'مصنع ثلج صناعي (مشروع سريع العائد)',
    nameEn: 'Ice Factory (Fast Returns)',
    icon: '🧊',
    descriptionAr: 'مصنع ثلج 20 طن/يوم - أسرع عائد (1.5 سنة) + هامش 57% - يخدم قطاع الصيد',
    descriptionEn: '20 ton/day ice plant - fastest payback (1.5yr) + 57% margin - serves fishing',
    data: {
      name: 'مصنع ثلج السواحل',
      description: 'مصنع ثلج صناعي بطاقة 20 طن/يوم لخدمة قطاع الصيد والمطاعم في الحديدة',
      establishment: {
        projectName: 'مصنع ثلج السواحل',
        projectType: 'صناعة تحويلية - ثلج',
        projectSector: 'صناعة - غذائية',
        projectLocation: 'الحديدة - المنطقة الصناعية',
        projectOwner: 'شركة برودة اليمن',
        projectCapital: 120000000,
        projectDuration: 7,
        projectDescription: 'مصنع ثلج صناعي بطاقة 20 طن/يوم (6000 طن/سنة). يخدم قطاع الصيد البحري (70%)، المطاعم (20%)، المستشفيات (10%). هامش ربح 57%.',
        projectGoals: '1. إنتاج 6000 طن ثلج سنوياً. 2. 8 فرص عمل. 3. دعم قطاع الصيد. 4. أسرع عائد (1.5 سنة).',
        projectJustification: 'الحديدة ميناء صيد رئيسي. الصيادون يحتاجون ثلج يومياً. هامش 57% (الأعلى). استثمار قليل 120 مليون. عائد سريع جداً.',
      },
      socialStudy: {
        jobsCreated: 8,
        indirectJobs: 15,
        localEmployment: 100,
        genderRatio: 10,
        foreignWorkers: 0,
        annualWages: 24000000,
        trainingPrograms: 'تدريب على تشغيل مكائن الثلج والصيانة.',
        communityImpact: '8 وظائف + دعم 200 صياد بالثلج اليومي.',
        developmentImpact: 'دعم قطاع الصيد + الحفاظ على جودة الأسماك.',
      },
      environmentalStudy: {
        airEmissions: 'منخفضة (مكائن كهربائية).',
        waterUsage: '8000 م³/سنة.',
        wasteManagement: 'مياه ذائبة معالجة.',
        energyConsumption: '350,000 kWh/سنة.',
        mitigationMeasures: 'طاقة شمسية مستقبلاً.',
        compliance: 'مواصفات مياه شرب.',
        impactAssessment: 'إيجابي - دعم سلسلة تبريد الأسماك.',
      },
      legalStudy: {
        legalForm: 'شركة ذات مسؤولية محدودة',
        licenses: 'سجل تجاري، رخصة صناعية، شهادة صحية.',
        complianceStatus: 'مكتمل.',
      },
      marketStudy: {
        targetCustomers: 'صيادون (70%)، مطاعم (20%)، مستشفيات (10%)',
        marketSize: 5000000000,
        expectedShare: 30,
        growthRate: 6,
        productPrice: 35000,
        competitors: 'مصانع ثلج محلية قليلة. ميزة: موقع قرب الميناء.',
        competitiveAdvantage: 'قرب الميناء + طاقة إنتاجية كبيرة + توصيل سريع.',
      },
      technicalStudy: {
        productionCapacity: '20 طن/يوم = 6000 طن/سنة',
        productionVolume: 6000,
        productionCost: 90000000,
        laborRequired: 8,
        location: 'الحديدة - المنطقة الصناعية. 800 م². قرب الميناء.',
        utilities: 'كهرباء: شبكة + مولد 100kVA. ماء: بئر + شبكة.',
        productionProcess: 'تنقية مياه → تجميد في قوالب 25كغ → تخزين براد -5°م → توزيع بشاحنة مبردة.',
        rawMaterials: 'ماء (8000م³)، كهرباء، عبوات بلاستيك.',
        equipment: 'مكينة ثلج 20طن/يوم، خزان ماء 5000لتر، فلتر UV، براد تخزين 100م³، شاحنة مبردة.',
      },
      financialStudy: {
        initialInvestment: 110000000,
        fixedAssets: 80000000,
        workingCapital: 25000000,
        operatingCosts: 5000000,
        loans: 60000000,
        interestRate: 7,
        loanPeriod: 5,
        yearsData: [
          YEAR(1, 180000000, 95000000),
          YEAR(2, 195000000, 97000000),
          YEAR(3, 205000000, 99000000),
          YEAR(4, 210000000, 101000000),
          YEAR(5, 210000000, 103000000),
          YEAR(6, 210000000, 105000000),
          YEAR(7, 210000000, 107000000),
        ],
      },
      economicStudy: {
        discountRate: 12,
        riskAnalysis: 'مخاطر منخفضة - طلب مستقر + استثمار قليل.',
        sensitivity: 'حساسية منخفضة - سعر الثلج مستقر.',
      },
    },
  },
  {
    id: 'sample-strawberry-farm',
    nameAr: 'مزرعة فراولة تصديرية (الأعلى ربحية)',
    nameEn: 'Strawberry Export Farm (Highest Profit)',
    icon: '🍓',
    descriptionAr: 'مزرعة فراولة 5 هكتار في الصوب - الأعلى ربحية (29.9 مليون/هكتار)',
    descriptionEn: '5-hectare greenhouse strawberry - highest profitability (29.9M/ha)',
    data: {
      name: 'مزرعة فراولة إب التصديرية',
      description: 'مزرعة فراولة 5 هكتار في صوب زراعية في إب، إنتاج 100 طن سنوياً للتصدير',
      establishment: {
        projectName: 'مزرعة فراولة إب',
        projectType: 'زراعة محمية - فواكه فاخرة',
        projectSector: 'زراعي - فواكه',
        projectLocation: 'إب - منطقة جبلة (ارتفاع 1900م)',
        projectOwner: 'تعاونية فراولة إب',
        projectCapital: 350000000,
        projectDuration: 8,
        projectDescription: 'مزرعة فراولة 5 هكتار في صوب زراعية مكيفة. إنتاج 100 طن سنوياً (20 طن/هكتار). تصدير 60% للسعودية بـ $4/كغ. الأعلى ربحية بين المحاصيل.',
        projectGoals: '1. إنتاج 100 طن فراولة. 2. تصدير 60 طن ($240,000). 3. 15 فرصة عمل. 4. أعلى ربحية (29.9M/هكتار).',
        projectJustification: 'الفراولة الأعلى ربحية بين المحاصيل. إب مناخ معتدل مثالي. تصدير مربح. صوب زراعية تضمن جودة + إنتاج طوال السنة.',
      },
      socialStudy: {
        jobsCreated: 15,
        indirectJobs: 20,
        localEmployment: 90,
        genderRatio: 50,
        foreignWorkers: 0,
        annualWages: 45000000,
        trainingPrograms: 'تدريب على الزراعة المحمية، التقليم، الحصاد الانتقائي.',
        communityImpact: '15 وظيفة + 30 موسمية. دعم 20 أسرة. نموذج زراعة فاخرة.',
        developmentImpact: 'تصدير فاخر $240,000 نقد أجنبي. نموذج تكراري.',
      },
      environmentalStudy: {
        airEmissions: 'إيجابي - نباتات تمتص CO2.',
        waterUsage: '3000 م³/هكتار = 15000 م³/سنة (ري تنقيط).',
        wasteManagement: 'نباتات كسماد. عبوات للتدوير.',
        energyConsumption: '10,000 kWh/سنة (صوب).',
        mitigationMeasures: 'سماد عضوي + مكافحة بيولوجية.',
        compliance: 'GlobalG.A.P + شهادة تصدير.',
        impactAssessment: 'إيجابي - زراعة كثيفة بدون تربة مع تنقيط.',
      },
      legalStudy: {
        legalForm: 'تعاونية زراعية',
        licenses: 'سجل تجاري، رخصة زراعية، شهادة تصدير، GlobalG.A.P.',
        complianceStatus: 'مكتمل.',
      },
      marketStudy: {
        targetCustomers: 'تصدير السعودية (60%)، سوبر ماركت محلي (25%)، فنادق (15%)',
        marketSize: 15000000000,
        expectedShare: 2,
        growthRate: 15,
        productPrice: 2000000,
        competitors: 'فراولة مستوردة (مصر، إسبانيا). ميزة: طازج محلي + جودة عالية.',
        competitiveAdvantage: '1. مناخ إب مثالي. 2. صوب زراعية = إنتاج طوال السنة. 3. طازج = أفضل من المستورد. 4. تصدير مربح.',
      },
      technicalStudy: {
        productionCapacity: '5 هكتار × 20 طن = 100 طن سنوياً',
        productionVolume: 100000,
        productionCost: 120000000,
        laborRequired: 15,
        location: 'إب - جبلة. ارتفاع 1900م. تربة خصبة. مناخ معتدل.',
        utilities: 'ماء: بئر + تنقيط. كهرباء: شبكة + شمسي.',
        productionProcess: 'تجهيز صوب → زراعة شتلات → ري تنقيط → تسميد → حصاد يومي → فرز → تعبئة → تبريد → شحن.',
        rawMaterials: 'شتلات فراولة (50,000)، سماد، مبيدات بيولوجية، عبوات 500غ، صوب.',
        equipment: 'صوب زراعية 5هكتار، نظام ري تنقيط، خزان 100م³، غرفة تبريد، خط تعبئة.',
      },
      financialStudy: {
        initialInvestment: 320000000,
        fixedAssets: 250000000,
        workingCapital: 50000000,
        operatingCosts: 20000000,
        loans: 180000000,
        interestRate: 6,
        loanPeriod: 7,
        yearsData: [
          YEAR(1, 120000000, 90000000),
          YEAR(2, 160000000, 95000000),
          YEAR(3, 180000000, 100000000),
          YEAR(4, 200000000, 105000000),
          YEAR(5, 200000000, 108000000),
          YEAR(6, 200000000, 110000000),
          YEAR(7, 200000000, 112000000),
          YEAR(8, 200000000, 115000000),
        ],
      },
      economicStudy: {
        discountRate: 12,
        riskAnalysis: 'مخاطر متوسطة - آفات + صعوبة تصدير. خطة: صوب + شهادات + تنويع.',
        sensitivity: 'حساسية عالية لسعر التصدير ±$1 = ±35% NPV.',
      },
    },
  },
  {
    id: 'sample-honey-packing',
    nameAr: 'مصنع تعبئة عسل سدر (مشروع تصديري فاخر)',
    nameEn: 'Sidr Honey Packing (Premium Export)',
    icon: '🍯',
    descriptionAr: 'مصنع تعبئة عسل سدر حضرموت - 36 طن/سنة بـ $200/كغ للتصدير العالمي',
    descriptionEn: 'Sidr honey packing - 36 tons/year at $200/kg for global export',
    data: {
      name: 'مصنع عسل وادي دوعن الفاخر',
      description: 'مصنع تعبئة عسل سدر حضرموت الأصلي، 36 طن سنوياً، تصدير للسعودية والإمارات وآسيا',
      establishment: {
        projectName: 'مصنع عسل وادي دوعن',
        projectType: 'صناعة تحويلية - تعبئة',
        projectSector: 'صناعة - غذائية فاخرة',
        projectLocation: 'حضرموت - وادي دوعن',
        projectOwner: 'شركة عسل حضرموت الذهبية',
        projectCapital: 90000000,
        projectDuration: 8,
        projectDescription: 'مصنع تعبئة عسل سدر حضرموت الأصلي. 36 طن سنوياً. سعر الكيلو $100-200 للتصدير الفاخر. أقل استثمار + أعلى عائد نسبي. استرداد 1.5 سنة.',
        projectGoals: '1. تعبئة 36 طن عسل فاخر. 2. تصدير 80% ($720,000). 3. 10 فرص عمل. 4. استرداد 1.5 سنة.',
        projectJustification: 'عسل سدر حضرموت عالمي السمعة ($100-200/كغ). الطلب يفوق العرض بـ 5×. استثمار قليل (90 مليون). عائد استثنائي. استرداد 1.5 سنة.',
      },
      socialStudy: {
        jobsCreated: 10,
        indirectJobs: 100,
        localEmployment: 100,
        genderRatio: 15,
        foreignWorkers: 0,
        annualWages: 30000000,
        trainingPrograms: 'تدريب على فحص الجودة، التعبئة، التصدير.',
        communityImpact: '10 وظائف + دعم 100 نحّال محلي (شراء العسل الخام).',
        developmentImpact: 'تصدير $720,000 نقد أجنبي. نموذج لقيمة مضافة محلية.',
      },
      environmentalStudy: {
        airEmissions: 'منخفضة جداً.',
        waterUsage: '1500 م³/سنة.',
        wasteManagement: 'شمع العسل يُباع. عبوات للتدوير.',
        energyConsumption: '60,000 kWh/سنة.',
        mitigationMeasures: 'دعم النحلين للحفاظ على أشجار السدر.',
        compliance: 'Codex Alimentarius + مواصفات خليجية.',
        impactAssessment: 'إيجابي - دعم النحلين + الحفاظ على السدر.',
      },
      legalStudy: {
        legalForm: 'شركة ذات مسؤولية محدودة',
        licenses: 'سجل تجاري، رخصة صناعية، شهادة تصدير، شهادة منشأ.',
        complianceStatus: 'مكتمل.',
      },
      marketStudy: {
        targetCustomers: 'تصدير السعودية (40%)، الإمارات (25%)، آسيا (20%)، محلي (15%)',
        marketSize: 8000000000,
        expectedShare: 5,
        growthRate: 12,
        productPrice: 50000000,
        competitors: 'عسل يمني آخر + عسل مانوكا النيوزيلندي. ميزة: شهرة سدر حضرموت.',
        competitiveAdvantage: '1. عسل سدر حضرموت عالمي السمعة. 2. شهادة منشأ. 3. تعبئة فاخرة. 4. تصدير مباشر.',
      },
      technicalStudy: {
        productionCapacity: '3 طن/شهر = 36 طن/سنة',
        productionVolume: 36000,
        productionCost: 1260000000,
        laborRequired: 10,
        location: 'حضرموت - وادي دوعن. قرب مصادر العسل الخام.',
        utilities: 'كهرباء: شبكة + مولد. ماء: بئر.',
        productionProcess: 'استلام عسل خام → فحص جودة → فلترة → تعبئة برطيلات زجاجية → لحام → ملصقات → تغليف → تصدير.',
        rawMaterials: 'عسل خام (36 طن × 35M ر.ي)، برطيلات زجاج 500غ (72000)، ملصقات، علب كرتون.',
        equipment: ['وحدة فلترة', 'آلة تعبئة', 'آلة لحام', 'مختبر جودة', 'خط تغليف', 'مكيف تخزين'],
      },
      financialStudy: {
        initialInvestment: 80000000,
        fixedAssets: 55000000,
        workingCapital: 20000000,
        operatingCosts: 5000000,
        loans: 40000000,
        interestRate: 6,
        loanPeriod: 5,
        yearsData: [
          YEAR(1, 1500000000, 1100000000),
          YEAR(2, 1650000000, 1150000000),
          YEAR(3, 1750000000, 1200000000),
          YEAR(4, 1800000000, 1230000000),
          YEAR(5, 1800000000, 1260000000),
          YEAR(6, 1800000000, 1280000000),
          YEAR(7, 1800000000, 1300000000),
          YEAR(8, 1800000000, 1320000000),
        ],
      },
      economicStudy: {
        discountRate: 12,
        riskAnalysis: 'مخاطر منخفضة - طلب يفوق العرض. خطة: عقود مع نحّالين + شهادات.',
        sensitivity: 'حساسية عالية لسعر البيع ±$50 = ±40% NPV.',
      },
    },
  },
  {
    id: 'sample-paint-factory',
    nameAr: 'مصنع دهانات وطلاء (مشروع قطاع البناء)',
    nameEn: 'Paint Factory (Construction Sector)',
    icon: '🎨',
    descriptionAr: 'مصنع دهانات 15 طن/يوم - ربح 6.3 مليار ريال، هامش 44%، يخدم قطاع البناء',
    descriptionEn: '15 ton/day paint factory - 6.3B profit, 44% margin, serves construction',
    data: {
      name: 'مصنع دهانات اليمن الحديث',
      description: 'مصنع دهانات مائية وزيتية بطاقة 15 طن/يوم، يخدم قطاع البناء المزدهر',
      establishment: {
        projectName: 'مصنع دهانات اليمن الحديث',
        projectType: 'صناعة تحويلية - كيماويات',
        projectSector: 'صناعة - كيماويات',
        projectLocation: 'صنعاء - المنطقة الصناعية',
        projectOwner: 'شركة دهانات اليمن',
        projectCapital: 220000000,
        projectDuration: 8,
        projectDescription: 'مصنع دهانات (مائي + زيتي) بطاقة 15 طن/يوم (4500 طن/سنة). يخدم قطاع البناء المزدهر. هامش 44%.',
        projectGoals: '1. إنتاج 4500 طن دهانات. 2. 18 فرصة عمل. 3. بديل للمستورد. 4. ربح 6.3 مليار ريال.',
        projectJustification: 'انتعاش قطاع البناء اليمني. اليمن تستورد معظم الدهانات. هامش 44%. استرداد 2 سنة. ربح 6.3 مليار ريال.',
      },
      socialStudy: {
        jobsCreated: 18,
        indirectJobs: 30,
        localEmployment: 95,
        genderRatio: 10,
        foreignWorkers: 0,
        annualWages: 54000000,
        trainingPrograms: 'تدريب على تصنيع الدهانات، سلامة المواد، الجودة.',
        communityImpact: '18 وظيفة + دعم موردين عبوات + بديل للمستورد.',
        developmentImpact: 'بديل لاستيراد الدهانات = توفير نقد أجنبي.',
      },
      environmentalStudy: {
        airEmissions: 'مذيبات (VOCs) - تحتاج تهوية + فلاتر.',
        waterUsage: '5000 م³/سنة.',
        wasteManagement: 'بقايا دهانات + عبوات + مواد كيميائية.',
        energyConsumption: '130,000 kWh/سنة.',
        mitigationMeasures: 'فلاتر VOCs + تهوية + عبوات قابلة للتدوير.',
        compliance: 'ISO 9001 + مواصفات دهانات.',
        impactAssessment: 'متوسط - يحتاج إدارة جيدة للمواد الخطرة.',
      },
      legalStudy: {
        legalForm: 'شركة ذات مسؤولية محدودة',
        licenses: 'سجل تجاري، رخصة صناعية، موافقة البيئة، شهادة جودة.',
        complianceStatus: 'مكتمل.',
      },
      marketStudy: {
        targetCustomers: 'مقاولين (40%)، محلات دهانات (35%)، أفراد (20%)، مؤسسات (5%)',
        marketSize: 20000000000,
        expectedShare: 15,
        growthRate: 8,
        productPrice: 3200000,
        competitors: 'دهانات مستوردة (Jotun، Hempel). ميزة: سعر منافس + توفر محلي.',
        competitiveAdvantage: '1. سعر أقل من المستورد 25%. 2. توفر محلي. 3. تشكيلة ألوان محلية. 4. خدمة ما بعد البيع.',
      },
      technicalStudy: {
        productionCapacity: '15 طن/يوم = 4500 طن/سنة',
        productionVolume: 4500,
        productionCost: 8100000000,
        laborRequired: 18,
        location: 'صنعاء - المنطقة الصناعية. 2500 م².',
        utilities: 'كهرباء: شبكة + مولد 150kVA. ماء: شبكة.',
        productionProcess: 'خلط راتنج + أصباغ + مذيبات → طحن بالمطحنة الرملية → فلترة → تعبئة → تغليف.',
        rawMaterials: 'راتنج أكريليك، TiO2، مذيبات، أصباغ، عبوات بلاستيك/حديد.',
        equipment: ['خلاطات عالية السرعة', 'مطحنة رملية', 'فلتر', 'آلة تعبئة', 'مختبر جودة'],
      },
      financialStudy: {
        initialInvestment: 200000000,
        fixedAssets: 140000000,
        workingCapital: 50000000,
        operatingCosts: 10000000,
        loans: 100000000,
        interestRate: 7,
        loanPeriod: 5,
        yearsData: [
          YEAR(1, 12000000000, 7800000000),
          YEAR(2, 13500000000, 8100000000),
          YEAR(3, 14400000000, 8400000000),
          YEAR(4, 14400000000, 8600000000),
          YEAR(5, 14400000000, 8800000000),
          YEAR(6, 14400000000, 9000000000),
          YEAR(7, 14400000000, 9200000000),
          YEAR(8, 14400000000, 9400000000),
        ],
      },
      economicStudy: {
        discountRate: 12,
        riskAnalysis: 'مخاطر منخفضة - طلب مستقر من قطاع البناء.',
        sensitivity: 'حساسية متوسطة لأسعار الراتنج المستورد.',
      },
    },
  },
  {
    id: 'sample-bakery',
    nameAr: 'مخبز حديث (مشروع مجدي)',
    nameEn: 'Modern Bakery (Viable Project)',
    icon: '🥖',
    descriptionAr: 'مخبز لإنتاج الخبز والمعجنات - مثال لمشروع مجدي بـ NPV موجب',
    descriptionEn: 'Bakery for bread and pastries - example of viable project with positive NPV',
    data: {
      name: 'مخبز السعادة الحديث',
      description: 'مخبز آلي لإنتاج الخبز والمعجنات اليومية بسعة 5000 رغيف/يوم',
      establishment: {
        projectName: 'مخبز السعادة الحديث',
        projectType: 'مخبز آلي',
        projectSector: 'صناعة غذائية',
        projectLocation: 'صنعاء - شارع تعز',
        projectOwner: 'أحمد محمد علي',
        projectCapital: 45000000,
        projectDuration: 5,
        projectStartDate: '2026-01-01',
        projectDescription: 'مخبز حديث بإنتاج يومي 5000 رغيف خبز + 500 قطعة معجنات',
        projectGoals: 'توفير خبز نظيف وعالي الجودة بأسعار منافسة للمنطقة',
        projectJustification: 'نقص في المخابز الحديثة بالمنطقة + طلب يومي متنامٍ',
      },
      marketStudy: {
        targetCustomers: 'الأسر، المحلات الصغيرة، المطاعم',
        marketSize: 30000000,
        expectedShare: 15,
        growthRate: 8,
        productPrice: 100,
        competitors: 'مخبز النور، مخبز الأمل، المخابز التقليدية',
        competitiveAdvantage: 'جودة عالية، نظافة، توزيع منظم، تنوع في المنتجات',
        segments: 'أسر (60%)، محلات (30%)، مطاعم (10%)',
        pricingStrategy: 'سعر تنافسي 10% أقل من المنافسين مع جودة أعلى',
        distribution: 'بيع مباشر + 3 موزعين + توصيل للمناطق القريبة',
        promotion: 'إعلانات محلية، عينات مجانية في أول أسبوع',
        demandForecast: 'طلب متزايد 8% سنوياً حسب نمو السكان',
        swot: 'القوة: جودة، موقع. الضعف: رأس مال محدود. الفرص: توسع. التهديدات: منافسين جدد',
      },
      technicalStudy: {
        productionCapacity: '5000 رغيف/يوم',
        productionVolume: 1825000,
        productionCost: 25000000,
        laborRequired: 6,
        location: '200 م² - شارع رئيسي',
        utilities: 'كهرباء ثلاثية، ماء، غاز صناعي',
        productionProcess: 'عجن → تخمير → تشكيل → خبز → تبريد → تعبئة',
        rawMaterials: 'دقيق (5 أطنان/شهر)، خميرة، ملح، سكر، زيت',
        equipment: 'فرن صناعي، عجانة 50 كجم، ماكينة تقطيع، عربات نقل',
        machinery: 'فرن tunnel، عجانة دوارة، مبرد',
        qualityControl: 'فحص يومي للعجين والمنتج النهائي',
        maintenance: 'صيانة شهرية للأفران، يومية للنظافة',
      },
      financialStudy: {
        initialInvestment: 30000000,
        fixedAssets: 20000000,
        workingCapital: 7000000,
        operatingCosts: 3000000,
        loans: 10000000,
        interestRate: 8,
        loanPeriod: 5,
        yearsData: [
          YEAR(1, 28000000, 18000000),
          YEAR(2, 32000000, 19500000),
          YEAR(3, 36000000, 21000000),
          YEAR(4, 40000000, 22500000),
          YEAR(5, 44000000, 24000000),
        ],
      },
      economicStudy: {
        discountRate: 12,
        riskAnalysis: 'مخاطر منخفضة - منتج أساسي يومي الطلب',
        sensitivity: 'حساسية معتدلة لتكاليف الدقيق (60% من المواد الخام)',
        economicImpact: 'توفير 6 فرص عمل، دعم الموردين المحليين',
      },
      socialStudy: {
        jobsCreated: 6,
        indirectJobs: 4,
        localEmployment: 90,
        genderRatio: 20,
        foreignWorkers: 0,
        annualWages: 18000000,
        trainingPrograms: 'تدريب فني على الخبز الصناعي والجودة',
        communityImpact: 'توفير خبز نظيف بأسعار مناسبة لـ 2000 أسرة',
        developmentImpact: 'دعم المزارعين المحليين بشراء القمح',
      },
      environmentalStudy: {
        airEmissions: 'انبعاثات من الأفران (ضمن الحدود المسموحة)',
        waterUsage: '2 م³/يوم',
        energyConsumption: '500 kWh/يوم + غاز',
        noiseLevel: '70 dB (ضمن الحدود)',
        wasteManagement: 'إعادة تدوير العجين الفائض، تخزيم النفايات',
        mitigationMeasures: 'فلاتر للدخان، عزل صوتي',
        greenMeasures: 'استخدام طاقة شمسية للتسخين مستقبلاً',
        impactAssessment: 'أثر بيئي منخفض',
        compliance: 'متوافق مع اشتراطات البلدية',
      },
      legalStudy: {
        legalForm: 'منشأة فردية',
        licenses: 'سجل تجاري، رخصة صناعية، شهادة صحية، رخصة بلدية',
        regulations: 'قانون الاستثمار، قانون الصناعة، اشتراطات الغذاء',
        contracts: 'عقد إيجار المحل، عقود توريد الدقيق',
        intellectualProperty: 'علامة تجارية مسجلة',
        taxObligations: 'ضريبة الدخل 15%، VAT 5%',
        insurance: 'تأمين على المعدات، تأمين ضد الحريق',
        governmentApprovals: 'وزارة الصناعة، البلدية، الهيئة العامة للمواصفات',
        complianceStatus: 'مكتمل',
      },
    },
  },
  {
    id: 'sample-laundry',
    nameAr: 'مصبغة ملابس (مشروع غير مجدي)',
    nameEn: 'Laundry Service (Non-Viable Project)',
    icon: '👔',
    descriptionAr: 'مصبغة ملابس صغيرة - مثال لمشروع غير مجدي لتعلم التحليل',
    descriptionEn: 'Small laundry service - example of non-viable project for learning',
    data: {
      name: 'مصبغة النظافة',
      description: 'مصبغة ملابس بحجم صغير مع استثمار مرتفع وإيرادات منخفضة',
      establishment: {
        projectName: 'مصبغة النظافة',
        projectType: 'خدمات',
        projectSector: 'خدمي',
        projectLocation: 'صنعاء',
        projectOwner: 'سالم أحمد',
        projectCapital: 80000000,
        projectDuration: 5,
        projectDescription: 'مصبغة ملابس بمعدات مستوردة بسعة 200 قطعة/يوم',
        projectGoals: 'تقديم خدمة مصبغة احترافية',
        projectJustification: 'حاجة المنطقة لخدمات مصبغة متخصصة',
      },
      marketStudy: {
        targetCustomers: 'الأسر، الفنادق، المطاعم',
        marketSize: 10000000,
        expectedShare: 5,
        growthRate: 3,
        productPrice: 500,
        competitors: 'المصابغ التقليدية (15 منافس)',
        competitiveAdvantage: 'معدات حديثة',
      },
      technicalStudy: {
        productionCapacity: '200 قطعة/يوم',
        productionVolume: 73000,
        productionCost: 30000000,
        laborRequired: 4,
        location: '150 م²',
        equipment: 'غسالات صناعية، مجففات، مكواة',
      },
      financialStudy: {
        initialInvestment: 75000000,
        fixedAssets: 60000000,
        workingCapital: 10000000,
        operatingCosts: 5000000,
        loans: 40000000,
        interestRate: 10,
        loanPeriod: 5,
        yearsData: [
          YEAR(1, 18000000, 15000000),
          YEAR(2, 20000000, 16000000),
          YEAR(3, 22000000, 17000000),
          YEAR(4, 24000000, 18000000),
          YEAR(5, 26000000, 19000000),
        ],
      },
      economicStudy: {
        discountRate: 15,
        riskAnalysis: 'مخاطر عالية - منافسة شديدة واستثمار كبير',
        sensitivity: 'حساسية عالية لحجم الإيرادات',
      },
    },
  },
  {
    id: 'sample-poultry',
    nameAr: 'مزرعة دواجن (مشروع متوازن)',
    nameEn: 'Poultry Farm (Balanced Project)',
    icon: '🐔',
    descriptionAr: 'مزرعة تسمين دواجن - مثال لمشروع متوازن يحتاج تحسينات',
    descriptionEn: 'Broiler poultry farm - example of balanced project needing improvements',
    data: {
      name: 'مزرعة الدواجن الذهبية',
      description: 'مزرعة تسمين دواجن بسعة 10000 طير/دورة (6 دورات/سنة)',
      establishment: {
        projectName: 'مزرعة الدواجن الذهبية',
        projectType: 'ثروة حيوانية',
        projectSector: 'زراعي',
        projectLocation: 'صنعاء - بني مطر',
        projectOwner: 'محمد الشميري',
        projectCapital: 60000000,
        projectDuration: 7,
        projectDescription: 'مزرعة تسمين دواجن بإنتاج 60,000 طير/سنة (6 دورات)',
        projectGoals: 'توفير لحوم الدواجن الطازجة محلياً وتقليل الاستيراد',
        projectJustification: 'طلب متزايد على لحوم الدواجن + دعم الأمن الغذائي',
      },
      marketStudy: {
        targetCustomers: 'تجار الجملة، محلات الجزارة، المطاعم',
        marketSize: 50000000,
        expectedShare: 8,
        growthRate: 10,
        productPrice: 1500,
        competitors: 'المزارع المحلية (10 مزارع) + الواردات',
        competitiveAdvantage: 'إنتاج طازج محلياً، تكلفة أقل من المستورد',
        segments: 'جملة (70%)، تجزئة (30%)',
      },
      technicalStudy: {
        productionCapacity: '10000 طير/دورة',
        productionVolume: 60000,
        productionCost: 35000000,
        laborRequired: 4,
        location: '500 م² - منطقة ريفية',
        utilities: 'ماء (5 م³/يوم)، كهرباء، تهوية',
        productionProcess: 'استلام كتاكيت → تربية 35 يوم → تسويق',
        rawMaterials: 'كتاكيت (60,000/سنة)، علف (180 طن)، أدوية بيطرية',
        equipment: 'حظائر، معالف أوتوماتيكية، مساقي، نظام تهوية، سخانات',
        qualityControl: 'متابعة بيطرية أسبوعية + تحصينات',
        maintenance: 'تنظيف وتطهير بين الدورات',
      },
      financialStudy: {
        initialInvestment: 50000000,
        fixedAssets: 35000000,
        workingCapital: 12000000,
        operatingCosts: 3000000,
        loans: 20000000,
        interestRate: 9,
        loanPeriod: 5,
        yearsData: [
          YEAR(1, 60000000, 42000000),
          YEAR(2, 66000000, 45000000),
          YEAR(3, 72000000, 48000000),
          YEAR(4, 79000000, 51000000),
          YEAR(5, 87000000, 54000000),
          YEAR(6, 95000000, 57000000),
          YEAR(7, 104000000, 60000000),
        ],
      },
      economicStudy: {
        discountRate: 12,
        riskAnalysis: 'مخاطر متوسطة - أمراض الطيور، تقلب أسعار العلف',
        sensitivity: 'حساسية عالية لتكلفة العلف (50% من التكاليف)',
      },
      socialStudy: {
        jobsCreated: 4,
        indirectJobs: 6,
        localEmployment: 100,
        genderRatio: 0,
        annualWages: 12000000,
        communityImpact: 'توفير لحم دواجن طازج، 4 فرص عمل مباشرة',
      },
      environmentalStudy: {
        airEmissions: 'روائح - تحتاج إدارة جيدة',
        waterUsage: '5 م³/يوم',
        wasteManagement: 'سماد عضوي من فضلات الدواجن',
        mitigationMeasures: 'تهوية جيدة، معالجة الفضلات',
      },
      legalStudy: {
        legalForm: 'منشأة فردية',
        licenses: 'رخصة زراعية، موافقة بيطرية، رخصة بلدية',
        complianceStatus: 'مكتمل',
      },
    },
  },
  {
    id: 'sample-dairy-factory',
    nameAr: 'مصنع ألبان متكامل (مشروع استراتيجي)',
    nameEn: 'Integrated Dairy Factory (Strategic)',
    icon: '🥛',
    descriptionAr: 'مصنع ألبان 5000 لتر/يوم - إنتاج حليب وزبادي وجبن، بديل للمستورد',
    descriptionEn: '5000 L/day dairy plant - milk, yogurt, cheese, replaces imports',
    data: {
      name: 'مصنع الألبان اليمني المتكامل',
      description: 'مصنع ألبان متكامل بطاقة 5000 لتر/يوم، ينتج حليب مبستر، زبادي، جبن، لبن. بديل للمستورد وداعم للأمن الغذائي.',
      establishment: {
        projectName: 'مصنع الألبان اليمني المتكامل',
        projectType: 'صناعة تحويلية غذائية',
        projectSector: 'صناعة - أغذية',
        projectLocation: 'ذمار - المنطقة الصناعية',
        projectOwner: 'شركة الألبان اليمنية',
        projectCapital: 450000000,
        projectDuration: 10,
        projectDescription: 'مصنع ألبان متكامل بطاقة 5000 لتر/يوم (1.8 مليون لتر/سنة). ينتج: حليب مبستر 60%، زبادي 25%، جبن 10%، لبن 5%. شراكة مع 50 مزارع ألبان في ذمار وإب.',
        projectGoals: '1. إنتاج 1.8 مليون لتر سنوياً. 2. توفير 25 فرصة عمل. 3. دعم 50 مزارع ألبان. 4. بديل للمستورد. 5. هامش ربح 35%.',
        projectJustification: 'اليمن يستورد 70% من الألبان. ذمار وإب منتجة للحليب الخام. تكلفة الإنتاج 64% من سعر البيع. هامش ربح 35% = 183 مليون ريال سنوياً. عائد استثنائي + دعم حكومي للأمن الغذائي.',
      },
      socialStudy: {
        jobsCreated: 25,
        indirectJobs: 100,
        localEmployment: 90,
        genderRatio: 30,
        foreignWorkers: 0,
        annualWages: 90000000,
        trainingPrograms: 'تدريب 25 عامل على إنتاج الألبان، سلامة الغذاء، تشغيل المعدات. شراكة مع مكتب الصناعة. دورات HACCP.',
        communityImpact: '25 وظيفة مباشرة + دعم 50 مزارع ألبان (100 وظيفة غير مباشرة). شراء 1.8 مليون لتر حليب سنوياً من المزارع المحلية. تحسين دخل المزارع.',
        developmentImpact: 'بديل لاستيراد 1.8 مليون لتر = توفير $1.2M نقد أجنبي. نقل تقنية صناعة الألبان. نموذج تكامل زراعي-صناعي.',
      },
      environmentalStudy: {
        airEmissions: 'انبعاثات منخفضة (مولد + سيارات). خطة طاقة شمسية 30kW.',
        waterUsage: '15000 م³/سنة (تنظيف + إنتاج). معالجة مياه صرف ثلاثية.',
        wasteManagement: '1. شرش اللبن (200 طن) يُباع كعلف. 2. عبوات PET قابلة للتدوير. 3. مياه صرف معالجة للري.',
        noiseLevel: '65 dB (ضمن الحدود)',
        energyConsumption: '250,000 kWh/سنة',
        mitigationMeasures: 'وحدة معالجة صرف + مرشحات هواء + عزل صوتي',
        compliance: 'HACCP + ISO 22000 + مواصفات خليجية',
        impactAssessment: 'إيجابي - حلقة وصل بين المزارع والسوق',
        greenMeasures: 'طاقة شمسية + تدوير العبوات + معالجة الصرف',
      },
      legalStudy: {
        legalForm: 'شركة ذات مسؤولية محدودة',
        licenses: '1. سجل تجاري. 2. رخصة صناعية. 3. شهادة HACCP. 4. موافقة هيئة المواصفات. 5. رخصة بلدية. 6. شهادة تصدير (مستقبلاً).',
        regulations: 'قانون الصناعة، قانون الغذاء، قانون حماية المستهلك، مواصفات الألبان الخليجية.',
        contracts: 'عقود مع 50 مزارع ألبان. عقد إدارة. عقد صيانة. عقود بيع مع 30 محلاً.',
        intellectualProperty: 'علامة "ألبان ذمار" مسجلة.',
        taxObligations: 'ضريبة دخل 15% + VAT 5% + إعفاء جمركي للمعدات الصناعية.',
        insurance: 'تأمين على المعدات + تأمين زراعي على الحليب + تأمين مسؤولية.',
        governmentApprovals: 'وزارة الصناعة، وزارة الصحة، الهيئة العامة للمواصفات، الغرفة التجارية.',
        complianceStatus: 'مكتمل.',
      },
      marketStudy: {
        targetCustomers: '1. محلات السوبر ماركت (40%). 2. البقالات (30%). 3. المطاعم والمخابز (15%). 4. المدارس (10%). 5. الجملة (5%).',
        marketSize: 30000000000,
        expectedShare: 6,
        growthRate: 8,
        productPrice: 280,
        competitors: 'ألبان مستوردة (70% من السوق)، مصانع محلية (3 مصانع). ميزتنا: طازج محلي + جودة + سعر منافس.',
        competitiveAdvantage: '1. طازج محلياً (نفس اليوم). 2. سلسلة تبريد كاملة. 3. شراكة مع 50 مزارع. 4. شهادة HACCP. 5. تنوع المنتجات. 6. دعم حكومي للأمن الغذائي.',
        pricingStrategy: 'سعر اللتر 280 ريال ($0.53) - أقل من المستورد بـ 25%. خصم 10% للجملة. أسعار خاصة للمدارس.',
        distribution: '1. شاحنات مبردة 12 نقطة توزيع. 2. وكلاء في 5 مدن. 3. بيع مباشر من المصنع. 4. تطبيق توصيل منزلي.',
        promotion: 'علامة "طازج اليوم". إعلانات محلية. عينات مجانية في المدارس. شهادات جودة ظاهرة على العبوة.',
        demandForecast: 'الطلب ينمو 8% سنوياً. استهلاك الفرد 25 لتر/سنة (منخفض عالمياً = فرصة نمو).',
        segments: 'سوبر ماركت (40%)، بقالات (30%)، مطاعم (15%)، مدارس (10%)، جملة (5%).',
        swot: 'القوة: محلي طازج + شراكات + جودة. الضعف: سلسلة تبريد مكلفة + قصر مدة الصلاحية. الفرص: نمو الطلب + تصدير + منتجات جديدة (آيس كريم). التهديدات: منافسة المستورد + تذبذب إمداد الحليب الخام.',
        productPrice: 280,
      },
      technicalStudy: {
        productionCapacity: '5000 لتر/يوم × 365 = 1.825 مليون لتر/سنة',
        productionVolume: 1825000,
        productionCost: 328000000,
        laborRequired: 25,
        location: 'ذمار - المنطقة الصناعية. 2000 م². قرب مناطق إنتاج الحليب (ذمار، إب). طرق معبدة + كهرباء + ماء.',
        utilities: 'كهرباء: شبكة + مولد 200kVA. ماء: بئر + شبكة. صرف: وحدة معالجة. اتصالات + إنترنت.',
        productionProcess: '1. استلام حليب من المزارع (مرتين يومياً). 2. فحص جودة (مختبر). 3. بسترة HTST (72°م/15ث). 4. تبريد 4°م. 5. فرز لخطوط (حليب، زبادي، جبن). 6. تعبئة أوتوماتيكية. 7. تخزين مبرد. 8. توزيع بشاحنات مبردة.',
        rawMaterials: '1. حليب طازج (1.8M لتر × 100 ر.ي). 2. عبوات PET (2M × 15 ر.ي). 3. ثقافات بكتيرية. 4. ملح للجبن. 5. منكهات. 6. مواد تنظيف ومعقمة.',
        equipment: '1. خزانات استلام 5000 لتر (3 وحدات). 2. مبستر HTST. 3. مبرد 2000 لتر. 4. وحدة تعبئة PET. 5. خط زبادي. 6. آلة جبن. 7. مختبر جودة. 8. شاحنة مبردة. 9. مولد 200kVA. 10. وحدة معالجة صرف.',
        machinery: 'خط إنتاج إيطالي/هندي. العمر الافتراضي 15 سنة. صيانة سنوية معتمدة.',
        qualityControl: '1. فحص الحليب الخام (دهون، بروتين، بكتريا). 2. رصد درجة الحرارة. 3. فحص منتظم للمنتج النهائي. 4. شهادة HACCP. 5. تتبع كل دفعة.',
        maintenance: 'صيانة وقائية شهرية + يومية للنظافة + سنوية للمعدات الكبرى.',
      },
      financialStudy: {
        initialInvestment: 420000000,
        fixedAssets: 290000000,
        workingCapital: 110000000,
        operatingCosts: 20000000,
        loans: 250000000,
        interestRate: 7,
        loanPeriod: 7,
        yearsData: [
          YEAR(1, 380000000, 320000000),
          YEAR(2, 460000000, 340000000),
          YEAR(3, 510000000, 350000000),
          YEAR(4, 540000000, 360000000),
          YEAR(5, 570000000, 370000000),
          YEAR(6, 600000000, 380000000),
          YEAR(7, 630000000, 390000000),
          YEAR(8, 660000000, 400000000),
          YEAR(9, 690000000, 410000000),
          YEAR(10, 720000000, 420000000),
        ],
      },
      economicStudy: {
        discountRate: 11,
        riskAnalysis: 'مخاطر منخفضة-متوسط: 1. تذبذب إمداد الحليب الخام (30%). 2. سلسلة التبريد (25%). 3. منافسة المستورد (35%). 4. تغير أسعار الوقود (20%). خطة: عقود طويلة + تنويع موردين + تأمين.',
        sensitivity: '1. الإنتاج ±10% = ∓25% NPV. 2. سعر البيع ±10% = ±35% NPV. 3. تكلفة الحليب الخام ±10% = ∓20% NPV. نقطة التعادل: 3500 لتر/يوم.',
        economicImpact: 'توفير $1.2M نقد أجنبي سنوياً. 125 وظيفة (مباشر + غير مباشر). دعم 50 مزارع. أثر مضاعف 3×.',
        costBenefit: 'B/C = 1.6. تكلفة اللتر المنتج 180 ر.ي، سعر 280 ر.ي = هامش 36%.',
      },
      riskRegister: [
        { id: 'd1', name: 'تذبذب إمداد الحليب الخام', category: 'تشغيلي', probability: 3, impact: 4, mitigation: 'عقود طويلة + 50 مزارع + تنويع المناطق', status: 'mitigated' },
        { id: 'd2', name: 'انقطاع سلسلة التبريد', category: 'تشغيلي', probability: 2, impact: 5, mitigation: 'مولد احتياطي + خزانات تخزين طوارئ', status: 'mitigated' },
        { id: 'd3', name: 'منافسة المستورد المدعوم', category: 'سوقي', probability: 4, impact: 3, mitigation: 'جودة + طزاجة محلية + تسويق', status: 'open' },
      ],
      swotAnalysis: {
        strengths: [
          { id: 's1', text: 'محلي طازج بنفس اليوم' },
          { id: 's2', text: 'شراكة مع 50 مزارع ألبان محليين' },
          { id: 's3', text: 'شهادة HACCP وجودة عالية' },
          { id: 's4', text: 'تنوع المنتجات (4 أصناف)' },
        ],
        weaknesses: [
          { id: 'w1', text: 'سلسلة تبريد مكلفة' },
          { id: 'w2', text: 'قصر مدة صلاحية المنتج' },
          { id: 'w3', text: 'استثمار كبير 420 مليون' },
        ],
        opportunities: [
          { id: 'o1', text: 'نمو الطلب 8% سنوياً' },
          { id: 'o2', text: 'تصدير للخليج (شهادة HACCP)' },
          { id: 'o3', text: 'إضافة منتجات (آيس كريم، زبدة)' },
          { id: 'o4', text: 'توسع لـ 10000 لتر/يوم' },
        ],
        threats: [
          { id: 't1', text: 'منافسة المستورد المدعوم' },
          { id: 't2', text: 'تذبذب إمداد الحليب الخام' },
          { id: 't3', text: 'تغير أسعار الوقود' },
        ],
      },
      projectPhases: [
        { id: 'dp1', name: 'التراخيص والاستملاك', start: '2026-04-01', end: '2026-07-31', progress: 100, status: 'completed' },
        { id: 'dp2', name: 'البناء والإنشاءات', start: '2026-08-01', end: '2027-01-31', progress: 80, status: 'in-progress' },
        { id: 'dp3', name: 'تركيب المعدات', start: '2027-02-01', end: '2027-04-30', progress: 50, status: 'in-progress' },
        { id: 'dp4', name: 'تراخيص تشغيل + HACCP', start: '2027-05-01', end: '2027-06-30', progress: 20, status: 'in-progress' },
        { id: 'dp5', name: 'التشغيل التجريبي', start: '2027-07-01', end: '2027-09-30', progress: 0, status: 'not-started' },
        { id: 'dp6', name: 'التشغيل التجاري الكامل', start: '2027-10-01', end: '2037-09-30', progress: 0, status: 'not-started' },
      ],
    },
  },
  {
    id: 'sample-juice-factory',
    nameAr: 'مصنع عصائر وتعبئة (مشروع ربحي عالٍ)',
    nameEn: 'Juice & Beverage Factory (High Profit)',
    icon: '🧃',
    descriptionAr: 'مصنع عصائر 10000 لتر/يوم - هامش ربح 45%، يستخدم الفواكه المحلية',
    descriptionEn: '10,000 L/day juice factory - 45% margin, uses local fruits',
    data: {
      name: 'مصنع عصائر اليمن الطبيعية',
      description: 'مصنع عصائر فواكه طبيعية بطاقة 10000 لتر/يوم (3 مليون لتر/سنة). يستخدم مانجو، برتقال، فراولة، عنب محلي. هامش ربح 45%.',
      establishment: {
        projectName: 'مصنع عصائر اليمن الطبيعية',
        projectType: 'صناعة تحويلية - مشروبات',
        projectSector: 'صناعة - مشروبات',
        projectLocation: 'الحديدة - المنطقة الصناعية',
        projectOwner: 'شركة ثمار اليمن للعصائر',
        projectCapital: 350000000,
        projectDuration: 10,
        projectDescription: 'مصنع عصائر فواكه طبيعية بطاقة 10000 لتر/يوم (3 مليون لتر/سنة). أصناف: مانجو، برتقال، فراولة، عنب، مشكل. يستخدم فواكه محلية طازجة. تعبئة Tetra Pak + PET.',
        projectGoals: '1. إنتاج 3 مليون لتر سنوياً. 2. تصدير 30% للسعودية والإمارات. 3. 18 فرصة عمل. 4. هامش ربح 45% = 300 مليون ريال سنوياً. 5. دعم مزارعي الفواكه.',
        projectJustification: 'الطلب على العصائر الطبيعية ينمو 12% سنوياً. اليمن غني بالفواكه (مانجو الحديدة، عنب صنعاء). هامش ربح عالٍ 45%. تكلفة اللتر 120 ريال، سعر 220 ريال. تصدير مربح جداً.',
      },
      socialStudy: {
        jobsCreated: 18,
        indirectJobs: 50,
        localEmployment: 90,
        genderRatio: 25,
        foreignWorkers: 0,
        annualWages: 65000000,
        trainingPrograms: 'تدريب 18 عامل على إنتاج العصائر، فحص الجودة، تشغيل خطوط التعبئة. دورات HACCP.',
        communityImpact: '18 وظيفة مباشرة + دعم 30 مزارع فواكه (50 وظيفة غير مباشرة). شراء 5000 طن فواكه سنوياً.',
        developmentImpact: 'تصدير 900 ألف لتر = $630,000 نقد أجنبي. نموذج لصناعة قيمة مضافة زراعية.',
      },
      environmentalStudy: {
        airEmissions: 'منخفضة (مولد + سيارات).',
        waterUsage: '10000 م³/سنة (تنظيف + إنتاج). معالجة صرف.',
        wasteManagement: '1. تفل الفواكه (800 طن) كعلف للحيوانات. 2. عبوات PET للتدوير. 3. صرف معالج.',
        noiseLevel: '60 dB',
        energyConsumption: '180,000 kWh/سنة',
        mitigationMeasures: 'مرشحات + عزل صوتي + وحدة معالجة صرف',
        compliance: 'HACCP + ISO 22000 + FDA (للتصدير)',
        impactAssessment: 'إيجابي - حلقة وصل زراعي-صناعي + تقليل هدر الفواكه',
        greenMeasures: 'تدوير التفل + عبوات قابلة للتدوير + طاقة شمسية مستقبلاً',
      },
      legalStudy: {
        legalForm: 'شركة ذات مسؤولية محدودة',
        licenses: '1. سجل تجاري. 2. رخصة صناعية. 3. HACCP. 4. ISO 22000. 5. FDA للتصدير. 6. موافقة هيئة المواصفات.',
        regulations: 'قانون الصناعة، قانون الغذاء، معايير المشروبات الخليجية، FDA الأمريكية.',
        contracts: 'عقود مع 30 مزارع فواكه. عقد صيانة. عقود تصدير مع 3 شركات. عقود جملة مع سوبر ماركت.',
        taxObligations: 'ضريبة دخل 15% + VAT 5% + إعفاء تصدير + إعفاء جمركي للمعدات.',
        insurance: 'تأمين مصنع + تأمين بضائع + تأمين مسؤولية.',
        governmentApprovals: 'وزارة الصناعة، الصحة، المواصفات، الجمارك.',
        complianceStatus: 'مكتمل - جميع الشهادات جاهزة.',
      },
      marketStudy: {
        targetCustomers: '1. سوبر ماركت (35%). 2. بقالات (25%). 3. مطاعم وكافيهات (15%). 4. تصدير (30%).',
        marketSize: 25000000000,
        expectedShare: 12,
        growthRate: 12,
        productPrice: 220,
        competitors: 'عصائر مستوردة (Tropicana، Almarai)، مصانع محلية (3). ميزتنا: طبيعي محلي 100% + فواكه يمنية + سعر منافس.',
        competitiveAdvantage: '1. طبيعي 100% بدون مواد حافظة. 2. فواكه يمنية فاخرة (مانجو الحديدة، عنب صنعاء). 3. هامش ربح عالٍ 45%. 4. تكلفة منخفضة (مواد خام محلية). 5. علامة "صنع في اليمن".',
        pricingStrategy: 'سعر اللتر 220 ريال ($0.42) - أقل من المستورد بـ 30%. سعر التصدير $0.65/لتر. خصم جملة 15%.',
        distribution: '1. شاحنات توزيع 8 مدن. 2. وكلاء تصدير للحديدة وجدة. 3. تطبيق توصيل. 4. بيع مباشر للمصنع.',
        promotion: 'علامة "طبيعي 100%". إعلانات تلفزيونية. عينات في المدارس. عروض موسمية. شهادات جودة FDA.',
        demandForecast: 'الطلب ينمو 12% سنوياً. استهلاك الفرد 8 لتر (منخفض = فرصة نمو). السوق الخليجي كبير.',
        segments: 'سوبر ماركت (35%)، بقالات (25%)، مطاعم (15%)، تصدير (30%).',
        swot: 'القوة: فواكه محلية فاخرة + طبيعي + هامش 45%. الضعف: موسمية بعض الفواكه + استثمار كبير. الفرص: تصدير خليجي + منتجات جديدة (عصائر مركزة) + شراكات. التهديدات: منافسة المستورد + موسمية + صعوبة شحن.',
        productPrice: 220,
      },
      technicalStudy: {
        productionCapacity: '10000 لتر/يوم × 300 يوم = 3 مليون لتر/سنة',
        productionVolume: 3000000,
        productionCost: 360000000,
        laborRequired: 18,
        location: 'الحديدة - المنطقة الصناعية. 1500 م². قرب ميناء الحديدة (سهولة التصدير). قرب مزارع المانجو.',
        utilities: 'كهرباء: شبكة + مولد 150kVA. ماء: بئر + شبكة. صرف: وحدة معالجة. إنترنت + تبريد.',
        productionProcess: '1. استلام فواكه من المزارع. 2. غسيل وتعقيم. 3. عصر (خط 5 طن/ساعة). 4. فلترة. 5. بسترة (90°م). 6. إضافة سكر/ماء (حسب الصنف). 7. تعبئة Tetra Pak أو PET. 8. تخزين. 9. توزيع.',
        rawMaterials: '1. مانجو (1500 طن × 800 ر.ي). 2. برتقال (1000 طن). 3. فراولة (300 طن). 4. عنب (500 طن). 5. سكر (200 طن). 6. عبوات Tetra Pak (3M × 60 ر.ي). 7. مواد تنظيف.',
        equipment: '1. خط عصر 5 طن/ساعة. 2. مبستر أنبوبي. 3. آلة تعبئة Tetra Pak. 4. آلة تعبئة PET. 5. مختبر جودة. 6. مبرد 5000 لتر. 7. خط تغليف. 8. مولد 150kVA. 9. شاحنة توزيع. 10. وحدة معالجة صرف.',
        machinery: 'خط إنتاج ألماني/إيطالي. العمر 15 سنة. صيانة معتمدة.',
        qualityControl: '1. فحص الفواكه (نضج، سكر). 2. رصد الإنتاج. 3. فحص نهائي (pH، سكر، بكتريا). 4. شهادة HACCP. 5. عينة لكل دفعة.',
        maintenance: 'صيانة شهرية + يومية للنظافة + سنوية كبرى.',
      },
      financialStudy: {
        initialInvestment: 320000000,
        fixedAssets: 220000000,
        workingCapital: 85000000,
        operatingCosts: 15000000,
        loans: 180000000,
        interestRate: 7,
        loanPeriod: 7,
        yearsData: [
          YEAR(1, 450000000, 360000000),
          YEAR(2, 540000000, 380000000),
          YEAR(3, 600000000, 395000000),
          YEAR(4, 630000000, 405000000),
          YEAR(5, 660000000, 415000000),
          YEAR(6, 690000000, 425000000),
          YEAR(7, 720000000, 435000000),
          YEAR(8, 750000000, 445000000),
          YEAR(9, 780000000, 455000000),
          YEAR(10, 810000000, 465000000),
        ],
      },
      economicStudy: {
        discountRate: 12,
        riskAnalysis: 'مخاطر متوسطة: 1. موسمية الفواكه (35%). 2. صعوبة التصدير (30%). 3. منافسة المستورد (25%). 4. صعوبة التعبئة Tetra Pak (20%). خطة: تنويع الفواكه + تجميد + عقود تصدير + PET احتياطي.',
        sensitivity: '1. الإنتاج ±10% = ∓30% NPV. 2. سعر البيع ±10% = ±40% NPV. 3. تكلفة الفواكه ±10% = ∓25% NPV. نقطة التعادل: 6500 لتر/يوم.',
        economicImpact: 'تصدير $630,000 نقد أجنبي. 68 وظيفة (مباشر + غير مباشر). دعم 30 مزارع. أثر مضاعف 3.5×.',
        costBenefit: 'B/C = 1.8. تكلفة اللتر 120 ر.ي، سعر 220 ر.ي = هامش 45%.',
      },
      riskRegister: [
        { id: 'j1', name: 'موسمية الفواكه', category: 'تشغيلي', probability: 4, impact: 3, mitigation: 'تجميد + تنويع + تخزين مركز', status: 'mitigated' },
        { id: 'j2', name: 'صعوبة التصدير والشحن', category: 'سياسي', probability: 3, impact: 4, mitigation: 'تنويع موانئ + شحن بري + شركاء متعددون', status: 'open' },
        { id: 'j3', name: 'منافسة المستورد', category: 'سوقي', probability: 4, impact: 3, mitigation: 'طبيعي 100% + سعر منافس + علامة محلية', status: 'open' },
      ],
      swotAnalysis: {
        strengths: [
          { id: 's1', text: 'فواكه يمنية فاخرة (مانجو، عنب)' },
          { id: 's2', text: 'طبيعي 100% بدون مواد حافظة' },
          { id: 's3', text: 'هامش ربح عالٍ 45%' },
          { id: 's4', text: 'قرب الميناء للتصدير' },
        ],
        weaknesses: [
          { id: 'w1', text: 'موسمية الفواكه' },
          { id: 'w2', text: 'استثمار كبير 320 مليون' },
          { id: 'w3', text: 'اعتماد على استيراد عبوات Tetra Pak' },
        ],
        opportunities: [
          { id: 'o1', text: 'نمو الطلب 12% سنوياً' },
          { id: 'o2', text: 'تصدير للسعودية والإمارات' },
          { id: 'o3', text: 'عصائر مركزة (تركيز أعلى)' },
          { id: 'o4', text: 'مشروبات طاقة وعضوية' },
        ],
        threats: [
          { id: 't1', text: 'منافسة المستورد القوية' },
          { id: 't2', text: 'صعوبة الشحن البحري' },
          { id: 't3', text: 'موسمية بعض الفواكه' },
        ],
      },
      projectPhases: [
        { id: 'jp1', name: 'التراخيص والاستملاك', start: '2026-04-01', end: '2026-07-31', progress: 100, status: 'completed' },
        { id: 'jp2', name: 'البناء والإنشاءات', start: '2026-08-01', end: '2026-12-31', progress: 85, status: 'in-progress' },
        { id: 'jp3', name: 'تركيب خط الإنتاج', start: '2027-01-01', end: '2027-03-31', progress: 60, status: 'in-progress' },
        { id: 'jp4', name: 'تراخيص HACCP + FDA', start: '2027-04-01', end: '2027-05-31', progress: 30, status: 'in-progress' },
        { id: 'jp5', name: 'تشغيل تجريبي', start: '2027-06-01', end: '2027-08-31', progress: 0, status: 'not-started' },
        { id: 'jp6', name: 'إنتاج تجاري + تصدير', start: '2027-09-01', end: '2037-08-31', progress: 0, status: 'not-started' },
      ],
    },
  },
  {
    id: 'sample-coffee-farm',
    nameAr: 'مزرعة بُن يمني - حراز (مشروع تصديري فاخر)',
    nameEn: 'Yemeni Coffee Farm - Haraz (Premium Export)',
    icon: '☕',
    descriptionAr: 'مزرعة بُن عربي 20 هكتار في جبال حراز - المشروع الأعلى ربحية (تصدير بـ $9/كغ)',
    descriptionEn: '20-hectare Arabica coffee farm in Haraz mountains - highest profitability (export at $9/kg)',
    data: {
      name: 'مزرعة بُن حراز الفاخرة - 20 هكتار',
      description: 'مزرعة بُن عربي تخصصي على ارتفاع 1800م في جبال حراز، إنتاج 16 طن بُن مختص سنوياً بسعر تصدير $9/كغ',
      establishment: {
        projectName: 'مزرعة بُن حراز الفاخرة',
        projectType: 'زراعة بُن تخصصي',
        projectSector: 'زراعي - محاصيل نقدية',
        projectLocation: 'حراز - محافظة صنعاء (ارتفاع 1800م)',
        projectOwner: 'تعاونية بُن حراز',
        projectCapital: 90000000,
        projectDuration: 10,
        projectStartDate: '2026-04-01',
        projectDescription: 'مزرعة بُن عربي 20 هكتار على مدرجات جبلية، تعتمد على الأمطار والري التكميلي. صنف حرازي أصلي. إنتاج 16 طن سنوياً (800 كغ/هكتار). يستهدف سوق البُن المختص العالمي بسعر $9/كغ.',
        projectGoals: '1. إنتاج 16 طن بُن مختص سنوياً. 2. تصدير 80% للأسواق الفاخرة (السعودية، الإمارات، اليابان، أمريكا). 3. الحفاظ على أصالة بُن حراز. 4. توفير 25 فرصة عمل مستدامة. 5. نقل المعرفة لـ 50 مزارعاً محلياً.',
        projectJustification: 'بُن اليمن عالمي السمعة - سعر الكيلو $8-11 للمختص. اليمن يصدر 5500-8800 طن سنوياً. حراز من أشهر مناطق البُن. تكلفة الإنتاج 41-45% من الإيراد. كل هكتار يولّد $7200 سنوياً (أعلى من القمح 12×).',
      },
      socialStudy: {
        jobsCreated: 12,
        indirectJobs: 25,
        localEmployment: 100,
        genderRatio: 25,
        foreignWorkers: 0,
        annualWages: 36000000,
        trainingPrograms: 'تدريب 50 مزارعاً على: القطف الانتقائي، التجفيف الشمسي، التخمير، التصنيف. شراكة مع مركز بُن اليمن.',
        communityImpact: '12 وظيفة دائمة + 50 موسمية (القطف). دعم 50 مزارعاً بشراء المحصول بأسعار عادلة. تأسيس تعاونية. تمديد طريق 3كم. مدرسة ابتدائية للمزرعة.',
        developmentImpact: 'نقل معرفة زراعة البُن المختص. رفع دخل المزارعين من $2/كغ إلى $5/كغ. نموذج تكراري في 5 مديريات. صادرات تدر $144,000 نقد أجنبي سنوياً.',
      },
      environmentalStudy: {
        airEmissions: 'ممتص للكربون (أشجار بُن + ظلال). كل هكتار يخزن 10 طن CO2.',
        waterUsage: 'الري التكميلي 800 م³/هكتار (الأساس أمطار). خزان تجميع 200 م³. كل هكتار = 16,000 م³/سنة.',
        wasteManagement: 'قشرة البُن (20 طن) تستخدم كسماد عضوي. قشور وأوراق كعلف.',
        noiseLevel: 'ضوضاء منخفضة (لا معدات ثقيلة).',
        energyConsumption: '5,000 kWh/سنة (تجفيف وتجهيز) + طاقة شمسية 5kW.',
        mitigationMeasures: 'زراعة أشجار ظلال (جوز، موز). حواجز مائية. مدرعات تربة.',
        compliance: 'معايير SCA (Specialty Coffee Association). شهادة عضوي قيد الإعداد.',
        impactAssessment: 'إيجابي صافي - حفظ التنوع الحيوي + امتصاص الكربون + منع الانجراف.',
        greenMeasures: 'تجفيف شمسي 100%. سماد عضوي ذاتي. طاقة شمسية. زراعة ظلال.',
      },
      legalStudy: {
        legalForm: 'تعاونية زراعية متعددة الأغراض',
        licenses: '1. سجل تجاري. 2. رخصة زراعية. 3. شهادة تصدير من هيئة المواصفات. 4. تصريح جمركي. 5. شهادة SCA. 6. شهادة عضوي (قيد الإعداد).',
        regulations: 'قانون الزراعة، قانون التعاونيات، قانون الجمارك، معايير القهوة العالمية.',
        contracts: '1. عقود مع 5 مصدّرين. 2. عقد مع شركة شحن. 3. عقود شراء مع مزارعين. 4. عقد إدارة مع التعاونية.',
        intellectualProperty: 'علامة "بُن حراز" مسجلة. شهادة المنشأ.',
        taxObligations: 'إعفاء زراعي كامل وفق القانون. ضريبة تصدير 0% على البُن الخام.',
        insurance: 'تأمين زراعي. تأمين على المخزون.',
        governmentApprovals: 'وزارة الزراعة، الجمارك، الغرفة التجارية.',
        complianceStatus: 'مكتمل - جميع الشهادات الجاهزة.',
      },
      marketStudy: {
        targetCustomers: '1. مصدّرون متخصصون (60%). 2. محامص فاخرة محلية (20%). 3. فنادق ومطاعم 5 نجوم (10%). 4. بيع مباشر أونلاين (10%).',
        marketSize: 80000000000,
        expectedShare: 0.2,
        growthRate: 15,
        productPrice: 9000000,
        competitors: 'بُن إثيوبي، كولومبي، كينيا. بُن يمني مناطق أخرى (بني مطر، إب). ميزتنا: جودة حراز الفريدة + شهادة المنشأ + التصنيف اليدوي.',
        competitiveAdvantage: '1. بُن حراز صنف أصلي نادر (Sanaani). 2. ارتفاع 1800م يعطي نكهة فريدة. 3. قطف انتقائي + تجفيف شمسي بطيء. 4. تصنيف يدوي دقيق. 5. سلسلة توريد قصيرة. 6. شهادة SCA درجة 84+.',
        pricingStrategy: 'سعر التصدير $9/كغ (مختص). البيع بالجملة $7/كغ. البيع المباشر للمحامص $11/كغ. عينات مجانية للشركات.',
        distribution: '1. تصدير جواً (صنعاء → جدة/دبي). 2. تخزين مؤقت بصنعاء (مخزن مكيف). 3. تعبئة 30كغ + أكياس 1كغ فاخرة. 4. شحن متعاون مع شركات أخرى لتقليل التكلفة.',
        promotion: '1. المشاركة في معارض القهوة (دبي، سياتل). 2. علاقات مع محامص متخصصة. 3. تسويق رقمي (إنستغرام). 4. شهادات SCA. 5. قصة الإنتاج والمنطقة.',
        demandForecast: 'سوق البُن المختص ينمو 15% سنوياً عالمياً. الطلب على بُن اليمن يتجاوز العرض بـ 3×. فجوة كبيرة للاستثمار.',
        segments: 'مصدرون (60%)، محامص محلية (20%)، فنادق (10%)، أونلاين (10%).',
        swot: 'القوة: صنف أصلي + موقع فريد + جودة SCA. الضعف: حجم صغير (16 طن) + تسويق محدود. الفرص: نمو سوق المختص 15% + شهادة عضوي + توسع لـ 50 هكتار. التهديدات: تغير مناخي + حرب + منافسة إثيوبية.',
        productPrice: 9000000,
      },
      technicalStudy: {
        productionCapacity: '20 هكتار × 800 كغ/هكتار = 16,000 كغ بُن مختص سنوياً',
        productionVolume: 16000,
        productionCost: 76000000,
        laborRequired: 12,
        location: 'حراز - ارتفاع 1800م. تربة بركانية خصبة. أمطار 800-1200 مم. مدرعات جبلية.',
        utilities: 'مياه: خزانات تجميع + ري تكميلي بالتنقيط. كهرباء: شبكة + شمسي 5kW. طرق: وصول معبد جزئي.',
        productionProcess: '1. زراعة الشتلات (مارس-أبريل). 2. العناية 3 سنوات (تقليم، تسميد عضوي). 3. الإنتاج من سنة 3 ويستمر 30 سنة. 4. القطف الانتقائي (نوفمبر-فبراير). 5. التجفيف الشمسي 15-20 يوم. 6. التقشير. 7. التصنيف اليدوي. 8. التخزين في أكياس Jute.',
        rawMaterials: '1. شتلات بُن حرازي (6500 شتلة × 1500 ر.ي). 2. سماد عضوي (50 طن × 5000 ر.ي). 3. أكياس Jute (500 × 2000 ر.ي). 4. معدات قطف. 5. صيانة مدرعات.',
        equipment: '1. نظام ري بالتنقيط تكميلي. 2. خزانات تجميع مياه (3 × 50 م³). 3. أحواض تجفيف شمسي (200 م²). 4. آلة تقشير يدوية + كهربائية. 5. غرفة تخزين مكيفة. 6. معدات تصنيف (شبكات). 7. ميزان دقيق. 8. طاقة شمسية 5kW.',
        machinery: 'ماكينة تقشير (Huller) + فاصل الجاذبية + جهاز قياس الرطوبة.',
        qualityControl: '1. فحص كل دفعة بجهاز SCA. 2. عينة Cupping لكل 100كغ. 3. تصنيف حسب الحجم والعيوب. 4. شهادة جودة من مختبر معتمد. 5. تتبع كل دفعة (Lot tracking).',
        maintenance: 'صيانة دورية للمعدات. تجديد المدرعات سنوياً. تقليم الأشجار سنوياً.',
      },
      financialStudy: {
        initialInvestment: 75000000,
        fixedAssets: 50000000,
        workingCapital: 20000000,
        operatingCosts: 5000000,
        loans: 40000000,
        interestRate: 6,
        loanPeriod: 7,
        yearsData: [
          YEAR(1, 0, 25000000),         // سنة التأسيس - لا إنتاج
          YEAR(2, 0, 20000000),         // نمو الأشجار
          YEAR(3, 45000000, 35000000),  // أول إنتاج 50%
          YEAR(4, 90000000, 50000000),  // إنتاج كامل
          YEAR(5, 108000000, 55000000),
          YEAR(6, 126000000, 60000000),
          YEAR(7, 144000000, 65000000),
          YEAR(8, 162000000, 70000000),
          YEAR(9, 180000000, 75000000),
          YEAR(10, 198000000, 80000000),
        ],
      },
      economicStudy: {
        discountRate: 12,
        riskAnalysis: 'مخاطر متوسطة-عالية: 1. مناخية (صقيع، أمطار غير منتظمة) - 25%. 2. تسويقية (صعوبة التصدير) - 30%. 3. آفات (حشرة القهوة) - 20%. 4. سعر الصرف - 35%. خطة التخفيف: شهادات جودة + تنويع مصادر التصدير + تأمين + عقود طويلة الأمد.',
        sensitivity: 'تحليل الحساسية: 1. سعر التصدير ±$2 = ±35% NPV. 2. الإنتاجية ±20% = ±30% NPV. 3. تكلفة العمالة ±20% = ±8% NPV. 4. معدل الخصم ±2% = ±22% NPV. النقطة الحرجة: سعر $5/كغ.',
        economicImpact: 'توفير نقد أجنبي $144,000 سنوياً. دعم 25 أسرة. نقل معرفة لـ 50 مزارعاً. صادرات فاخرة ترفع سمعة اليمن. أثر مضاعف 3× = $432,000.',
        costBenefit: 'B/C Ratio = 1.8. تكلفة الكيلو المنتج $4.75 مقابل سعر $9 = هامش ربح 89%.',
      },
      riskRegister: [
        { id: 'c1', name: 'الصقيع في الشتاء', category: 'بيئي', probability: 3, impact: 4, mitigation: 'زراعة ظلال + رش مائي + اختيار مواقع محمية', status: 'open' },
        { id: 'c2', name: 'صعوبة التصدير والحصار', category: 'سياسي', probability: 4, impact: 4, mitigation: 'تنويع موانئ التصدير + شحن جوي + شركاء متعددون', status: 'open' },
        { id: 'c3', name: 'حشرة ساق القهوة', category: 'بيئي', probability: 3, impact: 3, mitigation: 'فخاخ فيرومونية + رصد دوري + معالجة فورية', status: 'mitigated' },
        { id: 'c4', name: 'تذبذب أسعار الصرف', category: 'اقتصادي', probability: 4, impact: 3, mitigation: 'عقود بأسعار ثابتة بالدولار + تنويع العملات', status: 'open' },
      ],
      swotAnalysis: {
        strengths: [
          { id: 's1', text: 'صنف بُن حرازي أصلي بنكهة فريدة عالمياً' },
          { id: 's2', text: 'ارتفاع 1800م يعطي نكهة استثنائية (SCA 84+)' },
          { id: 's3', text: 'تكلفة إنتاج منخفضة (41% من الإيراد)' },
          { id: 's4', text: 'هامش ربح 89% (سعر $9 / تكلفة $4.75)' },
        ],
        weaknesses: [
          { id: 'w1', text: 'بداية الإنتاج تتأخر 3 سنوات (لا عائد فوري)' },
          { id: 'w2', text: 'حجم صغير (16 طن) يصعب التفاوض' },
          { id: 'w3', text: 'اعتماد كلي على التصدير' },
        ],
        opportunities: [
          { id: 'o1', text: 'نمو سوق البُن المختص 15% سنوياً' },
          { id: 'o2', text: 'شهادة عضوي ترفع السعر 30%' },
          { id: 'o3', text: 'توسع لـ 50 هكتار (مضاعفة 2.5×)' },
          { id: 'o4', text: 'بيعه مباشرة عبر الإنترنت بـ $20/كغ' },
        ],
        threats: [
          { id: 't1', text: 'صعوبات التصدير والحرب' },
          { id: 't2', text: 'تغير مناخي يؤثر على الإنتاجية' },
          { id: 't3', text: 'منافسة بُن إثيوبي المدعوم' },
        ],
      },
      projectPhases: [
        { id: 'cp1', name: 'التراخيص والتعاونية', start: '2026-04-01', end: '2026-06-30', progress: 100, status: 'completed' },
        { id: 'cp2', name: 'إعداد المدرعات والبنية', start: '2026-07-01', end: '2026-10-31', progress: 90, status: 'in-progress' },
        { id: 'cp3', name: 'زراعة الشتلات', start: '2026-11-01', end: '2027-03-31', progress: 70, status: 'in-progress' },
        { id: 'cp4', name: 'العناية 3 سنوات', start: '2027-04-01', end: '2030-03-31', progress: 20, status: 'in-progress' },
        { id: 'cp5', name: 'أول إنتاج (50%)', start: '2030-04-01', end: '2031-03-31', progress: 0, status: 'not-started' },
        { id: 'cp6', name: 'إنتاج كامل + تصدير', start: '2031-04-01', end: '2036-03-31', progress: 0, status: 'not-started' },
      ],
    },
  },
  {
    id: 'sample-mango-farm',
    nameAr: 'مزرعة مانجو تصديرية - الحديدة (مشروع سريع العائد)',
    nameEn: 'Export Mango Farm - Hodeidah (Fast Returns)',
    icon: '🥭',
    descriptionAr: 'مزرعة مانجو 20 هكتار بالري بالتنقيط - إنتاج سريع من السنة 3، تصدير للخليج',
    descriptionEn: '20-hectare drip-irrigated mango farm - production from year 3, exports to Gulf',
    data: {
      name: 'مزرعة مانجو الحديدة التصديرية - 20 هكتار',
      description: 'مزرعة مانجو 20 هكتار بنظام الري بالتنقيط في الحديدة، إنتاج 300 طن سنوياً، تصدير 60% للخليج',
      establishment: {
        projectName: 'مزرعة مانجو الحديدة',
        projectType: 'زراعة فاكهة استوائية',
        projectSector: 'زراعي - فواكه',
        projectLocation: 'الحديدة - سهل تهامة',
        projectOwner: 'شركة ثمار اليمن',
        projectCapital: 120000000,
        projectDuration: 10,
        projectDescription: 'مزرعة مانجو 20 هكتار بصنف الجلفور والبامبا. إنتاج يبدأ سنة 3 (50%) ويصل 300 طن سنوياً سنة 5. تصدير 60% للسعودية والإمارات.',
        projectGoals: '1. إنتاج 300 طن مانجو سنوياً. 2. تصدير 180 طن ($1500/طن). 3. 10 فرص عمل. 4. نموذج لتفعيل أراضي تهامة.',
        projectJustification: 'مانجو الحديدة مشهور بالجودة. السعودية تستورد 200,000 طن سنوياً. كل هكتار ينتج 15 طن. ري تنقيط يوفر 40% من المياه. عائد سريع من سنة 3.',
      },
      socialStudy: {
        jobsCreated: 10,
        indirectJobs: 20,
        localEmployment: 95,
        genderRatio: 15,
        foreignWorkers: 0,
        annualWages: 30000000,
        trainingPrograms: 'تدريب على: التقليم، التسميد، الحصاد، الفرز، التعبئة. دورات في التصدير والجودة.',
        communityImpact: '10 وظائف دائمة + 40 موسمية (حصاد). تطوير طرق. دعم 30 أسرة. تعاونية تصدير محلية.',
        developmentImpact: 'تنشيط اقتصاد تهامة. تصدير يدر $270,000 نقد أجنبي. نموذج تكراري في 10 مزارع.',
      },
      environmentalStudy: {
        airEmissions: 'ممتص CO2 (10 طن/هكتار/سنة). انبعاثات نقل منخفضة.',
        waterUsage: 'الري بالتنقيط 6000 م³/هكتار = 120,000 م³ سنوياً (توفير 50% مقارنة بالغمر).',
        wasteManagement: 'أوراق وأغصان كسماد. ثمار تالفة كعلف.',
        noiseLevel: 'منخفض.',
        energyConsumption: '15,000 kWh/سنة (مضخات). خطة شمسي 10kW.',
        mitigationMeasures: 'أشجار مصدات. سماد عضوي 40%. مكافحة بيولوجية للآفات.',
        compliance: 'شهادة GlobalG.A.P (قيد الإعداد). معايير التصدير السعودية.',
        impactAssessment: 'إيجابي - توفير مياه + تنوع حيوي + فرص عمل.',
        greenMeasures: 'طاقة شمسية. سماد عضوي. تعبئة قابلة للتدوير.',
      },
      legalStudy: {
        legalForm: 'شركة ذات مسؤولية محدودة',
        licenses: '1. سجل تجاري. 2. رخصة زراعية. 3. رخصة استيراد معدات. 4. شهادة تصدير. 5. GlobalG.A.P. 6. شهادة ليستير (تصدير).',
        regulations: 'قانون الزراعة، قانون الجمارك، معايير الخليج الغذائية.',
        contracts: 'عقود مع 3 مصدّرين. عقد شحن. عقد تأمين. عقود جملة مع 5 سوبر ماركت.',
        taxObligations: 'ضريبة دخل 15%. VAT 5%. إعفاء تصدير.',
        insurance: 'تأمين زراعي شامل + تأمين مخزون + تأمين نقل.',
        governmentApprovals: 'وزارة الزراعة، الجمارك، الهيئة العامة للمواصفات.',
        complianceStatus: 'مكتمل.',
      },
      marketStudy: {
        targetCustomers: '1. مصدّرون للسعودية (50%). 2. سلاسل سوبر ماركت يمنية (30%). 3. أسواق جملة محلية (15%). 4. فنادق (5%).',
        marketSize: 60000000000,
        expectedShare: 1.0,
        growthRate: 8,
        productPrice: 800000,
        competitors: 'مانجو باكستاني، هندي، مصري. مانجو محلي من مزارع أخرى. ميزتنا: جودة + قرب جغرافي + سعر تنافسي.',
        competitiveAdvantage: '1. مانجو الحديدة طعم فريد. 2. قرب من ميناء الحديدة. 3. تكلفة شحن أقل من المنافسين. 4. ري حديث يعطي جودة موحدة. 5. تصنيف دقيق.',
        pricingStrategy: 'سعر التصدير $1500/طن. الجملة محلياً $750/طن. تجزئة $1000/طن. درجة أولى $1800/طن.',
        distribution: 'شحن بحري من الحديدة لجدة. شحن بري للإمارات. شاحنات مبردة. تخزين بارد 100 طن.',
        promotion: 'معارض الخليج الغذائية. علاقات مع المستوردين. علامة "Yemen Mango". شهادات جودة.',
        demandForecast: 'السعودية تستورد 200,000 طن سنوياً (نمو 8%). الطلب الخليجي يفوق العرض اليمني 5×.',
        segments: 'تصدير (60%)، جملة (25%)، تجزئة (10%)، فنادق (5%).',
        swot: 'القوة: موقع + ري حديث + جودة. الضعف: صعوبة شحن + حجم محدود. الفرص: توسع + قيمة مضافة (عصير، مجفف). التهديدات: منافسة + حرب + شحن.',
        productPrice: 800000,
      },
      technicalStudy: {
        productionCapacity: '20 هكتار × 15 طن/هكتار = 300 طن سنوياً',
        productionVolume: 300000,
        productionCost: 80000000,
        laborRequired: 10,
        location: 'الحديدة - تربة رملية طينية. حرارة 25-38°. ماء وفير. قرب الميناء.',
        utilities: 'مياه: بئر + تنقيط. كهرباء: شبكة + مولد. طريق معبد.',
        productionProcess: '1. حرث وتسوية. 2. حفر جور 5×5م (200 شجرة/هكتار). 3. زراعة الشتلات (مارس). 4. ري تنقيط يومي. 5. تسميد NPK. 6. تقليم سنوي. 7. إثمار من سنة 3. 8. حصاد يدوي (أبريل-يوليو). 9. فرز وتعبئة. 10. تبريد وشحن.',
        rawMaterials: '1. شتلات مطعمة (4400 × 1500). 2. أسمدة NPK (10طن). 3. مبيدات بيولوجية. 4. وقود. 5. عبوات كرتون 5كغ (60,000).',
        equipment: '1. نظام ري تنقيط كامل. 2. بئر + مضخة. 3. جرار صغير 50حصان. 4. حفارة. 5. رشاشة. 6. وحدة فرز. 7. غرفة تبريد 100طن. 8. شاحنة مبردة. 9. مولد 30kW.',
        qualityControl: 'GlobalG.A.P. تتبع كل دفعة. تحليل بقايا مبيدات. فرز دقيق 4 درجات.',
        maintenance: 'صيانة شهرية للري. سنوية للمعدات. يومية للنظافة.',
      },
      financialStudy: {
        initialInvestment: 110000000,
        fixedAssets: 80000000,
        workingCapital: 25000000,
        operatingCosts: 5000000,
        loans: 60000000,
        interestRate: 7,
        loanPeriod: 7,
        yearsData: [
          YEAR(1, 0, 30000000),         // تأسيس - لا إنتاج
          YEAR(2, 0, 25000000),         // نمو
          YEAR(3, 90000000, 55000000),  // أول إنتاج 50%
          YEAR(4, 180000000, 65000000), // إنتاج كامل
          YEAR(5, 210000000, 70000000),
          YEAR(6, 240000000, 75000000),
          YEAR(7, 270000000, 80000000),
          YEAR(8, 300000000, 85000000),
          YEAR(9, 300000000, 88000000),
          YEAR(10, 300000000, 90000000),
        ],
      },
      economicStudy: {
        discountRate: 11,
        riskAnalysis: 'مخاطر منخفضة-متوسطة: 1. آفات (ذبابة الفاكهة) - 30%. 2. صعوبة شحن - 35%. 3. تقلب أسعار - 25%. 4. حرارة شديدة - 20%. خطة: مكافحة بيولوجية + تأمين + تنويع مشترين.',
        sensitivity: '1. الإنتاجية ±20% = ±28% NPV. 2. سعر التصدير ±$200 = ±22% NPV. 3. تكلفة الشحن ±20% = ±8% NPV. نقطة التعادل: 8 طن/هكتار.',
        economicImpact: 'نقد أجنبي $270,000 سنوياً. 30 وظيفة. نموذج تكراري. أثر مضاعف 2.8× = $756,000.',
        costBenefit: 'B/C = 1.6. تكلفة الطن $267، سعر تصدير $1500 = هامش 82%.',
      },
      riskRegister: [
        { id: 'm1', name: 'ذبابة الفاكهة', category: 'بيئي', probability: 3, impact: 4, mitigation: 'فخاخ + رش وقائي + تعقيم', status: 'mitigated' },
        { id: 'm2', name: 'صعوبة الشحن البحري', category: 'سياسي', probability: 4, impact: 3, mitigation: 'شحن بري + تنويع موانئ', status: 'open' },
        { id: 'm3', name: 'تقلب أسعار التصدير', category: 'اقتصادي', probability: 3, impact: 3, mitigation: 'عقود طويلة + تنويع منتجات', status: 'open' },
      ],
      projectPhases: [
        { id: 'mp1', name: 'التراخيص والاستملاك', start: '2026-04-01', end: '2026-06-30', progress: 100, status: 'completed' },
        { id: 'mp2', name: 'إعداد الأرض والري', start: '2026-07-01', end: '2026-09-30', progress: 85, status: 'in-progress' },
        { id: 'mp3', name: 'زراعة الشتلات', start: '2026-10-01', end: '2027-02-28', progress: 60, status: 'in-progress' },
        { id: 'mp4', name: 'العناية سنتان', start: '2027-03-01', end: '2029-02-28', progress: 30, status: 'in-progress' },
        { id: 'mp5', name: 'أول حصاد وتصدير', start: '2029-03-01', end: '2030-02-28', progress: 0, status: 'not-started' },
      ],
    },
  },
  {
    id: 'sample-wheat-farm',
    nameAr: 'مزرعة قمح نموذجية (مشروع استراتيجي مجدي)',
    nameEn: 'Model Wheat Farm (Strategic Viable Project)',
    icon: '🌾',
    descriptionAr: 'مزرعة قمح بمساحة 50 هكتار بنظام الري الحديث - مشروع استراتيجي مجدي يساهم في الأمن الغذائي',
    descriptionEn: '50-hectare wheat farm with modern irrigation - strategic viable project contributing to food security',
    data: {
      name: 'مزرعة القمح الذهبية - 50 هكتار',
      description: 'مزرعة قمح نموذجية بمساحة 50 هكتار (500,000 م²) بنظام الري المحوري الحديث لإنتاج 150 طن قمح سنوياً',
      establishment: {
        projectName: 'مزرعة القمح الذهبية',
        projectType: 'زراعة حقلية - محاصيل استراتيجية',
        projectSector: 'زراعي - محاصيل حبوب',
        projectLocation: 'محافظة ذمار - سهل صنعاء-ذمار الزراعي',
        projectOwner: 'شركة الأمن الغذائي الزراعية',
        projectCapital: 180000000,
        projectDuration: 10,
        projectStartDate: '2026-09-01',
        projectDescription: 'مزرعة قمح نموذجية بمساحة 50 هكتار (500 دونم) تعتمد على الري المحوري الحديث (Center Pivot) لزراعة القمح بشتاء اليمن، بإنتاجية مستهدفة 3 طن/هكتار (إجمالي 150 طن سنوياً)، موسم زراعي واحد مدته 4 أشهر (نوفمبر-فبراير).',
        projectGoals: '1. إنتاج 150 طن قمح محلي عالي الجودة سنوياً. 2. المساهمة في تحقيق الأمن الغذائي وتقليل الاستيراد. 3. إدخال تقنيات الري الحديثة كنموذج يُحتذى. 4. توفير فرص عمل مستدامة في الريف. 5. إنتاج قش القمح كعلف للحيوانات.',
        projectJustification: 'اليمن يستورد أكثر من 90% من احتياجاته من القمح (≈3 مليون طن سنوياً). سعر الطن المستورد ≈$320 + تكاليف شحن. الأراضي الزراعية في ذمار خصبة ومناخها ملائم للقمح. الري المحوري يوفر 40-50% من المياه مقارنة بالري التقليدي. الطلب على القمح المحلي مرتفع ومدعوم حكومياً. كل طن يُنتج محلياً يوفر ≈$350 من النقد الأجنبي.',
      },
      socialStudy: {
        jobsCreated: 8,
        indirectJobs: 15,
        localEmployment: 95,
        genderRatio: 10,
        foreignWorkers: 0,
        annualWages: 28000000,
        trainingPrograms: 'تدريب 20 فلاحاً من المنطقة على تقنيات الري الحديث والزراعة الميكانيكية بالتعاون مع مكتب الزراعة. دورات في إدارة المزارع والتسويق الزراعي.',
        communityImpact: '1. توفير 8 فرص عمل دائمة + 30 فرصة موسمية أيام الحصاد. 2. نقل المعرفة التقنية لـ 20 مزارعاً مجاوراً. 3. توفير قش القمح بسعر مدعوم لمربي الماشية. 4. تحسين بنية الطريق المؤدية للمزرعة بطول 2 كم. 5. دعم 50 أسرة بشكل غير مباشر.',
        developmentImpact: 'المساهمة في الأمن الغذائي الوطني عبر إنتاج 150 طن قمح سنوياً (يكفي لـ 6000 شخص). تشجيع استصلاح الأراضي الزراعية المهملة. خفض فاتورة استيراد القمح بمقدار 50,000$ سنوياً. نموذج قابل للتكرار في محافظات أخرى.',
      },
      environmentalStudy: {
        airEmissions: 'انبعاثات محدودة من الجرارات والمعدات الزراعية (≈2 طن CO2/سنة). يمكن تعويضها بزراعة 200 شجرة حول المزرعة.',
        waterUsage: 'الري المحوري يستهلك 4500 م³/هكتار/موسم = 225,000 م³ سنوياً (مقارنة بـ 450,000 م³ للري التقليدي - توفير 50%). المصدر: بئر ارتوازي عميق 150م بتصرف 30 لتر/ثانية.',
        wasteManagement: '1. قش القمح: 225 طن سنوياً يُباع كعلف للماشية. 2. بقايا الأسمدة: إدارة دقيقة وفق تحاليل التربة. 3. عبوات المبيدات: تجميع وتسليم للجهات المختصة. 4. زيوت المعدات: إعادة تدوير.',
        noiseLevel: '45 dB في الأوقات العادية، 75 dB أثناء تشغيل الجرارات (8 ساعات/أسبوع).',
        energyConsumption: '75,000 kWh/سنة لمضخات المياه + 5000 لتر ديزل للجرارات.',
        mitigationMeasures: '1. زراعة مصدات رياح من الأشجار المحلية. 2. استخدام أسمدة عضوية بنسبة 30%. 3. نظام دفعري للأرض لمنع التملح. 4. مراقبة منسوب المياه الجوفية شهرياً. 5. تطبيق الزراعة الدائرية (تبادل القمح بمحاصيل بقولية).',
        compliance: '1. موافقة مجلس المياه على استخراج المياه. 2. ترخيص استخدام المبيدات من مكتب الزراعة. 3. التزام بمعايير منظمة الأغذية والزراعة (FAO). 4. تقرير الأثر البيئي معتمد من وزارة البيئة.',
        impactAssessment: 'أثر بيئي إيجابي صافي: التربة ستتحسن بالزراعة المنظمة + مصدات الرياح + خفض الانجراف. المخاطر الوحيدة: استنزاف المياه الجوفية (مُخفّف بنظام الري الحديث).',
        greenMeasures: '1. خطة لتركيب 20kW طاقة شمسية لضخ المياه في السنة 3. 2. استخدام سماد عضوي من مزارع الدواجن المجاورة. 3. تطبيق الزراعة بدون حرث (No-till) في 30% من المساحة.',
      },
      legalStudy: {
        legalForm: 'شركة ذات مسؤولية محدودة (LLC) برأس مال 180 مليون ريال يمني',
        licenses: '1. سجل تجاري من الغرفة التجارية. 2. رخصة زراعية من وزارة الزراعة. 3. ترخيص استخراج مياه من مجلس الموارد المائية. 4. رخصة استخدام أراضي زراعية من السلطة المحلية. 5. شهادة تسجيل كمستورد للبذور والأسمدة. 6. موافقة بلدية على المباني الإدارية.',
        regulations: '1. قانون الزراعة رقم (25) لسنة 2010. 2. قانون الموارد المائية رقم (33) لسنة 2002. 3. قانون حماية البيئة رقم (26) لسنة 1995. 4. قانون الاستثمار رقم (15) لسنة 2010. 5. قانون الضرائب رقم (2) لسنة 2015. 6. قانون الجمارك للبذور والأسمدة.',
        contracts: '1. عقد إيجار الأراضي (50 هكتار) مع ملاك الأراضي لمدة 10 سنوات قابلة للتجديد. 2. عقد توريد البذور المعتمدة من مؤسسة الأبحاث الزراعية. 3. عقد صيانة نظام الري مع المورد. 4. عقد تسويق المحصول مع الصوامع الحكومية. 5. عقد تأمين زراعي على المحصول.',
        intellectualProperty: 'العلامة التجارية "قمح ذمار الذهبي" مسجلة. حقوق استخدام بذور محسّنة من معهد بحوث الزراعة مرخصة.',
        taxObligations: '1. ضريبة الدخل 15% على الأرباح. 2. ضريبة القيمة المضافة 5% على المبيعات. 3. إعفاء جمركي على استيراد المعدات الزراعية وفق قانون الاستثمار. 4. رسوم سنوية لرخصة المياه.',
        insurance: '1. تأمين زراعي شامل على المحصول (5% من قيمة المحصول). 2. تأمين على المعدات والآلات. 3. تأمين المسؤولية المدنية. 4. تأمين على العمال.',
        governmentApprovals: '1. وزارة الزراعة والري. 2. مجلس الموارد المائية. 3. السلطة المحلية بالمحافظة. 4. الهيئة العامة للبيئة. 5. الغرفة التجارية. 6. مكتب العمل (للعاملين).',
        complianceStatus: 'متقدم - تم الحصول على 4 من 6 تراخيص. الترخيصان المتبقيان (مياه وبيئة) متوقع إنجازهما خلال 60 يوماً.',
      },
      marketStudy: {
        targetCustomers: '1. الصوامع الحكومية (المؤسسة العامة للحبوب) - 60% من الإنتاج. 2. المطاحن الخاصة المحلية - 25%. 3. تجار الجملة للحبوب - 10%. 4. التعاونيات الزراعية - 5%.',
        marketSize: 96000000000,
        expectedShare: 0.16,
        growthRate: 5,
        productPrice: 200000,
        competitors: '1. الواردات (90% من السوق): روسيا، أوكرانيا، أستراليا. 2. مزارع محلية كبيرة (5 مزارع) في ذمار وحجة وصعدة. 3. مزارع صغيرة تقليدية. ميزتنا: الجودة المحلية + الدعم الحكومي + الطزاجة.',
        competitiveAdvantage: '1. الري الحديث يضاعف الإنتاجية (3 طن/هكتار مقابل 1 طن تقليدي). 2. تكلفة منخفضة بسبب قرب السوق. 3. جودة عالية (بروتين 12-14%). 4. سلسلة توريد قصيرة. 5. دعم حكومي بأسعار شراء مضمونة. 6. خبرة فنية من شراكة مع معهد بحوث الزراعة.',
        pricingStrategy: 'سعر الطن 200,000 ريال يمني ($377) - أقل من المستورد بـ 15%. للصوامع سعر تفضيلي 185,000 ريال. خصم 5% للمشترين بالجملة (10+ طن).',
        distribution: '1. نقل مباشر بالشاحنات من المزرعة للصوامع (200 كم). 2. تخزين مؤقت في مخازن المزرعة (سعة 200 طن). 3. تعبئة في شكاير 50 كجم للأسواق المحلية. 4. خطة لتأسيس مركز تجميع في صنعاء.',
        promotion: '1. علاقات مع مسؤولي الصوامع والمطاحن. 2. مشاركة في معارض الزراعة. 3. شهادة جودة من وزارة الزراعة. 4. علامة "منتج محلي" على التغليف. 5. حملة توعوية بأهمية القمح المحلي.',
        demandForecast: 'الطلب على القمح في اليمن ينمو 5% سنوياً بسبب النمو السكاني (3%). استهلاك الفرد 120 كجم/سنة (من الأعلى عالمياً). العجز الحالي 2.7 مليون طن يستورد. الفرصة كبيرة لتوسع مستقبلي.',
        growthRate: 5,
        segments: '1. الصوامع الحكومية (60%). 2. مطاحن خاصة (25%). 3. تجار جملة (10%). 4. تعاونيات (5%).',
        swot: 'القوة: أرض خصبة + ري حديث + موقع استراتيجي. الضعف: اعتماد على بئر واحد + خبرة محدودة بسلالات القمح. الفرص: دعم حكومي + أسعار شراء مضمونة + توسع محتمل لـ 100 هكتار. التهديدات: تقلبات المناخ + ارتفاع تكاليف الوقود + منافسة الواردات المدعومة.',
        productPrice: 200000,
      },
      technicalStudy: {
        productionCapacity: '50 هكتار × 3 طن/هكتار = 150 طن قمح/سنة + 225 طن قش',
        productionVolume: 150000,
        productionCost: 65000000,
        laborRequired: 8,
        location: 'محافظة ذمار - سهل زراعي على بُعد 200 كم جنوب صنعاء. تربة طينية رملية خصبة (PH 7.2). مناخ شبه جاف، أمطار 250 مم/سنة. مصدر مائي: بئر ارتوازي 150م عمق.',
        utilities: '1. مياه: بئر ارتوازي تصرف 30 لتر/ثانية + خزان تجميع 500 م³. 2. كهرباء: شبكة عامة + مولد احتياطي 50 KVA. 3. وقود: 5000 لتر ديزل/سنة للجرارات. 4. اتصالات: إنترنت للأنظمة الذكية.',
        productionProcess: '1. تحضير الأرض (سبتمبر): حرث + تسوية + تخطيط. 2. البذار (نوفمبر): بذور معتمدة (صنف سردا-1 أو بحوث 1) بمعدل 120 كجم/هكتار. 3. التسميد (نوفمبر-ديسمبر): NPK 15-15-15 بمعدل 500 كجم/هكتار + يوريا 200 كجم/هكتار. 4. الري المحوري: دورات كل 5 أيام، 50 مم/دورة. 5. مكافحة الحشائش (ديسمبر): مبيدات انتقائية. 6. مكافحة الآفات (يناير): مراقبة دقيقة. 7. الحصاد (فبراير-مارس): حصاد آلي بدراسات. 8. التخزين: تجفيف للرطوبة 13% + تخزين في شكاير.',
        rawMaterials: '1. بذور قمح معتمدة: 6 طن/سنة × 1500 ر.ي/كجم = 9 ملايين. 2. أسمدة NPK: 25 طن × 8000 ر.ي/كجم = 200 مليون. 3. يوريا: 10 طن × 6000 = 60 مليون. 4. مبيدات حشائش: 200 لتر × 8000 = 1.6 مليون. 5. وقود: 5000 لتر × 1500 = 7.5 مليون. 6. زيوت وشحوم: 2 مليون. 7. شكاير 50 كجم: 3000 × 200 = 600 ألف. الإجمالي: ≈ 31 مليون ريال يمني/سنة.',
        equipment: '1. نظام ري محوري (Center Pivot) نصف دائري - 2 وحدات × 25 هكتار. 2. جرار زراعي 100 حصان. 3. محراث متنقل + تسوية. 4. آلة بذر آلية. 5. آلة تسميد. 6. رشاشة آلية للمبيدات. 7. حصادة دراسة (Combine). 8. شاحنة نقل 5 طن. 9. مضخة مياه غاطسة 30 لتر/ثانية. 10. خزان تجميع 500 م³. 11. مولد كهرباء 50 KVA. 12. معدات تجفيف وتعبئة.',
        machinery: 'الري المحوري (Valley/Valmont): هيكل فولاذي مجلفن 400م طول، 11 برج، نظام تشغيل هيدروليكي، فوهات Spinner. العمر الافتراضي 20 سنة. تكلفة الوحدة $45,000.',
        qualityControl: '1. تحليل التربة قبل الزراعة (NPK + PH + ملوحة). 2. فحص البذور (نسبة الإنبات >90%). 3. رصد نمو النباتات أسبوعياً. 4. تحليل رطوبة القمح قبل الحصاد. 5. اختبار الجودة بعد الحصاد (بروتين + وزن الحبة + شوائب). 6. شهادة جودة من وزارة الزراعة.',
        maintenance: '1. صيانة وقائية شهرية لنظام الري. 2. صيانة دورية للجرارات كل 100 ساعة عمل. 3. تنظيف فوهات الري بعد كل موسم. 4. معايرة المعدات قبل الاستخدام. 5. برنامج صيانة معتمد من الموردين.',
      },
      financialStudy: {
        initialInvestment: 150000000,
        fixedAssets: 110000000,
        workingCapital: 35000000,
        operatingCosts: 5000000,
        loans: 90000000,
        interestRate: 7,
        loanPeriod: 7,
        yearsData: [
          YEAR(1, 38000000, 22000000),
          YEAR(2, 42000000, 23000000),
          YEAR(3, 46000000, 23500000),
          YEAR(4, 50000000, 24000000),
          YEAR(5, 55000000, 24500000),
          YEAR(6, 60000000, 25000000),
          YEAR(7, 65000000, 25500000),
          YEAR(8, 70000000, 26000000),
          YEAR(9, 75000000, 26500000),
          YEAR(10, 80000000, 27000000),
        ],
      },
      economicStudy: {
        discountRate: 10,
        riskAnalysis: 'المخاطر الرئيسية: 1. مناخية (جفاف، أمطار متأخرة) - احتمال 20%، تأثير متوسط. 2. ارتفاع تكاليف المدخلات (وقود، أسمدة) - احتمال 50%، تأثير عالي. 3. آفات زراعية (صدأ القمح) - احتمال 15%، تأثير عالي. 4. انخفاض منسوب المياه الجوفية - احتمال 30%، تأثير عالي طويل المدى. 5. عدم استقرار أسعار الشراء الحكومي - احتمال 25%، تأثير متوسط. خطة التخفيف: تأمين زراعي + تنوع مصادر الدخل (قش + بذور) + ري حديث + مراقبة دورية للمياه.',
        sensitivity: 'تحليل الحساسية: تأثير ±10% في المتغيرات على NPV: 1. إنتاجية/هكتار (الأكثر تأثيراً): ±10% = ∓35% NPV. 2. سعر بيع الطن: ±10% = ±28% NPV. 3. تكلفة الأسمدة: ±10% = ∓12% NPV. 4. تكلفة الوقود: ±10% = ∓8% NPV. 5. معدل الخصم: ±2% = ∓18% NPV. التوصية: تركيز الجهود على رفع الإنتاجية فوق 3 طن/هكتار عبر سلالات محسّنة وتسميد دقيق.',
        economicImpact: '1. توفير نقد أجنبي ≈ $57,000 سنوياً (150 طن × $380). 2. مساهمة في الناتج المحلي ≈ 30 مليون ريال يمني. 3. أثر مضاعف اقتصادي 2.5× = 75 مليون. 4. خلق 23 فرصة عمل مباشرة وغير مباشرة. 5. دعم 5 موردين محليين (وقود، أسمدة، صيانة). 6. نموذج تكراري لـ 20 مزرعة مماثلة = إنتاج إضافي 3000 طن.',
        costBenefit: 'نسبة المنفعة/التكلفة (B/C Ratio) = 1.34 (أكبر من 1 = مجدي). التكلفة الاقتصادية لكل طن قمح = $300 مقابل $380 للمستورد = وفر $80/طن. فترة استرداد معدّلة بالمخاطر = 5.8 سنة.',
        sensitivity: 'تحليل الحساسية يُظهر أن المشروع يبقى مجدياً حتى مع انخفاض الإنتاجية إلى 2.4 طن/هكتار (20% أقل من المتوقع). نقطة التعادل = 1.8 طن/هكتار.',
        riskAnalysis: 'تصنيف المخاطر: منخفض-متوسط. احتمال فشل كامل < 5%. خطة طوارئ: تأمين + تنويع محاصيل + احتياطي نقدي 15%.',
      },
      riskRegister: [
        { id: 'r1', name: 'انخفاض الإنتاجية بسبب الجفاف', category: 'بيئي', probability: 3, impact: 4, mitigation: 'تأمين زراعي + ري تكميلي + اختيار سلالات مقاومة للجفاف', status: 'open' },
        { id: 'r2', name: 'ارتفاع أسعار الوقود', category: 'اقتصادي', probability: 4, impact: 3, mitigation: 'تحويل للطاقة الشمسية في السنة 3 + كفاءة طاقة', status: 'open' },
        { id: 'r3', name: 'صدأ القمح (مرض فطري)', category: 'بيئي', probability: 3, impact: 5, mitigation: 'سلالات مقاومة + رصد مبكر + مبيدات وقائية', status: 'mitigated' },
        { id: 'r4', name: 'استنزاف المياه الجوفية', category: 'بيئي', probability: 3, impact: 4, mitigation: 'ري محوري موفر + مراقبة شهرية للمنسوب + زراعة بقولية بالتناوب', status: 'open' },
        { id: 'r5', name: 'تأخر دفعات الصوامع الحكومية', category: 'مالي', probability: 4, impact: 3, mitigation: 'تنويع المشترين + احتياطي نقدي + تسهيلات بنكية', status: 'open' },
      ],
      swotAnalysis: {
        strengths: [
          { id: 's1', text: 'أراضي خصبة في سهل ذمار بتربة طينية رملية ومناخ ملائم' },
          { id: 's2', text: 'نظام ري محوري حديث يضاعف الإنتاجية ويوفر 50% من المياه' },
          { id: 's3', text: 'قرب السوق (200 كم من صنعاء) يقلل تكاليف النقل' },
          { id: 's4', text: 'شراكة مع معهد بحوث الزراعة للدعم الفني والبذور المعتمدة' },
          { id: 's5', text: 'دعم حكومي وأسعار شراء مضمونة من الصوامع الحكومية' },
        ],
        weaknesses: [
          { id: 'w1', text: 'اعتماد على بئر واحد كمصدر مائي - نقطة فشل واحدة' },
          { id: 'w2', text: 'خبرة محدودة بالسلالات المحسّنة وتقنيات الزراعة المتقدمة' },
          { id: 'w3', text: 'استثمار أولي مرتفع (150 مليون ريال يمني)' },
          { id: 'w4', text: 'موسم زراعي واحد سنوياً (4 أشهر) يحد من الإيرادات' },
        ],
        opportunities: [
          { id: 'o1', text: 'توسع محتمل لـ 100 هكتار مضاعفاً الإنتاج' },
          { id: 'o2', text: 'دعم حكومي متزايد للزراعة ضمن خطة الأمن الغذائي' },
          { id: 'o3', text: 'إمكانية تصنيع القمح محلياً (مطحن خاص)' },
          { id: 'o4', text: 'تصدير قش القمح كعلف للأسواق المجاورة' },
          { id: 'o5', text: 'زراعة محاصيل بديلة بالموسم الصيفي (ذرة، عباد الشمس)' },
        ],
        threats: [
          { id: 't1', text: 'تقلبات مناخية (جفاف، أمطار متأخرة) تؤثر على الإنتاجية' },
          { id: 't2', text: 'ارتفاع تكاليف المدخلات (وقود، أسمدة مستوردة)' },
          { id: 't3', text: 'منافسة الواردات المدعومة من روسيا وأوكرانيا' },
          { id: 't4', text: 'انخفاض منسوب المياه الجوفية على المدى الطويل' },
          { id: 't5', text: 'عدم استقرار السياسات الحكومية الداعمة' },
        ],
      },
      projectPhases: [
        { id: 'p1', name: 'التراخيص والاستملاك', start: '2026-09-01', end: '2026-11-30', progress: 100, status: 'completed' },
        { id: 'p2', name: 'إعداد الأرض والبنية التحتية', start: '2026-12-01', end: '2027-02-28', progress: 80, status: 'in-progress' },
        { id: 'p3', name: 'تركيب نظام الري المحوري', start: '2027-01-15', end: '2027-03-15', progress: 60, status: 'in-progress' },
        { id: 'p4', name: 'شراء المعدات والآلات', start: '2027-02-01', end: '2027-04-30', progress: 40, status: 'in-progress' },
        { id: 'p5', name: 'الموسم الزراعي الأول', start: '2027-11-01', end: '2028-03-31', progress: 0, status: 'not-started' },
        { id: 'p6', name: 'الحصاد والتسويق', start: '2028-03-01', end: '2028-05-31', progress: 0, status: 'not-started' },
      ],
    },
  },
];

export function getSampleById(id: string): SampleProject | undefined {
  return SAMPLE_PROJECTS.find((s) => s.id === id);
}
